const { configuration, jsonHeaders } = require('./_lib/auth');
const { requireUser } = require('./_lib/require-user');

async function rest(url,key,path){const r=await fetch(url+'/rest/v1/'+path,{headers:jsonHeaders(key),signal:AbortSignal.timeout(10000)});const d=await r.json().catch(()=>[]);if(!r.ok)throw Error(d.message||'Manufacturing read failed');return d;}
const fixtures={
 planner:{total:45,destinations:['Amityville','Bohemia','Riverhead','Annex'],kpis:[['Destinations needing stock',4],['Finished SKUs below par',45],['Suggested doors to build',312],['BOM-ready quantity',268],['Component-blocked quantity',44],['Already in production',61]].map(([label,value])=>({label,value})),rows:[
  {id:'p1',destination:'Amityville',sku:'2PSR36SNRH',product:'2 Panel Brogan 36 in · Satin Nickel · RH',onHand:-4,allocated:0,available:-4,par:18,incoming:0,inProduction:0,suggested:22,bomStatus:'Ready'},
  {id:'p2',destination:'Amityville',sku:'CD3080PHRHSN2P',product:'Carrara prehung 30 × 80 · RH',onHand:3,allocated:8,available:-5,par:14,incoming:2,inProduction:0,suggested:17,bomStatus:'Ready'},
  {id:'p3',destination:'Bohemia',sku:'2PSR32SNLH',product:'2 Panel Brogan 32 in · Satin Nickel · LH',onHand:2,allocated:1,available:1,par:12,incoming:0,inProduction:4,suggested:7,bomStatus:'Shortage'},
  {id:'p4',destination:'Riverhead',sku:'5PSR32SNLH',product:'5 Panel Shaker 32 in · Satin Nickel · LH',onHand:0,allocated:0,available:0,par:10,incoming:3,inProduction:2,suggested:5,bomStatus:'Ready'}]},
 board:{NIGHTHAWK:[{id:101,number:'MWO-20260902-000101',destination:'Amityville',priority:'urgent',requested:'Sep 4',skus:3,planned:48,good:18,remaining:30,status:'In Production',action:'Record Progress'},{id:102,number:'MWO-20260902-000102',destination:'Riverhead',priority:'normal',requested:'Sep 5',skus:2,planned:24,good:0,remaining:24,status:'Released',action:'Start'}],TERMINATOR:[{id:103,number:'MWO-20260902-000103',destination:'Bohemia',priority:'high',requested:'Sep 4',skus:4,planned:56,good:40,remaining:16,status:'Partially Completed',action:'Record Progress'},{id:104,number:'MWO-20260902-000104',destination:'Annex',priority:'normal',requested:'Sep 6',skus:1,planned:12,good:12,remaining:0,status:'Completed',action:'Review Transfer'}]},
 orders:{total:4,rows:[
  {id:101,number:'MWO-20260902-000101',created:'Sep 2',destination:'Amityville',machine:'Nighthawk',status:'In Production',planned:48,good:18,remaining:30,transferStatus:'Transfer pending',requested:'Sep 4'},
  {id:103,number:'MWO-20260902-000103',created:'Sep 2',destination:'Bohemia',machine:'Terminator',status:'Partially Completed',planned:56,good:40,remaining:16,transferStatus:'Transfer pending',requested:'Sep 4'},
  {id:104,number:'MWO-20260902-000104',created:'Sep 1',destination:'Annex',machine:'Terminator',status:'Completed',planned:12,good:12,remaining:0,transferStatus:'Transfer created',requested:'Sep 6'},
  {id:100,number:'MWO-20260901-000100',created:'Sep 1',destination:'Riverhead',machine:'Nighthawk',status:'Closed',planned:30,good:29,remaining:0,transferStatus:'Transfer created',requested:'Sep 3'}]},
 boms:{total:2,rows:[{id:201,sku:'2PSR36SNRH',product:'2 Panel Brogan 36 in · RH',version:3,status:'Active',components:7,validation:'Ready',source:'Qoblex import',updated:'Sep 1',componentRows:[{sku:'SLAB-2P36',name:'2 Panel slab 36 in',quantity:1,uom:'EA',status:'Active'},{sku:'JAMB-496',name:'4-9/16 primed jamb',quantity:17,uom:'LF',status:'Active'},{sku:'HINGE-SN',name:'Satin nickel hinge',quantity:3,uom:'EA',status:'Active'}]},{id:202,sku:'CD3080PHRHSN2P',product:'Carrara prehung 30 × 80 · RH',version:2,status:'Active',components:8,validation:'Ready',source:'Qoblex import',updated:'Aug 30',componentRows:[{sku:'SLAB-CAR30',name:'Carrara slab 30 in',quantity:1,uom:'EA',status:'Active'}]}]}
};

module.exports=async(req,res)=>{const isolatedPreview=process.env.VERCEL_ENV==='preview'&&process.env.MANUFACTURING_UI_FIXTURES==='true'&&process.env.PREVIEW_TEST_SESSION==='enabled';if(process.env.VERCEL_ENV==='preview'&&!isolatedPreview)return res.status(503).json({ok:false,error:'preview_fixture_configuration_required'});const auth=isolatedPreview?{ok:true,user:{id:999999,role:'admin'}}:await requireUser(req);if(!auth.ok)return res.status(auth.status).json({ok:false,error:auth.error});if(req.method!=='GET')return res.status(405).json({ok:false,error:'method_not_allowed'});const view=String(req.query?.view||'planner');const pageSize=Math.min(100,Math.max(1,Number(req.query?.pageSize)||25));
 try{
  if(isolatedPreview)return res.status(200).json({ok:true,fixture:true,testEnvironment:true,permissions:['manufacturing_view_planner','manufacturing_view_work_orders','manufacturing_print_packet','manufacturing_create_draft','manufacturing_release','manufacturing_record_progress'],...(fixtures[view]||fixtures.planner)});
  if(process.env.MANUFACTURING_V2_ENABLED!=='true')return res.status(404).json({ok:false,error:'manufacturing_v2_disabled'});
  const {url,serviceRoleKey}=configuration();const flags=await rest(url,serviceRoleKey,'mfg_feature_flags?flag_key=eq.manufacturing_v2&enabled=eq.true&select=flag_key&limit=1');if(!flags.length)return res.status(404).json({ok:false,error:'manufacturing_v2_disabled'});
  const permissionNames=['manufacturing_view_planner','manufacturing_view_work_orders','manufacturing_print_packet','manufacturing_create_draft','manufacturing_release','manufacturing_record_progress','manufacturing_bom_admin','manufacturing_cost_admin'];
  const permissions=[];for(const permission of permissionNames){const r=await fetch(url+'/rest/v1/rpc/mfg_actor_can',{method:'POST',headers:jsonHeaders(serviceRoleKey),body:JSON.stringify({p_actor_user_id:Number(auth.user.id),p_permission:permission})});if(r.ok&&await r.json()===true)permissions.push(permission)}
  if(!permissions.some(x=>x.startsWith('manufacturing_view_')))return res.status(403).json({ok:false,error:'manufacturing_view_permission_denied'});
  const orders=await rest(url,serviceRoleKey,'mfg_work_orders?select=id,work_order_number,status,machine_code,priority,requested_completion_date,created_at,destination:locations!mfg_work_orders_destination_location_id_fkey(name),mfg_work_order_lines(planned_quantity,good_quantity,remaining_quantity)&order=created_at.desc&limit='+pageSize);
  const rows=orders.map(w=>({id:w.id,number:w.work_order_number,created:String(w.created_at).slice(0,10),destination:w.destination?.name||'—',machine:w.machine_code,status:w.status,planned:(w.mfg_work_order_lines||[]).reduce((s,x)=>s+Number(x.planned_quantity),0),good:(w.mfg_work_order_lines||[]).reduce((s,x)=>s+Number(x.good_quantity),0),remaining:(w.mfg_work_order_lines||[]).reduce((s,x)=>s+Number(x.remaining_quantity),0),transferStatus:'Transfer pending',requested:w.requested_completion_date||'—'}));
  if(view==='board')return res.json({ok:true,permissions,NIGHTHAWK:rows.filter(x=>x.machine==='NIGHTHAWK'),TERMINATOR:rows.filter(x=>x.machine==='TERMINATOR')});
  if(view==='orders')return res.json({ok:true,permissions,total:rows.length,rows});
  return res.json({ok:true,permissions,total:0,rows:[],kpis:[],destinations:[]});
 }catch(error){return res.status(400).json({ok:false,error:error.message||'manufacturing_ui_failed'})}}
