const {randomUUID}=require('node:crypto');
const {configuration,jsonHeaders}=require('./_lib/auth');
const {requireUser}=require('./_lib/require-user');
const PILOT='BM-MFG-PILOT-001';
const GENERAL=['manufacturing_release_enabled','manufacturing_completion_enabled','manufacturing_inventory_mutations_enabled','manufacturing_shopify_outbound_enabled','manufacturing_transfer_handoff_enabled'];
const PILOT_FLAGS=['manufacturing_pilot_release_enabled','manufacturing_pilot_completion_enabled','manufacturing_pilot_inventory_enabled','manufacturing_pilot_outbound_enabled','manufacturing_pilot_transfer_enabled'];
const safeInt=(v,d,min,max)=>Math.min(max,Math.max(min,parseInt(v,10)||d));
const enc=v=>encodeURIComponent(String(v));
const sum=(a,k)=>(a||[]).reduce((n,x)=>n+Number(x[k]||0),0);
const action=s=>({Released:'Start','In Production':'Record Progress',Paused:'Resume',Completed:'Review Transfer'}[s]||'View');
async function rest(url,key,path,count=false){const response=await fetch(url+'/rest/v1/'+path,{headers:{...jsonHeaders(key),...(count?{Prefer:'count=exact'}:{})},signal:AbortSignal.timeout(12000)});const data=await response.json().catch(()=>[]);if(!response.ok)throw Error(data.message||'Manufacturing read failed');const total=count?Number((response.headers.get('content-range')||'').split('/')[1]):data.length;return {data,total:Number.isFinite(total)?total:data.length}}
function orderRow(w,pilotPaused){const lines=w.mfg_work_order_lines||[],pilotOwned=w.pilot_identifier===PILOT&&Number(w.pilot_work_order_id)===Number(w.id),paused=pilotOwned&&pilotPaused;return {id:w.id,number:w.work_order_number,created:String(w.created_at||'').slice(0,10),destination:w.destination?.name||'—',machine:w.machine_code||'Unassigned',status:paused?`${w.status} · Pilot paused`:w.status,lifecycleStatus:w.status,planned:sum(lines,'planned_quantity'),good:sum(lines,'good_quantity'),remaining:sum(lines,'remaining_quantity'),skus:lines.length,priority:w.priority||'normal',requested:w.requested_completion_date||'—',transferStatus:'Not created',action:paused?'Pilot paused':action(w.status),actionDisabled:paused,pilotOwned,lines:lines.map(x=>({id:x.id,sku:x.products?.sku||'—',product:x.products?.name||'—',planned:Number(x.planned_quantity||0),good:Number(x.good_quantity||0),remaining:Number(x.remaining_quantity||0)}))}}
module.exports=async function manufacturingUi(req,res){
 const started=performance.now(),requestId=req.headers['x-request-id']||randomUUID(),marks=[];
 const mark=name=>marks.push([name,performance.now()-started]);
 const finish=(status,payload)=>{mark('total');let prior=0;res.setHeader('x-request-id',requestId);res.setHeader('server-timing',marks.map(([n,t])=>{const d=t-prior;prior=t;return `${n};dur=${Math.max(.1,d).toFixed(1)}`}).join(', '));res.setHeader('cache-control','private, no-store');const body={...payload,requestId};console.info(JSON.stringify({event:'manufacturing_ui',requestId,view:req.query?.view||'planner',status,durationMs:Math.round(marks.at(-1)[1]),payloadBytes:Buffer.byteLength(JSON.stringify(body))}));return res.status(status).json(body)};
 if(req.method!=='GET')return finish(405,{ok:false,error:'method_not_allowed'});
 const auth=await requireUser(req);mark('auth');if(!auth.ok)return finish(auth.status,{ok:false,error:auth.error});
 if(process.env.MANUFACTURING_V2_ENABLED!=='true')return finish(404,{ok:false,error:'manufacturing_v2_disabled'});
 try{
  const {url,serviceRoleKey}=configuration(),beta=(await rest(url,serviceRoleKey,`mfg_beta_users?user_id=eq.${Number(auth.user.id)}&select=user_id&limit=1`)).data;mark('access');
  if(!beta.length)return finish(403,{ok:false,error:'manufacturing_beta_access_denied'});
  const view=String(req.query?.view||'planner'),page=safeInt(req.query?.page,1,1,100000),pageSize=safeInt(req.query?.pageSize,25,1,100),offset=(page-1)*pageSize;
  const [fr,gr]=await Promise.all([rest(url,serviceRoleKey,'mfg_feature_flags?select=flag_key,enabled&order=flag_key'),rest(url,serviceRoleKey,`manufacturing_pilot_gate?pilot_identifier=eq.${PILOT}&select=pilot_identifier,enabled,approved_work_order_id,approved_finished_product_id,approved_bom_id,origin_location_id,destination_location_id,machine_code`)]);mark('controls');
  const fm=Object.fromEntries(fr.data.map(x=>[x.flag_key,x.enabled===true]));if(!fm.manufacturing_v2||!fm.manufacturing_view_enabled)return finish(404,{ok:false,error:'manufacturing_v2_disabled'});
  const gate=gr.data[0]||null,pilotPaused=Boolean(gate?.approved_work_order_id)&&gate.enabled!==true;
  const controlState={pilotIdentifier:PILOT,gateEnabled:gate?.enabled===true,approvedWorkOrderId:gate?.approved_work_order_id||null,pilotPaused,pilotCapabilities:Object.fromEntries(PILOT_FLAGS.map(x=>[x,fm[x]===true])),generalMutations:Object.fromEntries(GENERAL.map(x=>[x,fm[x]===true])),statusLabel:pilotPaused?`Restricted pilot paused — work order ID ${gate.approved_work_order_id} remains bound.`:gate?.enabled?`Restricted pilot active for work order ID ${gate.approved_work_order_id} only.`:'Manufacturing planning access is available; no restricted pilot is active.'};
  const common={ok:true,permissions:['manufacturing_view_planner','manufacturing_view_work_orders','manufacturing_print_packet'],controlState,page,pageSize};
  const os='id,work_order_number,status,machine_code,priority,created_at,requested_completion_date,pilot_identifier,pilot_work_order_id,destination:locations!mfg_work_orders_destination_location_id_fkey(id,name),mfg_work_order_lines(id,finished_product_id,planned_quantity,good_quantity,remaining_quantity,products(id,sku,name))';
  if(view==='order-detail'){const id=safeInt(req.query?.id,0,1,Number.MAX_SAFE_INTEGER),rows=(await rest(url,serviceRoleKey,`mfg_work_orders?id=eq.${id}&select=${os}&limit=1`)).data;mark('query');return rows.length?finish(200,{...common,row:orderRow(rows[0],pilotPaused)}):finish(404,{ok:false,error:'work_order_not_found'})}
  if(view==='bom-detail'){const id=safeInt(req.query?.id,0,1,Number.MAX_SAFE_INTEGER),rows=(await rest(url,serviceRoleKey,`mfg_bom_versions?id=eq.${id}&select=id,source_bom_id,version_number,status,source_type,finished_product_id,component_hash,products!mfg_bom_versions_finished_product_id_fkey(id,sku,name),mfg_bom_version_components(component_product_id,quantity_per_yield,products(id,sku,name,uom))&limit=1`)).data;mark('query');if(!rows.length)return finish(404,{ok:false,error:'bom_not_found'});const b=rows[0];return finish(200,{...common,row:{id:b.id,finishedProductId:b.finished_product_id,sku:b.products?.sku||'—',product:b.products?.name||'—',version:b.version_number||1,status:b.status,source:b.source_type==='qoblex_import'?'Qoblex import':'BM manual',componentHash:b.component_hash,componentRows:(b.mfg_bom_version_components||[]).map(c=>({sku:c.products?.sku||'—',name:c.products?.name||'—',quantity:c.quantity_per_yield,uom:c.products?.uom||'EA',status:'Active'}))}})}
  if(view==='board'){const r=await rest(url,serviceRoleKey,`mfg_work_orders?status=not.in.(Draft,Cancelled,Closed)&select=${os}&order=created_at.desc&limit=100`);mark('query');const rows=r.data.map(w=>orderRow(w,pilotPaused));return finish(200,{...common,NIGHTHAWK:rows.filter(x=>x.machine==='NIGHTHAWK'),TERMINATOR:rows.filter(x=>x.machine==='TERMINATOR')})}
  if(view==='orders'){const search=String(req.query?.search||'').trim(),filter=search?`&work_order_number=ilike.*${enc(search)}*`:'';const r=await rest(url,serviceRoleKey,`mfg_work_orders?select=${os}${filter}&order=created_at.desc&offset=${offset}&limit=${pageSize}`,true);mark('query');return finish(200,{...common,total:r.total,rows:r.data.map(w=>orderRow(w,pilotPaused))})}
  if(view==='boms'){const search=String(req.query?.search||'').trim(),pj=search?'products!mfg_bom_versions_finished_product_id_fkey!inner':'products!mfg_bom_versions_finished_product_id_fkey',filter=search?`&products.or=(sku.ilike.*${enc(search)}*,name.ilike.*${enc(search)}*)`:'';const r=await rest(url,serviceRoleKey,`mfg_bom_versions?select=id,source_bom_id,version_number,status,source_type,created_at,activated_at,finished_product_id,component_hash,${pj}(id,sku,name),mfg_bom_version_components(count)${filter}&order=created_at.desc&offset=${offset}&limit=${pageSize}`,true);mark('query');const rows=r.data.map(b=>{const components=Number(b.mfg_bom_version_components?.[0]?.count||0);return {id:b.id,finishedProductId:b.finished_product_id,sku:b.products?.sku||'—',product:b.products?.name||'—',version:b.version_number||1,status:b.status,components,validation:components?'Ready':'Missing',source:b.source_type==='qoblex_import'?'Qoblex import':'BM manual',updated:String(b.activated_at||b.created_at||'').slice(0,10),componentHash:b.component_hash}});return finish(200,{...common,total:r.total,rows})}
  const locations=(await rest(url,serviceRoleKey,'locations?active=eq.true&code=neq.730&select=id,name,code&order=name')).data,destination=String(req.query?.destination||'').trim(),search=String(req.query?.search||'').trim(),chosen=destination?locations.filter(x=>x.name===destination):locations;
  const lf=chosen.length?`location_id=in.(${chosen.map(x=>x.id).join(',')})`:'location_id=eq.-1',pj=search?'products!inner':'products',pf=search?`&products.or=(sku.ilike.*${enc(search)}*,name.ilike.*${enc(search)}*)`:'';
  const pr=await rest(url,serviceRoleKey,`product_par_levels?${lf}&select=id,location_id,product_id,par_quantity,${pj}(id,sku,name),locations(id,name)${pf}&order=par_quantity.desc&offset=${offset}&limit=${pageSize}`,true),pars=pr.data,pids=[...new Set(pars.map(x=>Number(x.product_id)))],lids=[...new Set(pars.map(x=>Number(x.location_id)))];
  const [br,bvr,or]=pids.length?await Promise.all([rest(url,serviceRoleKey,`inventory_balances?product_id=in.(${pids})&location_id=in.(${lids})&select=product_id,location_id,quantity,allocated_quantity`),rest(url,serviceRoleKey,`mfg_bom_versions?finished_product_id=in.(${pids})&status=eq.active&select=id,finished_product_id`),rest(url,serviceRoleKey,`mfg_work_orders?status=not.in.(Cancelled,Closed)&destination_location_id=in.(${lids})&select=id,destination_location_id,mfg_work_order_lines(finished_product_id,remaining_quantity)&limit=100`)]):[{data:[]},{data:[]},{data:[]}];mark('query');
  const rows=pars.map(p=>{const b=br.data.find(x=>Number(x.product_id)===Number(p.product_id)&&Number(x.location_id)===Number(p.location_id)),onHand=Number(b?.quantity||0),allocated=Number(b?.allocated_quantity||0),available=onHand-allocated,target=Number(p.par_quantity||0),inProduction=or.data.filter(x=>Number(x.destination_location_id)===Number(p.location_id)).flatMap(x=>x.mfg_work_order_lines||[]).filter(x=>Number(x.finished_product_id)===Number(p.product_id)).reduce((n,x)=>n+Number(x.remaining_quantity||0),0),suggested=Math.max(target-available-inProduction,0);return {id:`${p.location_id}:${p.product_id}`,destination:p.locations?.name||'—',sku:p.products?.sku||'—',product:p.products?.name||'—',onHand,allocated,available,par:target,incoming:0,inProduction,suggested,bomStatus:bvr.data.some(x=>Number(x.finished_product_id)===Number(p.product_id))?'Ready':'Missing'}});
  return finish(200,{...common,total:pr.total,destinations:locations.map(x=>x.name),rows,kpis:[{label:'Destinations needing stock',value:new Set(rows.filter(x=>x.suggested>0).map(x=>x.destination)).size},{label:'Finished SKUs below par',value:rows.filter(x=>x.suggested>0).length},{label:'Suggested doors to build',value:sum(rows,'suggested')},{label:'BOM-ready quantity',value:rows.filter(x=>x.bomStatus==='Ready').reduce((n,x)=>n+x.suggested,0)},{label:'Component-blocked quantity',value:0},{label:'Already in production',value:sum(rows,'inProduction')}]});
 }catch(error){return finish(error.name==='TimeoutError'?504:400,{ok:false,error:error.name==='TimeoutError'?'manufacturing_read_timeout':error.message||'manufacturing_ui_failed'})}
};
