create table if not exists public.shopify_sales_sync_windows (
  id bigint generated by default as identity primary key,
  window_start date not null,
  window_end date not null,
  status text not null default 'completed' check (status in ('completed')),
  orders integer not null default 0,
  lines integer not null default 0,
  mirrored integer not null default 0,
  completed_at timestamptz not null default now(),
  unique (window_start, window_end)
);

create index if not exists shopify_sales_sync_windows_completed_idx
  on public.shopify_sales_sync_windows(status, window_start asc);

alter table public.shopify_sales_sync_windows enable row level security;
revoke all on table public.shopify_sales_sync_windows from anon, authenticated;
