create table if not exists public.v1_door_bom_sources (
  id bigint generated by default as identity primary key,
  finished_sku text not null unique,
  finished_name text not null,
  components jsonb not null,
  v2_finished_product_id bigint references public.products(id) on delete set null,
  match_status text not null check (match_status in ('matched', 'unmatched')),
  missing_skus text[] not null default '{}',
  imported_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists v1_door_bom_sources_status_sku_idx
  on public.v1_door_bom_sources(match_status, finished_sku);

create index if not exists v1_door_bom_sources_v2_finished_product_id_idx
  on public.v1_door_bom_sources(v2_finished_product_id);

alter table public.v1_door_bom_sources enable row level security;
revoke all on table public.v1_door_bom_sources from anon, authenticated;
