(()=>{
  const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  function render(){
    app.innerHTML=`<section class="forecast-page">
      <section class="forecast-hero"><div><div class="eyebrow">DEMAND & REPLENISHMENT</div><h2>Forecasting</h2><p>Turn fulfillment history, current inventory, open purchase orders, and transfers into warehouse-level stocking recommendations.</p></div><span>Model setup</span></section>
      <section class="forecast-summary"><article><small>Planning Window</small><strong>30 Days</strong><span>Primary replenishment horizon</span></article><article><small>Demand Basis</small><strong>Fulfillment</strong><span>Where inventory is actually consumed</span></article><article><small>Distribution Hub</small><strong>Windham</strong><span>Overstock and internal replenishment</span></article><article><small>Output</small><strong>Recommendations</strong><span>No automatic inventory changes</span></article></section>
      <section class="forecast-panel"><div class="eyebrow">MODEL ROADMAP</div><h3>Forecasting workspace</h3><div class="forecast-grid">
        <article><b>1</b><div><strong>Demand History</strong><p>Normalize completed Shopify fulfillments by SKU, warehouse, and day.</p></div><em>Next</em></article>
        <article><b>2</b><div><strong>Warehouse Routing</strong><p>NY deliveries count at Bayview; CT activity counts at Annex; pickups remain with their selling branch.</p></div><em>Planned</em></article>
        <article><b>3</b><div><strong>Lead Times & Supply</strong><p>Include current inventory, incoming purchase orders, transfers, vendor lead times, and safety stock.</p></div><em>Planned</em></article>
        <article><b>4</b><div><strong>Suggested Actions</strong><p>Recommend par changes, internal transfers, and purchase quantities with a confidence score.</p></div><em>Planned</em></article>
      </div></section>
      <section class="forecast-panel"><div class="eyebrow">SOURCE OF TRUTH</div><h3>Initial location rules</h3><div class="forecast-rules"><div><strong>336 Bayview</strong><span>NY local-delivery fulfillment</span></div><div><strong>Bohemia</strong><span>Bohemia pickup and store demand</span></div><div><strong>Riverhead</strong><span>Riverhead pickup and store demand</span></div><div><strong>Annex</strong><span>CT sales, pickups, and deliveries</span></div><div><strong>730 Windham</strong><span>Distribution and overstock; manual starting pars</span></div></div></section>
    </section>`;
  }
  function show(){state.route='forecasting';pageTitle.textContent='Forecasting';render()}
  window.bmOpenForecastingDashboard=show;
  const style=document.createElement('style');style.textContent='.forecast-page{display:grid;gap:16px}.forecast-hero,.forecast-panel{background:#fff;border:1px solid var(--line);border-radius:16px;padding:20px}.forecast-hero{display:flex;justify-content:space-between;gap:20px;background:linear-gradient(135deg,#eff6ff,#fff)}.forecast-hero h2{margin:5px 0}.forecast-hero p{margin:0;max-width:760px;color:var(--muted)}.forecast-hero>span{align-self:start;padding:7px 10px;border-radius:999px;background:#dbeafe;color:#1d4ed8;font-weight:850}.forecast-summary{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.forecast-summary article{display:grid;gap:5px;padding:16px;border:1px solid var(--line);border-radius:13px;background:#fff}.forecast-summary small,.forecast-summary span{color:var(--muted)}.forecast-summary strong{font-size:22px}.forecast-panel h3{margin:4px 0 14px}.forecast-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.forecast-grid article{display:grid;grid-template-columns:auto 1fr auto;gap:12px;align-items:start;padding:14px;border:1px solid var(--line);border-radius:12px}.forecast-grid b{display:grid;place-items:center;width:30px;height:30px;border-radius:9px;background:#0c2f49;color:#fff}.forecast-grid p{margin:5px 0;color:var(--muted)}.forecast-grid em{font-style:normal;padding:5px 8px;border-radius:999px;background:#f1f5f9;color:#475569;font-size:11px;font-weight:850}.forecast-rules{display:grid;grid-template-columns:repeat(5,1fr);gap:9px}.forecast-rules div{display:grid;gap:5px;padding:13px;border-radius:11px;background:#f8fafc;border:1px solid var(--line)}.forecast-rules span{color:var(--muted);font-size:12px}@media(max-width:1000px){.forecast-summary,.forecast-rules{grid-template-columns:repeat(2,1fr)}}@media(max-width:700px){.forecast-hero{display:grid}.forecast-summary,.forecast-grid,.forecast-rules{grid-template-columns:1fr}}';document.head.appendChild(style);
})();
