(()=>{'use strict';
const $=id=>document.getElementById(id),view=$('forecastingView');if(!view||view.dataset.forecastInitialized==='true')return;view.dataset.forecastInitialized='true';
const fmt=(v,d=0)=>new Intl.NumberFormat('en-US',{maximumFractionDigits:d}).format(Number(v||0));
let state={data:null,page:1,controller:null,searchTimer:null,requestSeq:0};
const status=(message,error=false,id='')=>{const el=$('forecastDataStatus');el.replaceChildren();const text=document.createElement('span');text.textContent=message+(id?' Request '+id+'.':'');el.append(text);if(error){const retry=document.createElement('button');retry.type='button';retry.textContent='Retry';retry.addEventListener('click',()=>load(1));el.append(' ',retry)}};
const add=(tr,value,cls='')=>{const cell=document.createElement('td');cell.textContent=value;if(cls)cell.className=cls;tr.append(cell)};
function params(page=state.page){return new URLSearchParams({historyDays:$('forecastHistory').value,growth:$('forecastGrowth').value,coverageDays:$('forecastCoverage').value,safetyStockDays:$('forecastSafety').value,category:$('forecastCategory').value,search:$('forecastSearch').value.trim(),sort:$('forecastSort')?.value||'suggested_desc',page:String(page),pageSize:'50'})}
function render(data){state.data=data;const s=data.summary||{},st=data.status||{},p=data.pagination||{};
$('forecastGross').textContent=fmt(s.grossUnits);$('forecastTarget').textContent=fmt(s.target);$('forecastUsable').textContent=fmt(s.usable730);$('forecastInbound').textContent=fmt(s.validInbound);$('forecastSuggested').textContent=st.recommendationsEnabled?fmt(s.suggestedRequirement):'Disabled';
status(String(st.confidence||'').toUpperCase()+' · '+st.completedHistoryDays+' synchronized days · '+st.manualExclusions+' manually excluded non-stock SKUs · Showing '+(data.items||[]).length+' of '+(p.total||0)+'. '+st.manualExclusionLabel+' '+st.returnsNotice);
const body=$('forecastRows'),frag=document.createDocumentFragment();body.replaceChildren();
(data.items||[]).forEach(item=>{const row=document.createElement('tr');row.className='forecast-main';add(row,item.sku);add(row,item.product+(item.bulkOrderInfluenced?' · Bulk-order influenced':''));add(row,fmt(item.grossUnitsSold));add(row,item.completedHistoryDays);add(row,fmt(item.averageDailyDemand,2));add(row,fmt(item.growthAdjustedDailyDemand,2));add(row,fmt(item.target730));add(row,fmt(item.usable730));add(row,fmt(item.validInboundPoQuantity));add(row,fmt(item.projectedShortageSurplus),Number(item.projectedShortageSurplus)<0?'surplus':'shortage');add(row,item.suggestedRequirement==null?'Disabled':fmt(item.suggestedRequirement));add(row,item.confidence);frag.append(row);
 row.addEventListener('click',async()=>{if(row.nextElementSibling?.classList.contains('forecast-detail')){row.nextElementSibling.remove();return}const detail=document.createElement('tr');detail.className='forecast-detail';const cell=document.createElement('td');cell.colSpan=12;cell.textContent='Loading bulk-order details…';detail.append(cell);row.after(detail);try{const r=await fetch('/api/forecast?detailSku='+encodeURIComponent(item.sku)+'&'+params(1),{credentials:'same-origin',cache:'no-store',signal:AbortSignal.timeout(15000)}),d=await r.json();if(!r.ok)throw Error(d.error||'Detail failed');const b=d.item.bulk||{};cell.textContent='Orders '+fmt(b.orders)+' · Avg/order '+fmt(b.averageUnitsPerOrder,2)+' · Largest '+fmt(b.largestOrder)+' · Top five '+fmt(b.fiveLargestOrderUnits)+' ('+fmt(Number(b.topFiveShare||0)*100,1)+'%) · Median '+fmt(b.medianLineQuantity,2)+' · Unusually large lines '+fmt(b.unusuallyLargeLines)+' / '+fmt(b.unitsFromUnusuallyLargeLines)+' units · Supplier ordering multiple not configured.'}catch(e){cell.textContent=e.message}});
});body.append(frag);if(!(data.items||[]).length)body.innerHTML='<tr><td colspan="12">No eligible SKUs match these filters.</td></tr>';
let nav=$('forecastPager');if(!nav){nav=document.createElement('div');nav.id='forecastPager';nav.className='forecast-pager';$('forecastingView').append(nav)}nav.replaceChildren();const prev=document.createElement('button'),label=document.createElement('span'),next=document.createElement('button');prev.textContent='Previous';next.textContent='Next';label.textContent='Page '+(p.page||1)+' of '+(p.totalPages||1);prev.disabled=(p.page||1)<=1;next.disabled=(p.page||1)>=(p.totalPages||1);prev.onclick=()=>load((p.page||1)-1);next.onclick=()=>load((p.page||1)+1);nav.append(prev,label,next);
const sel=$('forecastCategory');if(sel.options.length===1)(data.categories||[]).forEach(c=>sel.add(new Option(c,c)))}
async function load(page=1){const seq=++state.requestSeq;state.controller?.abort();const controller=new AbortController();state.controller=controller;state.page=page;$('forecastRecalculate').disabled=true;status('Loading Forecasting from the local cache…');const timeout=setTimeout(()=>controller.abort('timeout'),15000);
try{const response=await fetch('/api/forecast?'+params(page),{credentials:'same-origin',cache:'no-store',signal:controller.signal}),data=await response.json();if(seq!==state.requestSeq)return;if(!response.ok)throw Object.assign(Error(data.error||'Forecast failed'),{requestId:data.requestId});render(data)}
catch(error){if(seq!==state.requestSeq)return;status(error.name==='AbortError'?'Forecast request timed out.':error.message,true,error.requestId||'')}
finally{clearTimeout(timeout);if(seq===state.requestSeq){$('forecastRecalculate').disabled=false;state.controller=null}}}
function show(){const clickStart=performance.now();document.querySelectorAll('main > section,#atGlanceView').forEach(el=>{if(el!==view)el.hidden=true});view.hidden=false;status('Forecasting is ready to load…');requestAnimationFrame(()=>{console.info('[forecast shell]',{viewSwitchMs:performance.now()-clickStart});setTimeout(()=>load(1),0)})}
function csv(){if(!state.data)return;const h=['SKU','Product','Gross units sold','Completed history days','Average daily demand','Growth-adjusted daily demand','Target at 730','Usable inventory at 730','Valid inbound PO quantity','Projected shortage or surplus','Suggested requirement','Confidence'],rows=state.data.items.map(x=>[x.sku,x.product,x.grossUnitsSold,x.completedHistoryDays,x.averageDailyDemand,x.growthAdjustedDailyDemand,x.target730,x.usable730,x.validInboundPoQuantity,x.projectedShortageSurplus,x.suggestedRequirement,x.confidence]),out=[h,...rows].map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([out],{type:'text/csv'}));a.download='forecast-page-'+state.page+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),0)}
$('forecastNav')?.addEventListener('click',show,{passive:true});$('forecastRecalculate').addEventListener('click',()=>load(1));$('forecastExport').addEventListener('click',csv);$('forecastSearch').addEventListener('input',()=>{clearTimeout(state.searchTimer);state.searchTimer=setTimeout(()=>load(1),300)});$('forecastCategory').addEventListener('change',()=>load(1));$('forecastSort')?.addEventListener('change',()=>load(1));
document.querySelectorAll('.nav-item').forEach(el=>{if(el.id!=='forecastNav')el.addEventListener('click',()=>state.controller?.abort('navigation'),{passive:true})});
})();