(() => {
const $=id=>document.getElementById(id),view=$('forecastingView'); if(!view)return;
const n=(v,d=0)=>new Intl.NumberFormat('en-US',{maximumFractionDigits:d}).format(Number(v||0));
let data=null;
function td(tr,v,cls=''){const x=document.createElement('td');x.textContent=v;if(cls)x.className=cls;tr.append(x)}
function render(d){data=d; const s=d.summary||{},st=d.status||{};
$('forecastDataStatus').innerHTML='<strong>'+String(st.confidence||'').toUpperCase()+'</strong> · '+st.completedHistoryDays+' synchronized days · '+st.manualExclusions+' manually excluded non-stock SKUs'+(st.staleInventoryRows?' · '+st.staleInventoryRows+' stale inventory rows':'')+'<br>'+st.manualExclusionLabel+' '+st.returnsNotice;
$('forecastGross').textContent=n(s.grossUnits);$('forecastTarget').textContent=n(s.target);$('forecastUsable').textContent=n(s.usable730);$('forecastInbound').textContent=n(s.validInbound);$('forecastSuggested').textContent=st.recommendationsEnabled?n(s.suggestedRequirement):'Disabled';
const body=$('forecastRows');body.replaceChildren();
let items=[...(d.items||[])]; const term=$('forecastSearch').value.trim().toUpperCase();if(term)items=items.filter(x=>(x.sku+' '+x.product).toUpperCase().includes(term));
items.sort((a,b)=>Number(b.suggestedRequirement||0)-Number(a.suggestedRequirement||0));
items.forEach(x=>{const tr=document.createElement('tr');tr.className='forecast-main';td(tr,x.sku);td(tr,x.product+(x.bulkOrderInfluenced?'  Bulk-order influenced':''));td(tr,n(x.grossUnitsSold));td(tr,x.completedHistoryDays);td(tr,n(x.averageDailyDemand,2));td(tr,n(x.growthAdjustedDailyDemand,2));td(tr,n(x.target730));td(tr,n(x.usable730));td(tr,n(x.validInboundPoQuantity));td(tr,n(x.projectedShortageSurplus),Number(x.projectedShortageSurplus)<0?'surplus':'shortage');td(tr,x.suggestedRequirement==null?'Disabled':n(x.suggestedRequirement));td(tr,x.confidence);body.append(tr);
const detail=document.createElement('tr');detail.className='forecast-detail';detail.hidden=true;const c=document.createElement('td');c.colSpan=12;const b=x.bulk||{};c.textContent='Orders '+n(b.orders)+' · Avg/order '+n(b.averageUnitsPerOrder,2)+' · Largest '+n(b.largestOrder)+' · Top five '+n(b.fiveLargestOrderUnits)+' ('+n(Number(b.topFiveShare||0)*100,1)+'%) · Median '+n(b.medianLineQuantity,2)+' · Unusually large lines '+n(b.unusuallyLargeLines)+' / '+n(b.unitsFromUnusuallyLargeLines)+' units · Pending Shopify confirmation '+n(x.pendingShopifyConfirmation)+' · Supplier ordering multiple not configured.';detail.append(c);body.append(detail);tr.addEventListener('click',()=>detail.hidden=!detail.hidden)});
if(!items.length)body.innerHTML='<tr><td colspan="12">No eligible SKUs match these filters.</td></tr>';
}
async function load(){try{$('forecastRecalculate').disabled=true;$('forecastDataStatus').textContent='Calculating from the local forecasting cache…';const p=new URLSearchParams({historyDays:$('forecastHistory').value,growth:$('forecastGrowth').value,coverageDays:$('forecastCoverage').value,safetyStockDays:$('forecastSafety').value,category:$('forecastCategory').value});const r=await fetch('/api/forecast?'+p,{credentials:'same-origin',cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error||'Forecast failed');render(d);const sel=$('forecastCategory');if(sel.options.length===1)(d.categories||[]).forEach(c=>sel.add(new Option(c,c)));}catch(e){$('forecastDataStatus').textContent=e.message}else{$('forecastRecalculate').disabled=false}}
function csv(){if(!data)return;const h=['SKU','Product','Gross units sold','Completed history days','Average daily demand','Growth-adjusted daily demand','Target at 730','Usable inventory at 730','Valid inbound PO quantity','Projected shortage or surplus','Suggested requirement','Confidence'];const rows=(data.items||[]).map(x=>[x.sku,x.product,x.grossUnitsSold,x.completedHistoryDays,x.averageDailyDemand,x.growthAdjustedDailyDemand,x.target730,x.usable730,x.validInboundPoQuantity,x.projectedShortageSurplus,x.suggestedRequirement,x.confidence]);const out=[h,...rows].map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([out],{type:'text/csv'}));a.download='forecast.csv';a.click();URL.revokeObjectURL(a.href)}
function show(){document.querySelectorAll('main > section,#atGlanceView').forEach(x=>{if(x!==view)x.hidden=true});view.hidden=false;load()}
$('forecastNav')?.addEventListener('click',show);$('forecastRecalculate').addEventListener('click',load);$('forecastExport').addEventListener('click',csv);$('forecastSearch').addEventListener('input',()=>data&&render(data));
})();