(() => {
  const $=id=>document.getElementById(id);let initialized=false;
  const label={opening_balance:'Opening balance',purchase_receipt:'PO receipt',transfer_ship:'Transfer shipped',transfer_receive:'Transfer received',production_consume:'Production used',production_complete:'Production completed',cycle_count:'Cycle count',adjustment:'Adjustment',damage:'Damaged stock',return:'Return',allocation:'Allocated',allocation_release:'Allocation released'};
  const set=(text,error=false)=>{$('ledgerStatus').textContent=text;$('ledgerStatus').classList.toggle('error',error);};
  function cell(row,value,kind){const td=document.createElement('td');td.textContent=value;if(kind)td.className=kind;row.append(td);}
  function render(rows){const body=$('ledgerRows');body.replaceChildren();if(!rows.length){body.innerHTML='<tr><td colspan="11">No movements match these filters.</td></tr>';return;}rows.forEach(row=>{const tr=document.createElement('tr'),delta=Number(row.quantity_delta);cell(tr,new Date(row.created_at).toLocaleString());cell(tr,row.locations?.name||'—');cell(tr,row.products?.sku||'—','sku');cell(tr,row.products?.name||'—');cell(tr,label[row.movement_type]||row.movement_type);cell(tr,delta>0?'+'+delta:delta,delta<0?'error':'');cell(tr,String(row.quantity_before)+' → '+String(row.quantity_after));cell(tr,row.unit_cost==null?'—':'$'+Number(row.unit_cost).toFixed(2));cell(tr,row.performed_by_name||'—');cell(tr,row.reason||'—');cell(tr,row.reference_id||row.metadata?.note||'—');body.append(tr);});}
  function options(select,items,placeholder){const current=select.value;select.replaceChildren();const first=document.createElement('option');first.value='';first.textContent=placeholder;select.append(first);items.forEach(item=>{const opt=document.createElement('option');opt.value=item.id??item;opt.textContent=item.name??item;select.append(opt);});select.value=current;}
  async function load(){set('Loading inventory ledger…');const params=new URLSearchParams({locationId:$('ledgerLocation').value||'all',search:$('ledgerSearch').value,movementType:$('ledgerType').value,employee:$('ledgerEmployee').value,from:$('ledgerFrom').value,to:$('ledgerTo').value});const response=await fetch('/api/inventory-ledger?'+params,{credentials:'same-origin'}),data=await response.json().catch(()=>({}));if(!response.ok)throw Error(data.error||'Could not load ledger.');if(!initialized){options($('ledgerLocation'),data.locations,'All assigned warehouses');initialized=true;}options($('ledgerType'),data.types,'All movement types');options($('ledgerEmployee'),data.employees,'All employees');render(data.movements||[]);set((data.movements||[]).length+' movements shown.');}
  function show(){['overviewView','inventoryView','snapshotView','transferView','purchaseOrdersView','replenishmentView','productSyncView','forecastView','parLevelsView','skuFixView','productionView','bomManagementView'].forEach(id=>{const x=$(id);if(x)x.hidden=id!=='inventoryLedgerView';});['overviewNav','inventoryNav','transfersNav','purchaseOrdersNav','replenishmentNav','forecastNav','productSyncNav','snapshotNav','parLevelsNav','skuFixNav','productionNav','bomManagementNav'].forEach(id=>$(id)?.classList.remove('active'));$('inventoryLedgerNav').classList.add('active');if(!initialized)load().catch(e=>set(e.message,true));}
  $('inventoryLedgerNav').onclick=show;$('ledgerRefresh').onclick=()=>load().catch(e=>set(e.message,true));['ledgerLocation','ledgerType','ledgerEmployee','ledgerFrom','ledgerTo'].forEach(id=>$(id).onchange=()=>load().catch(e=>set(e.message,true)));$('ledgerSearch').onkeydown=e=>{if(e.key==='Enter')load().catch(err=>set(err.message,true));};
})();