function createMfgDrawerLifecycle({drawer,body,document}){
 let listeners=null,opener=null;
 function cleanup({restoreFocus=true}={}){const priorOpener=opener;listeners?.abort();listeners=null;if(drawer.open)drawer.close();body.innerHTML='';document.body.classList.remove('mfg-drawer-open');opener=null;if(restoreFocus&&priorOpener?.isConnected&&typeof priorOpener.focus==='function'){try{priorOpener.focus({preventScroll:true})}catch{priorOpener.focus()}}}
 function bindSession(){if(listeners)return;listeners=new AbortController();const options={signal:listeners.signal};drawer.addEventListener('click',event=>{if(event.target===drawer||event.target?.closest?.('[data-close]'))cleanup()},options);drawer.addEventListener('cancel',event=>{event.preventDefault();cleanup()},options);drawer.addEventListener('close',()=>cleanup(),options)}
 function open(html){if(!drawer.open)opener=document.activeElement;body.innerHTML=html;bindSession();if(!drawer.open)drawer.showModal();document.body.classList.add('mfg-drawer-open')}
 return {open,close:cleanup};
}
function createMfgProductionPacketPrinter({window}){
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 return order=>{const popup=window.open('about:blank','_blank','width=900,height=760');if(!popup)return false;const rows=(order.lines||[]).map(line=>`<tr><td><b>${esc(line.sku)}</b><br>${esc(line.product)}</td><td>${esc(line.planned)}</td><td>${esc(line.good)}</td><td>${esc(line.remaining)}</td></tr>`).join('');popup.document.write(`<!doctype html><title>${esc(order.number)} production packet</title><style>body{font:15px Arial;color:#172d45;margin:36px}h1{margin:0 0 6px}.meta{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:24px 0}.meta div,.notice{padding:12px;border:1px solid #ccd8e5;border-radius:8px}.meta small{display:block;color:#687b90}.notice{background:#fff6cf;color:#735800;font-weight:800}table{width:100%;border-collapse:collapse;margin-top:20px}th,td{padding:11px;border:1px solid #ccd8e5;text-align:left}th{background:#edf3f8}@media print{body{margin:16px}}</style><h1>${esc(order.number)}</h1><p>Production packet · printed ${esc(new Date().toLocaleString())}</p><div class="meta"><div><small>Destination</small><b>${esc(order.destination)}</b></div><div><small>Machine</small><b>${esc(order.machine)}</b></div><div><small>Status</small><b>${esc(order.lifecycleStatus||order.status)}</b></div></div><div class="notice">BOM MATERIAL REFERENCE — NOT A PICK TICKET</div><table><thead><tr><th>Finished product</th><th>Planned</th><th>Good</th><th>Remaining</th></tr></thead><tbody>${rows}</tbody></table>`);popup.document.close();popup.focus();setTimeout(()=>popup.print(),150);return true}
}
function bindMfgNewBomButton({document,selectedBomVersionId,openEditor,closeDrawer,onError}){
 const button=document.getElementById('mfgDrawerBody')?.querySelector('[data-new-bom]');
 if(!button)return false;
 button.addEventListener('click',async()=>{try{if(!selectedBomVersionId||typeof openEditor!=='function')throw Error('BOM editor is unavailable. Refresh and try again.');closeDrawer();await openEditor(selectedBomVersionId)}catch(error){onError(error)}});
 return true;
}
if(typeof module==='object'&&module.exports){module.exports=createMfgDrawerLifecycle;module.exports.createMfgProductionPacketPrinter=createMfgProductionPacketPrinter;module.exports.bindMfgNewBomButton=bindMfgNewBomButton}
(()=>{
 if(typeof document==='undefined')return;
 const trace=(event,detail={})=>{const record={time:new Date().toISOString(),event,...detail};window.__bmManufacturingTrace=window.__bmManufacturingTrace||[];window.__bmManufacturingTrace.push(record);if(window.__bmManufacturingTrace.length>100)window.__bmManufacturingTrace.shift();console.info('[bm-mfg]',JSON.stringify(record));return record};
 window.BMManufacturingTrace=trace;
 let enterImpl=null,readyResolve;
 const ready=new Promise(resolve=>{readyResolve=resolve});
 window.enterManufacturing=async()=>{if(!enterImpl){trace('module_waiting');await ready}return enterImpl()};
 function initialize(){
 if(window.__bmManufacturingPhase3Initialized)return;
 const $=id=>document.getElementById(id),view=$('productionView');if(!view)return;
 window.__bmManufacturingPhase3Initialized=true;
 const state={tab:'planner',data:null,panels:new Map(),selected:new Map(),controllers:new Map(),sequence:0,requestGeneration:0,loaded:false,entryComplete:false,drawer:null,params:{planner:{page:1,destination:'',search:''},orders:{page:1,search:''},boms:{page:1,search:''},board:{page:1}}};
 trace('module_ready');
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const num=v=>Number(v||0).toLocaleString('en-US',{maximumFractionDigits:2});
 const badge=s=>'<span class="mfg-badge '+String(s).toLowerCase().replaceAll(' ','-')+'">'+esc(s)+'</span>';
 const idempotency=prefix=>prefix+':'+crypto.randomUUID();
 const printPacket=createMfgProductionPacketPrinter({window});
 function shell(){view.innerHTML=`<header class="mfg-head"><div><div class="eyebrow">730 WINDHAM MANUFACTURING</div><h1>Stock-door production</h1><p>Plan, run and review Nighthawk and Terminator work orders.</p></div><span id="mfgLive" class="mfg-live">Loading controls…</span></header><div id="mfgControlState" class="mfg-control-state">Checking Manufacturing controls…</div><nav class="mfg-tabs" aria-label="Manufacturing sections">${[['planner','Production Planner'],['board','Production Board'],['orders','Work Orders'],['boms','BOM & Costing']].map(([k,l])=>`<button class="mfg-tab" data-tab="${k}">${l}</button>`).join('')}</nav><div id="mfgMessage" class="mfg-message" aria-live="polite"></div><main id="mfgPanel" class="mfg-panel">${['planner','board','orders','boms'].map(k=>`<section data-mfg-panel="${k}" ${k==='planner'?'':'hidden'}></section>`).join('')}</main><dialog id="mfgDrawer" class="mfg-drawer"><div id="mfgDrawerBody" class="mfg-drawer-body"></div></dialog>`;state.drawer=createMfgDrawerLifecycle({drawer:$('mfgDrawer'),body:$('mfgDrawerBody'),document});$('mfgDrawerBody').addEventListener('click',handleDrawerAction);view.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{if(!state.entryComplete){trace('tab_ignored_before_entry',{tab:b.dataset.tab});return}load(b.dataset.tab)});}
 const panel=tab=>view.querySelector(`[data-mfg-panel="${tab}"]`);
 function loading(tab){const el=panel(tab),label={planner:'Production Planner',board:'Production Board',orders:'Work Orders',boms:'BOM & Costing'}[tab]||'Manufacturing';el.dataset.loading='true';if(!state.panels.has(tab))el.innerHTML=`<div class="mfg-card" role="status"><strong>Loading ${label}…</strong>${Array.from({length:6},()=>'<div class="mfg-skeleton"></div>').join('')}</div>`;else el.insertAdjacentHTML('afterbegin',`<div class="mfg-panel-progress" role="status">Refreshing ${label}…</div>`)}
 async function api(tab,params={},scope=tab,generation=++state.requestGeneration){const prior=state.controllers.get(scope);if(prior){trace('request_abort',{tab,scope,generation:prior.generation,reason:'superseded'});prior.controller.abort('superseded')}const controller=new AbortController(),timeout=setTimeout(()=>{trace('request_abort',{tab,scope,generation,reason:'timeout'});controller.abort('timeout')},9000);state.controllers.set(scope,{controller,generation});trace('request_start',{tab,scope,generation});try{const q=new URLSearchParams({view:tab,pageSize:'25',...params});const r=await fetch('/api/manufacturing-ui?'+q,{credentials:'same-origin',cache:'no-store',signal:controller.signal,headers:{'x-request-id':crypto.randomUUID()}});const d=await r.json().catch(()=>({}));trace('request_finish',{tab,scope,generation,status:r.status});if(!r.ok)throw Error(d.error||'Manufacturing view could not load');return d}catch(error){if(error.name==='AbortError')trace('request_aborted',{tab,scope,generation,reason:String(controller.signal.reason||'abort')});throw error}finally{clearTimeout(timeout);if(state.controllers.get(scope)?.controller===controller)state.controllers.delete(scope)}}
 async function command(body,button){if(button?.disabled)return;button&&(button.disabled=true);try{const r=await fetch('/api/manufacturing-v2',{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json'},body:JSON.stringify({...body,idempotencyKey:body.idempotencyKey||idempotency('mfg-ui')})});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Manufacturing action failed');await load(state.tab);return d;}catch(e){$('mfgMessage').textContent=e.message;$('mfgMessage').className='mfg-message mfg-error';await load(state.tab);throw e;}finally{button&&(button.disabled=false)}}
 function renderControlState(){const c=state.data?.controlState||{};const el=$('mfgControlState');if(state.data?.testEnvironment){el.textContent='TEST ENVIRONMENT — NO PRODUCTION DATA';el.className='mfg-fixture-banner';$('mfgLive').textContent='Phase 3 preview';return}el.textContent=c.statusLabel||'Manufacturing controls loaded.';el.className='mfg-control-state '+(c.pilotPaused?'pilot-paused':c.gateEnabled?'pilot-enabled':'');$('mfgLive').textContent=c.pilotPaused?'Restricted pilot paused':c.gateEnabled?'Restricted pilot active':'Planning access';}
 async function load(tab=state.tab,refresh=false){if(tab!==state.tab)state.drawer?.close({restoreFocus:false});state.tab=tab;const seq=++state.sequence,generation=++state.requestGeneration;view.querySelectorAll('.mfg-tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));view.querySelectorAll('[data-mfg-panel]').forEach(p=>p.hidden=p.dataset.mfgPanel!==tab);for(const [key,request] of state.controllers)if(key!=='detail'&&key!==tab){trace('request_abort',{tab:key,scope:key,generation:request.generation,reason:'panel_change'});request.controller.abort('panel_change');state.controllers.delete(key)}if(state.panels.has(tab)&&!refresh){state.data=state.panels.get(tab);renderControlState();trace('render_start',{tab,generation,cached:true});render(tab);trace('render_finish',{tab,generation,cached:true});return}loading(tab);try{const data=await api(tab,state.params[tab]||{},tab,generation);if(seq!==state.sequence||tab!==state.tab){trace('response_stale',{tab,generation,sequence:seq,currentSequence:state.sequence});return}state.panels.set(tab,data);state.data=data;renderControlState();trace('render_start',{tab,generation,cached:false});render(tab);trace('render_finish',{tab,generation,cached:false});$('mfgMessage').textContent=''}catch(e){if(seq!==state.sequence)return;const el=panel(tab);el.querySelector('.mfg-panel-progress')?.remove();if(e.name==='AbortError'&&state.controllers.has(tab))return;if(e.name==='AbortError')e=new Error('This panel took too long to load.');trace('render_error',{tab,generation,message:e.message});el.innerHTML=`<div class="mfg-card mfg-empty"><h2>Could not load this panel</h2><p>${esc(e.message)}</p><button class="mfg-btn" data-retry="${tab}">Retry</button></div>`;el.querySelector('[data-retry]')?.addEventListener('click',()=>load(tab,true))}}
 const kpis=items=>'<div class="mfg-kpis">'+items.map(x=>`<article class="mfg-kpi"><span>${esc(x.label)}</span><strong>${num(x.value)}</strong></article>`).join('')+'</div>';
 const pagination=d=>{const start=d.total?(d.page-1)*d.pageSize+1:0,end=Math.min(d.total,d.page*d.pageSize),pages=Math.max(1,Math.ceil(d.total/d.pageSize));return `<div class="mfg-pagination"><span>Showing ${start}–${end} of ${d.total}</span><div><button class="mfg-btn secondary" data-page="${d.page-1}" ${d.page<=1?'disabled':''}>Previous</button> <button class="mfg-btn secondary" data-page="${d.page+1}" ${d.page>=pages?'disabled':''}>Next</button></div></div>`};
 function tray(){return `<div id="mfgSelectionTray" class="mfg-tray" ${state.selected.size?'':'hidden'}><strong>${state.selected.size} SKUs selected · ${num([...state.selected.values()].reduce((s,x)=>s+x.suggested,0))} doors</strong><button id="mfgReviewBatch" class="mfg-btn">Review production batch</button></div>`}
 function planner(){const d=state.data,p=state.params.planner,rows=d.rows||[];return kpis(d.kpis||[])+`<section class="mfg-card"><div class="mfg-card-head"><div><h2>Store replenishment needs</h2><small>${num(d.total)} finished products</small></div></div><div class="mfg-filters"><select id="mfgDestination" class="mfg-control"><option value="">All destinations</option>${(d.destinations||[]).map(x=>`<option ${p.destination===x?'selected':''}>${esc(x)}</option>`)}</select><input id="mfgSkuSearch" class="mfg-control" type="search" value="${esc(p.search)}" placeholder="Search finished SKU or description"><select class="mfg-control"><option>Largest suggested build</option><option>Destination</option><option>SKU</option></select></div></section><section class="mfg-card"><div class="mfg-table-wrap mobile-cards"><table class="mfg-table"><thead><tr><th>Select</th><th>Destination</th><th>SKU / Product</th><th class="num">On hand</th><th class="num">Allocated</th><th class="num">Available</th><th class="num">Par</th><th class="num">Incoming</th><th class="num">In production</th><th class="num">Suggested</th><th>BOM</th></tr></thead><tbody>${rows.map(r=>`<tr><td><input class="mfg-select" type="checkbox" data-id="${r.id}" ${state.selected.has(r.id)?'checked':''}></td><td>${esc(r.destination)}</td><td><div class="mfg-sku">${esc(r.sku)}</div>${esc(r.product)}</td><td class="num ${r.onHand<0?'mfg-negative':''}">${num(r.onHand)}</td><td class="num">${num(r.allocated)}</td><td class="num ${r.available<0?'mfg-negative':''}">${num(r.available)}</td><td class="num">${num(r.par)}</td><td class="num">${num(r.incoming)}</td><td class="num">${num(r.inProduction)}</td><td class="num mfg-strong">${num(r.suggested)}</td><td>${badge(r.bomStatus)}</td></tr>`).join('')||'<tr><td colspan="11" class="mfg-empty">No finished products match these filters.</td></tr>'}</tbody></table></div>${pagination(d)}${tray()}</section>`;}
 function board(){const d=state.data;return `<div class="mfg-board">${['NIGHTHAWK','TERMINATOR'].map(machine=>`<section class="mfg-machine"><div class="mfg-machine-title"><h2>${machine==='NIGHTHAWK'?'4000A · Nighthawk':'4000B · Terminator'}</h2><span>${(d[machine]||[]).length} jobs</span></div>${(d[machine]||[]).map(job=>`<article class="mfg-job"><div class="mfg-job-top"><span class="mfg-sku">${esc(job.number)}${job.pilotOwned?'<span class="mfg-pilot-label">Restricted pilot</span>':''}</span>${badge(job.status)}</div><h3>${esc(job.destination)}</h3><p>${job.skus} finished SKUs · ${esc(job.priority)} priority · Due ${esc(job.requested)}</p><div class="mfg-job-stats"><span>Planned<strong>${num(job.planned)}</strong></span><span>Good<strong>${num(job.good)}</strong></span><span>Remaining<strong>${num(job.remaining)}</strong></span></div><div class="mfg-job-actions"><button class="mfg-btn" data-progress="${job.id}" ${job.actionDisabled?'disabled':''}>${esc(job.action)}</button><button class="mfg-btn secondary" data-detail="${job.id}">View / Print</button></div></article>`).join('')||'<div class="mfg-empty">No work assigned.</div>'}</section>`).join('')}</div>`;}
 function orders(){const d=state.data;return `<section class="mfg-card"><div class="mfg-card-head"><h2>Work Orders</h2><span>${num(d.total)} records</span></div><div class="mfg-table-wrap mobile-cards"><table class="mfg-table"><thead><tr><th>Work order</th><th>Created</th><th>Destination</th><th>Machine</th><th>Status</th><th class="num">Planned</th><th class="num">Good</th><th class="num">Remaining</th><th>Transfer</th><th>Requested</th></tr></thead><tbody>${(d.rows||[]).map(r=>`<tr data-detail="${r.id}" tabindex="0"><td class="mfg-sku">${esc(r.number)}</td><td>${esc(r.created)}</td><td>${esc(r.destination)}</td><td>${esc(r.machine)}</td><td>${badge(r.status)}</td><td class="num">${num(r.planned)}</td><td class="num">${num(r.good)}</td><td class="num">${num(r.remaining)}</td><td>${badge(r.transferStatus)}</td><td>${esc(r.requested)}</td></tr>`).join('')||'<tr><td colspan="10" class="mfg-empty">No work orders found.</td></tr>'}</tbody></table></div>${pagination(d)}</section>`;}
 function boms(){const d=state.data,p=state.params.boms;return `<section class="mfg-card"><div class="mfg-card-head"><div><h2>BOM & Costing</h2><small>Versioned recipes; released jobs retain frozen snapshots.</small></div></div><div class="mfg-filters"><input id="mfgBomSearch" class="mfg-control" value="${esc(p.search)}" placeholder="Search SKU or finished product"></div><div class="mfg-table-wrap mobile-cards"><table class="mfg-table"><thead><tr><th>SKU / Product</th><th>Version</th><th>Status</th><th class="num">Components</th><th>Validation</th><th>Source</th><th>Last updated</th></tr></thead><tbody>${(d.rows||[]).map(r=>`<tr data-bom="${r.id}" tabindex="0"><td><span class="mfg-sku">${esc(r.sku)}</span><br>${esc(r.product)}</td><td>v${r.version}</td><td>${badge(r.status)}</td><td class="num">${r.components}</td><td>${badge(r.validation)}</td><td>${esc(r.source)}</td><td>${esc(r.updated)}</td></tr>`).join('')||'<tr><td colspan="7" class="mfg-empty">No BOM versions match this search.</td></tr>'}</tbody></table></div>${pagination(d)}<div class="mfg-cost-unavailable">Cost unavailable — component cost source not configured</div></section>`;}
 function render(tab=state.tab){const el=panel(tab);el.dataset.loading='false';el.innerHTML=tab==='planner'?planner():tab==='board'?board():tab==='orders'?orders():boms();bind(el,tab)}
 function updateTray(){const old=$('mfgSelectionTray'),next=document.createRange().createContextualFragment(tray()).firstElementChild;old?.replaceWith(next);$('mfgReviewBatch')?.addEventListener('click',batch)}
 function debounce(fn,delay=250){let timer;return event=>{const value=event.target.value;clearTimeout(timer);timer=setTimeout(()=>fn(value),delay)}}
 function bind(el,tab){el.querySelectorAll('.mfg-select').forEach(c=>c.onchange=()=>{const row=state.data.rows.find(x=>String(x.id)===c.dataset.id);c.checked?state.selected.set(row.id,row):state.selected.delete(row.id);updateTray()});$('mfgReviewBatch')?.addEventListener('click',batch);el.querySelectorAll('[data-progress]').forEach(b=>b.onclick=()=>progress(Number(b.dataset.progress)));el.querySelectorAll('[data-detail]').forEach(r=>r.onclick=()=>detail(Number(r.dataset.detail)));el.querySelectorAll('[data-bom]').forEach(r=>r.onclick=()=>bomDetail(Number(r.dataset.bom)));el.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{state.params[tab].page=Number(b.dataset.page);load(tab,true)});if(tab==='planner'){$('mfgDestination').onchange=e=>{state.params.planner.destination=e.target.value;state.params.planner.page=1;load('planner',true)};$('mfgSkuSearch').oninput=debounce(value=>{state.params.planner.search=value;state.params.planner.page=1;load('planner',true)})}if(tab==='boms')$('mfgBomSearch').oninput=debounce(value=>{state.params.boms.search=value;state.params.boms.page=1;load('boms',true)})}
 function batch(){const rows=[...state.selected.values()],dest=[...new Set(rows.map(x=>x.destination))];if(dest.length!==1){$('mfgMessage').textContent='Select products for one destination per work order.';$('mfgMessage').className='mfg-message mfg-error';return}openDrawer(`<div class="mfg-drawer-head"><div><div class="eyebrow">STEP 1 OF 3</div><h2>Review production batch</h2><p>${esc(dest[0])}</p></div><button class="mfg-btn secondary" data-close>Close</button></div><div class="mfg-table-wrap"><table class="mfg-table"><thead><tr><th>Finished SKU</th><th>Product</th><th>Suggested</th><th>Planned</th></tr></thead><tbody>${rows.map(r=>`<tr><td class="mfg-sku">${esc(r.sku)}</td><td>${esc(r.product)}</td><td>${r.suggested}</td><td><input class="mfg-control" value="${r.suggested}" type="number"></td></tr>`).join('')}</tbody></table></div><h3>Production</h3><div class="mfg-detail-grid"><label>Machine<select class="mfg-control"><option>Nighthawk</option><option>Terminator</option></select></label><label>Priority<select class="mfg-control"><option>Normal</option><option>Urgent</option></select></label><label>Requested date<input type="date" class="mfg-control"></label></div><h3>Materials and release</h3><p>Aggregated component readiness will be checked at 730. This is material awareness—not a pick ticket.</p><div class="mfg-cost-unavailable">Signed component availability is preserved. Shortages require an authorized override.</div><div class="mfg-job-actions"><button class="mfg-btn secondary">Save Draft</button><button class="mfg-btn">Release Work Order</button></div>`);}
 function progress(id){const j=[...(state.data.NIGHTHAWK||[]),...(state.data.TERMINATOR||[])].find(x=>x.id===id);openDrawer(`<div class="mfg-drawer-head"><div><div class="eyebrow">${esc(j.number)}</div><h2>Record production progress</h2><p>Finished output only—this is not a raw-material pick ticket.</p></div><button class="mfg-btn secondary" data-close>Close</button></div><div class="mfg-progress-grid"><label>Good units<input class="mfg-control" type="number" min="0" value="0"></label><label>Rework units<input class="mfg-control" type="number" min="0" value="0"></label><label>Rejected pending<input class="mfg-control" type="number" min="0" value="0"></label><label>Finished scrap<input class="mfg-control" type="number" min="0" value="0"></label></div><section class="mfg-card"><h3>Transaction preview</h3><p>Good finished inventory added at 730 · Components consumed · Remaining production updated · Transferable quantity increased by good units only.</p></section><details><summary>Record explicit component scrap</summary><div class="mfg-detail-grid"><input class="mfg-control" placeholder="Component SKU"><input class="mfg-control" type="number" placeholder="Actual quantity"><input class="mfg-control" placeholder="Required reason"></div></details><label>Notes<textarea class="mfg-control" rows="3"></textarea></label><button class="mfg-btn">Confirm progress</button>`);}
 async function detail(id){openDrawer('<div class="mfg-card" role="status">Loading work-order detail…</div>');try{const r=(await api('order-detail',{id},'detail')).row;if(!$('mfgDrawer').open)return;state.drawerOrder=r;$('mfgDrawerBody').innerHTML=`<div class="mfg-drawer-head"><div><div class="eyebrow">WORK ORDER</div><h2>${esc(r.number)}${r.pilotOwned?'<span class="mfg-pilot-label">Restricted pilot</span>':''}</h2>${badge(r.status)}</div><button class="mfg-btn secondary" data-close>Close</button></div><div class="mfg-detail-tabs">${['Overview','Finished Products','Materials','Production Activity','Transfer','Audit'].map((x,i)=>`<button class="mfg-detail-tab ${i?'':'active'}">${x}</button>`).join('')}</div><div class="mfg-detail-grid"><div><small>Destination</small><strong>${esc(r.destination)}</strong></div><div><small>Machine</small><strong>${esc(r.machine)}</strong></div><div><small>Transfer</small><strong>${esc(r.transferStatus)}</strong></div><div><small>Planned</small><strong>${num(r.planned)}</strong></div><div><small>Good</small><strong>${num(r.good)}</strong></div><div><small>Remaining</small><strong>${num(r.remaining)}</strong></div></div><p class="mfg-cost-unavailable">BOM MATERIAL REFERENCE — NOT A PICK TICKET</p><div class="mfg-job-actions"><button class="mfg-btn secondary" data-print>Print production packet</button><button class="mfg-btn secondary" data-transfer-detail ${r.transferId?'':'disabled'}>Open Transfer detail</button></div><p class="mfg-message" data-drawer-feedback aria-live="polite"></p>`;bindDrawer()}catch(e){drawerError(e,()=>detail(id))}}
 function drawerFeedback(message,failed=false){const el=$('mfgDrawerBody')?.querySelector('[data-drawer-feedback]');if(el){el.textContent=message;el.className='mfg-message '+(failed?'mfg-error':'mfg-success')}else{$('mfgMessage').textContent=message;$('mfgMessage').className='mfg-message '+(failed?'mfg-error':'mfg-success')}}
 async function handleDrawerAction(event){const button=event.target.closest?.('[data-print],[data-transfer-detail]');if(!button)return;const r=state.drawerOrder;if(!r)return drawerFeedback('Work-order detail is not ready. Close it and try again.',true);if(button.matches('[data-print]')){if(!printPacket(r))return drawerFeedback('Your browser blocked the print window. Allow pop-ups for BM Warehouse and try again.',true);return drawerFeedback('Production packet opened for printing.')}button.disabled=true;drawerFeedback('Opening transfer '+(r.transferReference||r.transferStatus)+'…');try{if(!r.transferId)throw Error('This work order does not have a linked transfer ID.');if(typeof window.openShopifyTransferDetail!=='function')throw Error('Transfer detail is still loading. Close this drawer and try again.');await window.openShopifyTransferDetail(r.transferId);closeDrawer({restoreFocus:false})}catch(error){button.disabled=false;drawerFeedback(error.message||'Transfer detail could not be opened.',true)}}
 async function bomDetail(id){openDrawer('<div class="mfg-card" role="status">Loading BOM components…</div>');try{const r=(await api('bom-detail',{id},'detail')).row;if(!$('mfgDrawer').open)return;$('mfgDrawerBody').innerHTML=`<div class="mfg-drawer-head"><div><div class="eyebrow">VERSIONED BOM</div><h2>${esc(r.sku)} · ${esc(r.product)}</h2></div><button class="mfg-btn secondary" data-close>Close</button></div><div class="mfg-detail-grid"><div><small>Active version</small><strong>v${r.version}</strong></div><div><small>Source</small><strong>${esc(r.source)}</strong></div></div><div class="mfg-table-wrap"><table class="mfg-table"><thead><tr><th>Component SKU</th><th>Description</th><th>Per finished unit</th><th>UOM</th><th>Status</th></tr></thead><tbody>${r.componentRows.map(c=>`<tr><td class="mfg-sku">${esc(c.sku)}</td><td>${esc(c.name)}</td><td>${c.quantity}</td><td>${esc(c.uom)}</td><td>${badge(c.status)}</td></tr>`).join('')}</tbody></table></div><div class="mfg-cost-unavailable">Cost unavailable — component cost source not configured</div><button class="mfg-btn secondary" data-new-bom>Create new draft version</button>`;bindDrawer();bindMfgNewBomButton({document,selectedBomVersionId:r.id,openEditor:window.openBomManagementVersion,closeDrawer,onError:error=>{$('mfgMessage').textContent=error.message;$('mfgMessage').className='mfg-message mfg-error'}})}catch(e){drawerError(e,()=>bomDetail(id))}}
 function closeDrawer(options){state.drawer?.close(options)}
 function bindDrawer(){}
 function drawerError(error,retry){$('mfgDrawerBody').innerHTML=`<div class="mfg-card mfg-empty"><h2>Could not load detail</h2><p>${esc(error.message)}</p><button class="mfg-btn" data-detail-retry>Retry</button><button class="mfg-btn secondary" data-close>Close</button></div>`;bindDrawer();$('mfgDrawerBody [data-detail-retry]').onclick=retry}
 function openDrawer(html){state.drawer.open(html)}
 enterImpl=async()=>{trace('entry_start');sessionStorage.setItem('bm-active-view','manufacturing');document.querySelectorAll('.page>section').forEach(x=>x.hidden=x!==view);view.hidden=false;document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.id==='productionNav'));if(!state.loaded){shell();state.loaded=true}state.entryComplete=false;await load('planner');state.entryComplete=true;trace('entry_finish',{tab:state.tab})};
 readyResolve();
 }
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initialize,{once:true});else initialize();
})();
