(() => {
  const $ = id => document.getElementById(id);
  const view = $('productionView'); if (!view) return;
  let locations=[], finished=null, components=[], bom=null, timer;
  const msg=(t,err=false)=>{ $('productionStatus').textContent=t; $('productionStatus').classList.toggle('error',err); };
  const escape = s => String(s ?? '');
  async function get(path){ const r=await fetch('/api/production'+path,{credentials:'same-origin'}); const d=await r.json(); if(!r.ok) throw new Error(d.error||'Request failed'); return d; }
  async function post(body){ const r=await fetch('/api/production',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify(body)}); const d=await r.json(); if(!r.ok) throw new Error(d.error||'Request failed'); return d; }
  function option(select, label, value){ const o=document.createElement('option'); o.value=value; o.textContent=label; select.append(o); }
  function renderHistory(rows){ const host=$('productionHistoryRows'); host.replaceChildren(); if(!rows.length){const tr=document.createElement('tr'); tr.innerHTML='<td colspan="4" class="muted">No V2 production runs yet.</td>';host.append(tr);return;} rows.forEach(x=>{const tr=document.createElement('tr');[x.document_number,x.description,x.user_name||'—',new Date(x.created_at).toLocaleString()].forEach(v=>{const td=document.createElement('td');td.textContent=v||'—';tr.append(td)});host.append(tr)}); }
  function renderComponents(){ const host=$('bomComponents'); host.replaceChildren(); if(!components.length){const p=document.createElement('p');p.className='muted';p.textContent='Add the components consumed for one yield.';host.append(p);return;} components.forEach((row,i)=>{const line=document.createElement('div');line.className='inventory-actions';line.style.marginTop='10px'; const lookup=document.createElement('div');lookup.className='product-lookup';const input=document.createElement('input');input.className='inventory-search';input.placeholder='Search component SKU or product';input.value=row.product?row.product.sku+' — '+row.product.name:'';const choices=document.createElement('div');choices.className='product-suggestions';choices.hidden=true;lookup.append(input,choices);const qty=document.createElement('input');qty.className='inventory-search';qty.type='number';qty.min='0.0001';qty.step='0.0001';qty.placeholder='Qty per yield';qty.value=row.quantity||'';const remove=document.createElement('button');remove.className='button secondary';remove.textContent='Remove';remove.type='button'; remove.onclick=()=>{components.splice(i,1);renderComponents();}; input.oninput=()=>{row.product=null;clearTimeout(timer); const term=input.value.trim(); if(term.length<2){choices.hidden=true;return;} timer=setTimeout(async()=>{try{const found=await get('?term='+encodeURIComponent(term));choices.replaceChildren();found.slice(0,8).forEach(p=>{const b=document.createElement('button');b.type='button';b.className='product-suggestion';b.textContent=p.sku+' — '+p.name;b.onclick=()=>{row.product=p;input.value=p.sku+' — '+p.name;choices.hidden=true;};choices.append(b)});choices.hidden=!choices.childElementCount;}catch{choices.hidden=true;}},180);};qty.oninput=()=>row.quantity=qty.value;line.append(lookup,qty,remove);host.append(line);}); }
  function renderBom(){ $('productionBomStatus').textContent=bom ? 'Active BOM: '+(bom.products?.sku||finished?.sku)+' · yield '+bom.yield_quantity : 'No BOM saved for this finished SKU yet.'; const host=$('bomPreview');host.replaceChildren(); if(!bom) return; (bom.product_bom_components||[]).forEach(c=>{const tr=document.createElement('tr');const p=c.products||{};const b=c.balance||{};[p.sku,p.name,c.quantity_per_yield,b.quantity??'—',b.allocated_quantity??'—'].forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.append(td)});host.append(tr);}); }
  async function loadBom(){ if(!finished)return; const id=$('productionLocation').value; const data=await get('?bomForProductId='+finished.id+(id?'&locationId='+id:'')); bom=data.bom; if(bom){$('bomYield').value=bom.yield_quantity;$('bomNotes').value=bom.notes||'';components=(bom.product_bom_components||[]).map(c=>({product:c.products,quantity:c.quantity_per_yield}));renderComponents();} renderBom(); }
  async function open(){ view.hidden=false; document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.id==='productionNav')); const data=await get(''); locations=data.locations||[]; const s=$('productionLocation');s.replaceChildren();option(s,'Choose production location','');locations.filter(x=>x.canManage).forEach(x=>option(s,x.name,x.id));renderHistory(data.history||[]);msg('Choose a finished SKU, configure its BOM, then complete production in one warehouse.'); }
  $('productionNav').addEventListener('click',()=>open().catch(e=>msg(e.message,true)));
  ['overviewNav','inventoryNav','productSyncNav','snapshotNav','transfersNav','receivingNav'].forEach(id=>$(id)?.addEventListener('click',()=>view.hidden=true));
  $('productionLocation').addEventListener('change',()=>loadBom().catch(e=>msg(e.message,true)));
  $('finishedSku').addEventListener('input',ev=>{finished=null;clearTimeout(timer);const term=ev.target.value.trim(),box=$('finishedSuggestions');if(term.length<2){box.hidden=true;return;}timer=setTimeout(async()=>{try{const found=await get('?term='+encodeURIComponent(term));box.replaceChildren();found.slice(0,8).forEach(p=>{const b=document.createElement('button');b.type='button';b.className='product-suggestion';b.textContent=p.sku+' — '+p.name;b.onclick=()=>{finished=p;ev.target.value=p.sku+' — '+p.name;box.hidden=true;loadBom().catch(e=>msg(e.message,true));};box.append(b)});box.hidden=!box.childElementCount;}catch{box.hidden=true;}},180);});
  $('addBomComponent').onclick=()=>{components.push({product:null,quantity:''});renderComponents();};
  $('saveBom').onclick=async()=>{try{if(!finished)throw new Error('Choose the finished product.');const list=components.map(x=>({component_product_id:x.product?.id,quantity_per_yield:Number(x.quantity)}));if(list.some(x=>!x.component_product_id||!(x.quantity_per_yield>0)))throw new Error('Choose every component and enter a quantity.');await post({action:'saveBom',finishedProductId:finished.id,yieldQuantity:Number($('bomYield').value),notes:$('bomNotes').value,components:list});await loadBom();msg('BOM saved. Production still has not changed inventory.');}catch(e){msg(e.message,true);}};
  $('completeProduction').onclick=async()=>{try{if(!bom)throw new Error('Save a BOM before completing production.');const quantity=Number($('productionQty').value),locationId=Number($('productionLocation').value);if(!locationId||!(quantity>0))throw new Error('Choose a location and production quantity.');if(!confirm('Complete '+quantity+' of '+(bom.products?.sku||finished.sku)+'? Components will be consumed and finished goods added to the V2 ledger.'))return;const d=await post({action:'complete',bomId:bom.id,locationId,quantity,reference:$('productionReference').value,idempotencyKey:crypto.randomUUID()});msg(d.alreadyCompleted?'This production run was already recorded.':'Production complete. Finished inventory is now '+d.onHand+'.'+(d.shortages?.length?' Component shortages remain visible for replenishment.':''));$('productionQty').value='';const hist=await get('');renderHistory(hist.history||[]);await loadBom();}catch(e){msg(e.message,true);}};
})();