(()=>{const $=id=>document.getElementById(id);let state,bom;
const api=async body=>{const r=await fetch('/api/manufacturing-v2',body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{}),d=await r.json();if(!r.ok)throw Error(d.error||'Manufacturing request failed');return d};
const say=(m,bad=false)=>{const e=$('productionStatus');e.textContent=m;e.classList.toggle('error',bad)};const add=(s,t,v)=>s.add(new Option(t,String(v)));
function preview(){const h=$('bomPreview');h.replaceChildren();(bom?.mfg_bom_version_components||[]).forEach(c=>{const balance=(state.signedInventory||[]).find(x=>Number(x.product_id)===Number(c.component_product_id))||{quantity:0,allocated_quantity:0};const tr=document.createElement('tr');[c.products?.sku||'—',c.products?.name||'—',c.quantity_per_yield,balance.quantity,balance.allocated_quantity].forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.append(td)});h.append(tr)});$('productionBomStatus').textContent=bom?'Frozen BOM ready · signed inventory at 730 · hash '+bom.component_hash:'Choose a finished SKU to inspect its frozen BOM.';}
function render(){const p=$('productionBom'),d=$('productionDestination');p.replaceChildren();d.replaceChildren();add(p,'Choose finished SKU','');add(d,'Choose destination','');(state.boms||[]).sort((a,b)=>String(a.products?.sku).localeCompare(String(b.products?.sku))).forEach(x=>add(p,(x.products?.sku||'—')+' — '+(x.products?.name||''),x.id));(state.locations||[]).filter(x=>x.code!=='730').forEach(x=>add(d,x.name,x.id));p.onchange=()=>{bom=(state.boms||[]).find(x=>String(x.id)===p.value);preview()};
const rows=$('activeWorkOrderRows');rows.replaceChildren();(state.workOrders||[]).forEach(w=>{const tr=document.createElement('tr'),lines=(w.mfg_work_order_lines||[]).map(l=>(l.products?.sku||l.finished_product_id)+' × '+l.planned_quantity).join(', ');[w.work_order_number,w.machine_code,lines,w.destination?.name||'—',w.notes||'—'].forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.append(td)});const td=document.createElement('td');if(w.status==='Draft'){const b=document.createElement('button');b.type='button';b.className='button secondary';b.textContent='Cancel draft';b.onclick=()=>cancelDraft(w.id);td.append(b)}else td.textContent=w.status+' · read only';tr.append(td);rows.append(tr)});say('Shadow Mode active. View and draft only; release, production, inventory, transfer and Shopify actions are disabled.');}
async function open(){['overviewView','inventoryView','snapshotView','transferView','productSyncView','parLevelsView','replenishmentView','bomManagementView'].forEach(id=>{if($(id))$(id).hidden=true});$('productionView').hidden=false;state=await api();render();}
async function createDraft(){try{if(!bom)throw Error('Choose a finished SKU.');const destination=Number($('productionDestination').value),quantity=Number($('productionQty').value);if(!destination)throw Error('Choose a destination.');if(!Number.isInteger(quantity)||quantity<1)throw Error('Enter a whole-door quantity.');const out=await api({action:'createDraft',destinationLocationId:destination,machineCode:$('productionMachine').value,lines:[{productId:bom.finished_product_id,plannedQuantity:quantity}],priority:'normal',notes:'SHADOW MODE TEST — '+$('productionReference').value,idempotencyKey:'shadow-draft-'+crypto.randomUUID()});say('Draft '+out.result.workOrderNumber+' created. No inventory changed.');await open()}catch(e){say(e.message,true)}}
async function cancelDraft(id){try{await api({action:'cancelDraft',workOrderId:id,idempotencyKey:'shadow-cancel-'+crypto.randomUUID()});await open()}catch(e){say(e.message,true)}}
document.addEventListener('DOMContentLoaded',()=>{$('productionNav').onclick=()=>open().catch(e=>say(e.message,true));const o=$('overviewManufacturing');if(o)o.onclick=()=>open().catch(e=>say(e.message,true));$('productionAddLine').hidden=true;$('productionLocation').hidden=true;$('productionQty').min='1';$('productionQty').step='1';$('productionQty').value='1';$('releaseProduction').textContent='Create draft';$('releaseProduction').onclick=createDraft;const legacy=['mtoSaveTrigger','mtoShopifyProductId','mtoDestination','productionHistoryRows'];legacy.forEach(id=>{const node=$(id);if(node){node.disabled=true;const section=node.closest('section');if(section){section.hidden=true;section.setAttribute('aria-hidden','true')}}});});window.openProduction=open;
})();
