(() => {
  const $ = id => document.getElementById(id); const view = $('productionView'); if (!view) return;
  let locations=[], finished=null, bom=null, lines=[], timer;
  const say=(t,b=false)=>{$('productionStatus').textContent=t;$('productionStatus').classList.toggle('error',b)};
  async function get(q=''){const r=await fetch('/api/production'+q,{credentials:'same-origin',cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d}
  async function post(body){const r=await fetch('/api/production',{method:'POST',headers:{'content-type':'application/json'},credentials:'same-origin',body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d}
  const add=(el,text,value)=>{const o=document.createElement('option');o.textContent=text;o.value=value;el.append(o)};
  function jobLines(){const host=$('productionJobLines');host.replaceChildren();if(!lines.length){host.innerHTML='<tr><td colspan="5" class="muted">Add every door SKU you want on this work order.</td></tr>';return}lines.forEach((line,i)=>{const tr=document.createElement('tr');[line.p.sku,line.p.name,line.q,'Active BOM · yield '+line.b.yield_quantity].forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.append(td)});const td=document.createElement('td'),b=document.createElement('button');b.className='button secondary';b.textContent='Remove';b.onclick=()=>{lines.splice(i,1);jobLines()};td.append(b);tr.append(td);host.append(tr)})}
  function preview(){const host=$('bomPreview');host.replaceChildren();$('productionBomStatus').textContent=bom?'Ready to add: '+(bom.products?.sku||finished?.sku)+' · BOM yield '+bom.yield_quantity:'No active BOM for this finished SKU. Repair it in BOM Management.';(bom?.product_bom_components||[]).forEach(c=>{const tr=document.createElement('tr'),p=c.products||{},b=c.balance||{};[p.sku,p.name,c.quantity_per_yield,b.quantity??'—',b.allocated_quantity??'—'].forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.append(td)});host.append(tr)})}
  function jobs(rows){const host=$('activeWorkOrderRows');host.replaceChildren();if(!rows.length){host.innerHTML='<tr><td colspan="5" class="muted">No released production jobs.</td></tr>';return}rows.forEach(job=>{const tr=document.createElement('tr'),l=job.production_job_lines||[];[job.job_number,l.map(x=>(x.product_boms?.products?.sku||'—')+' × '+x.output_quantity).join(', '),job.destination?.name||'—',job.reference||'—'].forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.append(td)});const td=document.createElement('td'),b=document.createElement('button');b.className='button';b.textContent='Complete';b.onclick=async()=>{try{if(!confirm('Complete '+job.job_number+'? This consumes reserved 730 components and creates one allocated transfer with every finished line.'))return;const d=await post({action:'completeProductionJob',jobId:job.id});say(d.alreadyCompleted?'Already completed.':d.jobNumber+' complete. '+d.transferNumber+' is ready to ship.');await refresh()}catch(e){say(e.message,true)}};td.append(b);tr.append(td);host.append(tr)})}
  async function refresh(){const d=await get('');jobs(d.activeProductionJobs||[]);const h=$('productionHistoryRows');h.replaceChildren();(d.history||[]).forEach(x=>{const tr=document.createElement('tr');[x.document_number,x.description,x.user_name||'—',new Date(x.created_at).toLocaleString()].forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.append(td)});h.append(tr)})}
  async function open(){['overviewView','inventoryView','snapshotView','transferView','receivingView','productSyncView','parLevelsView','replenishmentView','bomManagementView'].forEach(id=>{$(id)&&( $(id).hidden=true)});view.hidden=false;document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.id==='productionNav'));const d=await get();locations=d.locations||[];const floor=locations.find(x=>x.name==='730 Windham Rd'),p=$('productionLocation'),dest=$('productionDestination');p.replaceChildren();add(p,'730 Windham Rd (production floor)',floor?.id||'');p.disabled=true;dest.replaceChildren();add(dest,'Choose final destination','');locations.filter(x=>x.canManage&&x.id!==floor?.id).forEach(x=>add(dest,x.name,x.id));jobs(d.activeProductionJobs||[]);jobLines();say('Search a finished door, add every line to one job, then release it to reserve 730 components.')}
  $('productionNav').onclick=()=>open().catch(e=>say(e.message,true));['overviewNav','inventoryNav','productSyncNav','snapshotNav','transfersNav','receivingNav','parLevelsNav','replenishmentNav','bomManagementNav'].forEach(id=>$(id)?.addEventListener('click',()=>view.hidden=true));
  $('finishedSku').oninput=e=>{finished=null;bom=null;preview();clearTimeout(timer);const term=e.target.value.trim(),box=$('finishedSuggestions');if(term.length<2){box.hidden=true;return}timer=setTimeout(async()=>{try{const found=await get('?term='+encodeURIComponent(term));box.replaceChildren();found.forEach(p=>{const b=document.createElement('button'),s=document.createElement('strong'),m=document.createElement('small');b.type='button';b.className='product-suggestion';s.textContent=p.sku;m.textContent=p.name+(p.barcode?' · '+p.barcode:'')+(p.category?' · '+p.category:'');b.append(s,m);b.onclick=async()=>{finished=p;e.target.value=p.sku+' — '+p.name;box.hidden=true;const d=await get('?bomForProductId='+p.id+'&locationId='+$('productionLocation').value);bom=d.bom;preview()};box.append(b)});box.hidden=!box.childElementCount}catch{box.hidden=true}},120)};
  $('productionAddLine').onclick=()=>{try{const q=Number($('productionQty').value);if(!finished||!bom)throw Error('Search and select a finished door with an active BOM first.');if(!(q>0))throw Error('Enter the finished quantity.');const found=lines.find(x=>x.b.id===bom.id);if(found)found.q+=q;else lines.push({b:bom,p:bom.products||finished,q});$('productionQty').value='';$('finishedSku').value='';finished=null;bom=null;preview();jobLines();say('Door added. Add more SKUs, then release the full job.')}catch(e){say(e.message,true)}};
  $('releaseProduction').onclick=async()=>{try{const dest=Number($('productionDestination').value);if(!dest)throw Error('Choose the final destination.');if(!lines.length)throw Error('Add at least one finished door.');const summary=lines.map(x=>x.p.sku+' × '+x.q).join(', ');if(!confirm('Release one production job?\n\n'+summary+'\n\nComponents will be allocated at 730.'))return;const d=await post({action:'startProductionJob',destinationLocationId:dest,lines:lines.map(x=>({bomId:x.b.id,quantity:x.q})),reference:$('productionReference').value,idempotencyKey:crypto.randomUUID()});say(d.jobNumber+' released. Components are allocated at 730.');lines=[];$('productionReference').value='';jobLines();await refresh()}catch(e){say(e.message,true)}};
})();
