(() => {
  const $ = id => document.getElementById(id), view = $('purchaseOrdersView');
  if (!view) return;
  let orders = [], locations = [], vendors = [], capabilities = {}, draftLines = [], selectedProduct = null, scanned = new Map(), selectedOrderId = null, editingOrder = false;
  let searchTimer;
  const fmt = value => new Intl.NumberFormat('en-US', { maximumFractionDigits: 2 }).format(Number(value || 0));
  const money = value => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(Number(value || 0));
  const set = (text, error = false) => { $('purchaseOrdersStatus').textContent = text; $('purchaseOrdersStatus').classList.toggle('error', error); };
  const scanSet = (text, error = false) => { $('poScanStatus').textContent = text; $('poScanStatus').classList.toggle('error', error); };
  const cell = (row, value) => { const td = document.createElement('td'); td.textContent = value; row.append(td); };
  const selectedOrder = () => orders.find(order => String(order.id) === String(selectedOrderId));
  const activeOrder = () => orders.find(order => String(order.id) === $('poReceiveOrder').value);
  const expectedOrders = () => orders.filter(order => ['ordered', 'partially_received'].includes(order.status));
  const orderTotal = order => (order.purchase_order_lines || []).reduce((total, line) => total + Number(line.ordered_quantity || 0) * Number(line.unit_cost || 0), Number(order.shipping_cost || 0));
  async function request(path, options = {}) { const response = await fetch(path, { credentials: 'same-origin', cache: 'no-store', ...options }); const data = await response.json().catch(() => ({})); if (!response.ok) throw Error(data.error || 'Purchase order request failed'); return data; }
  function setLocationOptions() { const select = $('poReceivingLocation'), previous = select.value; select.replaceChildren(); locations.forEach(location => { const option = document.createElement('option'); option.value = location.id; option.textContent = location.name + (location.code === '730' ? ' (procurement hub)' : ''); select.append(option); }); if ([...select.options].some(option => option.value === previous)) select.value = previous; else { const hub = locations.find(location => location.code === '730'); if (hub) select.value = hub.id; } }
  function setVendorOptions() { const list = $('poVendors'); list.replaceChildren(); vendors.forEach(vendor => { const option = document.createElement('option'); option.value = vendor.name; option.label = vendor.code ? vendor.code + ' · ' + vendor.name : vendor.name; list.append(option); }); }
  function editable() { const order = selectedOrder(); return Boolean(capabilities.canManagePurchaseOrders && (!order || order.status === 'draft' || (editingOrder && ['ordered', 'partially_received'].includes(order.status)))); }
  function renderDraft() {
    const host = $('poDraftLineRows'); host.replaceChildren();
    draftLines.forEach(line => { const row = document.createElement('tr'); cell(row, line.sku || '—'); cell(row, line.name || 'Unnamed product'); cell(row, line.uom || 'EA'); const quantity = document.createElement('td'); if (editable()) { const input = document.createElement('input'); input.className = 'line-quantity-input'; input.type = 'number'; input.min = String(Number(line.receivedQuantity || 0)); input.step = '0.01'; input.value = String(line.quantity); input.setAttribute('aria-label', (line.sku || 'Item') + ' ordered quantity'); input.onchange = () => { const value = Number(input.value); if (!Number.isFinite(value) || value <= 0 || value < Number(line.receivedQuantity || 0)) { input.value = String(line.quantity); return set((line.sku || 'This line') + ' cannot be reduced below its received quantity.', true); } line.quantity = value; renderDraft(); }; quantity.append(input); } else quantity.textContent = fmt(line.quantity); row.append(quantity); cell(row, money(line.unitCost)); cell(row, money(line.quantity * line.unitCost)); const action = document.createElement('td'); if (editable() && !Number(line.receivedQuantity || 0)) { const button = document.createElement('button'); button.className = 'button secondary'; button.type = 'button'; button.textContent = 'Remove'; button.onclick = () => { draftLines = draftLines.filter(item => item.productId !== line.productId); renderDraft(); }; action.append(button); } else if (Number(line.receivedQuantity || 0)) action.textContent = 'Received ' + fmt(line.receivedQuantity); else action.textContent = '—'; row.append(action); host.append(row); });
    if (!draftLines.length) { const row = document.createElement('tr'), empty = document.createElement('td'); empty.colSpan = 7; empty.className = 'muted'; empty.textContent = editable() ? 'Add PO items by scanning or searching a SKU, barcode, or product.' : 'This purchase order has no lines.'; row.append(empty); host.append(row); }
    const material = draftLines.reduce((sum, line) => sum + Number(line.quantity || 0) * Number(line.unitCost || 0), 0), shipping = Math.max(0, Number($('poShippingCost')?.value || 0)); $('poDraftMaterial').textContent = 'Material: ' + money(material); $('poDraftShipping').textContent = 'Shipping: ' + money(shipping); $('poDraftTotal').textContent = 'PO total: ' + money(material + shipping);
  }
  function statusPill(status) { const span = document.createElement('span'); span.className = 'po-status ' + status; span.textContent = status.replaceAll('_', ' '); return span; }
  function renderMaster() {
    const host = $('purchaseOrderMasterRows'), term = $('poMasterSearch').value.trim().toLowerCase(); host.replaceChildren(); const visible = orders.filter(order => !term || [order.purchase_order_number, order.vendor_name, order.supplier_reference_number].filter(Boolean).some(value => String(value).toLowerCase().includes(term)));
    visible.forEach(order => { const row = document.createElement('tr'), lines = order.purchase_order_lines || []; const number = document.createElement('button'); number.className = 'po-order-link'; number.type = 'button'; number.textContent = order.purchase_order_number; number.onclick = () => openDetail(order); const numberCell = document.createElement('td'); numberCell.append(number); row.append(numberCell); cell(row, order.order_date || '—'); cell(row, order.vendor_name || '—'); cell(row, order.supplier_reference_number || '—'); const status = document.createElement('td'); status.append(statusPill(order.status)); row.append(status); cell(row, order.locations?.name || '—'); cell(row, order.expected_date || '—'); cell(row, fmt(lines.reduce((sum, line) => sum + Number(line.received_quantity || 0), 0)) + ' / ' + fmt(lines.reduce((sum, line) => sum + Number(line.ordered_quantity || 0), 0))); cell(row, money(orderTotal(order))); host.append(row); });
    if (!visible.length) { const row = document.createElement('tr'), empty = document.createElement('td'); empty.colSpan = 9; empty.className = 'muted'; empty.textContent = term ? 'No purchase orders match that search.' : 'No purchase orders are visible for your locations.'; row.append(empty); host.append(row); } $('poMasterCount').textContent = 'Showing ' + visible.length + ' of ' + orders.length + ' purchase orders';
  }
  function renderReceiverOptions() { const select = $('poReceiveOrder'), previous = select.value; select.replaceChildren(); const placeholder = document.createElement('option'); placeholder.value = ''; placeholder.textContent = 'Choose sent PO to receive'; select.append(placeholder); expectedOrders().forEach(order => { const option = document.createElement('option'); option.value = order.id; option.textContent = order.purchase_order_number + ' · ' + (order.vendor_name || 'Supplier') + ' · ' + (order.locations?.name || 'Receiving location'); select.append(option); }); if ([...select.options].some(option => option.value === previous)) select.value = previous; }
  function renderScanRows() { const host = $('poScanRows'), order = activeOrder(); host.replaceChildren(); if (!order) { const row = document.createElement('tr'), empty = document.createElement('td'); empty.colSpan = 6; empty.className = 'muted'; empty.textContent = 'Choose a sent purchase order to view its expected lines.'; row.append(empty); host.append(row); return; } (order.purchase_order_lines || []).forEach(line => { const now = Number(scanned.get(line.id) || 0), remaining = Number(line.ordered_quantity) - Number(line.received_quantity) - now, row = document.createElement('tr'); cell(row, line.products?.sku || '—'); cell(row, line.products?.name || 'Unnamed product'); cell(row, fmt(line.ordered_quantity)); cell(row, fmt(line.received_quantity)); cell(row, fmt(now)); cell(row, fmt(remaining)); host.append(row); }); }
  function selectReceiverOrder() { scanned = new Map(); renderScanRows(); const order = activeOrder(); scanSet(order ? 'Ready to scan ' + order.purchase_order_number + ' into ' + (order.locations?.name || 'its receiving location') + '.' : 'Choose a sent PO to begin scanning.'); }
  function renderEditor() {
    const order = selectedOrder(), canEdit = editable(), hasReceipts = (order?.purchase_order_lines || []).some(line => Number(line.received_quantity || 0) > 0), openOrder = ['ordered', 'partially_received'].includes(order?.status); $('poMasterList').hidden = true; $('poDetailPanel').hidden = false; $('poDetailTitle').textContent = order ? order.purchase_order_number : 'New purchase order'; $('poDetailHelp').textContent = order ? (order.status === 'draft' ? 'Edit this draft, then send it to enable warehouse receiving.' : canEdit ? 'Editing this open PO. Received quantities stay protected; changes apply only to the remaining order.' : 'This order is ' + order.status.replaceAll('_', ' ') + '. Use Edit PO for admin changes or Receive PO for the warehouse scan workflow.') : 'Normal procurement lands at 730. Select a retail location only for a direct-to-retail PO.'; $('poEdit').hidden = !(capabilities.canManagePurchaseOrders && openOrder && !canEdit); $('poSave').hidden = !canEdit; $('poSave').textContent = order ? (order.status === 'draft' ? 'Save draft changes' : 'Save PO changes') : 'Create draft'; $('poSend').hidden = !(order?.status === 'draft' && capabilities.canManagePurchaseOrders); $('poReceiveFromDetail').hidden = !expectedOrders().some(item => item.id === order?.id);
    ['poNumber', 'poVendor', 'poSupplierReference', 'poReceivingLocation', 'poOrderDate', 'poExpectedDate', 'poShippingCost', 'poNotes', 'poProductSearch', 'poLineQuantity', 'poLineUom', 'poLineCost', 'poAddLine'].forEach(id => { $(id).disabled = !canEdit; }); $('poNumber').disabled = Boolean(order); $('poReceivingLocation').disabled = !canEdit || hasReceipts; $('poEditorControls').hidden = !canEdit; renderDraft();
  }
  function clearEditor() { selectedOrderId = null; draftLines = []; selectedProduct = null; ['poNumber', 'poVendor', 'poSupplierReference', 'poExpectedDate', 'poNotes'].forEach(id => { $(id).value = ''; }); $('poOrderDate').value = new Date().toISOString().slice(0, 10); $('poShippingCost').value = '0.00'; $('poLineQuantity').value = '1'; $('poLineUom').value = 'EA'; $('poLineCost').value = '0.00'; setLocationOptions(); renderSuggestions([]); }
  function openDetail(order = null) { editingOrder = false; if (order) { selectedOrderId = order.id; draftLines = (order.purchase_order_lines || []).map(line => ({ productId: Number(line.product_id), sku: line.products?.sku, name: line.products?.name, quantity: Number(line.ordered_quantity), receivedQuantity: Number(line.received_quantity || 0), uom: line.uom || 'EA', unitCost: Number(line.unit_cost || 0) })); $('poNumber').value = order.purchase_order_number || ''; $('poVendor').value = order.vendor_name || ''; $('poSupplierReference').value = order.supplier_reference_number || ''; $('poReceivingLocation').value = String(order.receiving_location_id || ''); $('poOrderDate').value = order.order_date || ''; $('poExpectedDate').value = order.expected_date || ''; $('poShippingCost').value = Number(order.shipping_cost || 0).toFixed(2); $('poNotes').value = order.notes || ''; } else clearEditor(); renderEditor(); window.scrollTo({ top: 0, behavior: 'smooth' }); }
  function backToMaster() { editingOrder = false; $('poDetailPanel').hidden = true; $('poMasterList').hidden = false; selectedOrderId = null; renderMaster(); }
  function renderAll() { setLocationOptions(); setVendorOptions(); renderMaster(); renderReceiverOptions(); renderScanRows(); if (!$('poDetailPanel').hidden) renderEditor(); }
  async function load() { const data = await request('/api/purchase-orders'); orders = data.orders || []; locations = data.locations || []; vendors = data.vendors || []; capabilities = data.capabilities || {}; renderAll(); set(capabilities.canManagePurchaseOrders ? 'PO master ready. Click an order to work it.' : 'Choose a sent PO from Overview to begin scan-first receiving.'); }
  function renderSuggestions(products) { const host = $('poProductSuggestions'); host.replaceChildren(); products.slice(0, 8).forEach(product => { const button = document.createElement('button'); button.type = 'button'; button.className = 'product-suggestion'; button.textContent = (product.sku || 'No SKU') + ' — ' + (product.name || 'Unnamed product'); button.onclick = () => { selectedProduct = product; $('poProductSearch').value = button.textContent; host.hidden = true; }; host.append(button); }); host.hidden = !products.length; }
  async function searchProducts() { const term = $('poProductSearch').value.trim(); selectedProduct = null; if (term.length < 2) return renderSuggestions([]); const data = await request('/api/purchase-orders?productSearch=' + encodeURIComponent(term)); renderSuggestions(data.products || []); }
  function addDraftLine() { const quantity = Number($('poLineQuantity').value), unitCost = Number($('poLineCost').value), uom = String($('poLineUom').value || 'EA').trim().toUpperCase(); if (!editable()) throw Error('Only an admin can edit this purchase order.'); if (!selectedProduct || !Number.isFinite(quantity) || quantity <= 0 || !Number.isFinite(unitCost) || unitCost < 0 || !uom) throw Error('Choose a product, positive quantity, UOM, and non-negative unit cost.'); const existing = draftLines.find(line => Number(line.productId) === Number(selectedProduct.id)); if (existing) { existing.quantity += quantity; existing.unitCost = unitCost; existing.uom = uom; } else draftLines.push({ productId: Number(selectedProduct.id), sku: selectedProduct.sku, name: selectedProduct.name, quantity, unitCost, uom }); selectedProduct = null; $('poProductSearch').value = ''; $('poLineQuantity').value = '1'; $('poLineUom').value = 'EA'; $('poLineCost').value = '0.00'; renderSuggestions([]); renderDraft(); }
  function editorPayload(action) { return { action, purchaseOrderId: selectedOrderId, purchaseOrderNumber: $('poNumber').value, vendorName: $('poVendor').value, supplierReferenceNumber: $('poSupplierReference').value, receivingLocationId: Number($('poReceivingLocation').value), orderDate: $('poOrderDate').value || null, expectedDate: $('poExpectedDate').value || null, shippingCost: Number($('poShippingCost').value || 0), notes: $('poNotes').value, lines: draftLines.map(line => ({ productId: line.productId, quantity: line.quantity, uom: line.uom, unitCost: line.unitCost })), idempotencyKey: crypto.randomUUID() }; }
  async function saveDraft() { if (!draftLines.length) throw Error('Add at least one PO item.'); const order = selectedOrder(); const action = order ? (order.status === 'draft' ? 'update-detailed' : 'update-open-detailed') : 'create-detailed'; const data = await request('/api/purchase-orders', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(editorPayload(action)) }); set(data.purchaseOrder.purchaseOrderNumber + (order ? ' updated.' : ' drafted.')); await load(); const latest = orders.find(item => item.id === data.purchaseOrder.id || item.purchase_order_number === data.purchaseOrder.purchaseOrderNumber); if (latest) openDetail(latest); }
  async function sendOrder() { const order = selectedOrder(); if (!order || !confirm('Send ' + order.purchase_order_number + ' to the supplier? Warehouse receiving will then be enabled.')) return; const data = await request('/api/purchase-orders', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'send', purchaseOrderId: order.id }) }); set(data.purchaseOrder.purchaseOrderNumber + ' sent.'); await load(); const latest = orders.find(item => item.id === order.id); if (latest) openDetail(latest); }
  async function openReceiver(order = null) { await load(); if (order) $('poReceiveOrder').value = String(order.id); selectReceiverOrder(); const dialog = $('poReceivingDialog'); if (typeof dialog.showModal === 'function' && !dialog.open) dialog.showModal(); else dialog.hidden = false; $('poScanInput').focus(); }
  function scan(value) { const order = activeOrder(), code = String(value || '').trim().toLowerCase(); if (!order) throw Error('Choose a sent purchase order first.'); if (!code) return; const line = (order.purchase_order_lines || []).find(item => [item.products?.sku, item.products?.barcode].filter(Boolean).some(candidate => String(candidate).trim().toLowerCase() === code)); if (!line) throw Error('That SKU/barcode is not an expected line on ' + order.purchase_order_number + '.'); const count = Number(scanned.get(line.id) || 0), outstanding = Number(line.ordered_quantity) - Number(line.received_quantity); if (count >= outstanding) throw Error((line.products?.sku || 'This item') + ' is already fully scanned for this PO.'); scanned.set(line.id, count + 1); $('poScanInput').value = ''; renderScanRows(); scanSet((line.products?.sku || 'Item') + ' scanned · ' + (count + 1) + ' of ' + fmt(outstanding) + ' for this receipt.'); }
  async function postReceipt() { const order = activeOrder(), lines = [...scanned.entries()].map(([lineId, quantity]) => ({ lineId, quantity })); if (!order || !lines.length) throw Error('Scan at least one expected PO item before posting.'); const data = await request('/api/purchase-orders', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'receive-lines', purchaseOrderId: order.id, lines, idempotencyKey: crypto.randomUUID() }) }); scanSet(data.purchaseOrder.purchaseOrderNumber + ' updated: ' + data.purchaseOrder.status.replaceAll('_', ' ') + '.'); scanned = new Map(); await load(); }
  $('purchaseOrdersNav').addEventListener('click', () => { document.querySelectorAll('main > section, #overviewView').forEach(element => { if (element.id !== 'purchaseOrdersView') element.hidden = true; }); view.hidden = false; document.querySelectorAll('.nav-item').forEach(item => item.classList.toggle('active', item.id === 'purchaseOrdersNav')); load().catch(error => set(error.message, true)); }); document.querySelectorAll('.nav-item').forEach(item => { if (item.id !== 'purchaseOrdersNav') item.addEventListener('click', () => { view.hidden = true; }); });
  $('purchaseOrdersRefresh').onclick = () => load().catch(error => set(error.message, true)); $('poNewOrder').onclick = () => { if (!capabilities.canManagePurchaseOrders) return set('Only an admin can create a purchase order.', true); openDetail(); }; $('poBackToMaster').onclick = backToMaster; $('poEdit').onclick = () => { editingOrder = true; renderEditor(); }; $('poSave').onclick = () => saveDraft().catch(error => set(error.message, true)); $('poSend').onclick = () => sendOrder().catch(error => set(error.message, true)); $('poReceiveFromDetail').onclick = () => openReceiver(selectedOrder()).catch(error => set(error.message, true)); $('poMasterSearch').oninput = renderMaster;
  $('poProductSearch').addEventListener('input', () => { clearTimeout(searchTimer); searchTimer = setTimeout(() => searchProducts().catch(error => set(error.message, true)), 180); }); $('poAddLine').onclick = () => { try { addDraftLine(); } catch (error) { set(error.message, true); } }; $('poShippingCost').oninput = renderDraft; $('poOrderDate').value = new Date().toISOString().slice(0, 10); $('overviewReceivePo').onclick = () => openReceiver().catch(error => set(error.message, true)); $('poReceiveOrder').onchange = selectReceiverOrder; $('poScanInput').addEventListener('keydown', event => { if (event.key === 'Enter') { event.preventDefault(); try { scan(event.currentTarget.value); } catch (error) { scanSet(error.message, true); } } }); $('poPostReceipt').onclick = () => postReceipt().catch(error => scanSet(error.message, true));
})();
