(() => {
  const $ = id => document.getElementById(id), view = $('purchaseOrdersView');
  if (!view) return;
  let orders = [], selected = null, canPurchase = false;
  const set = (text, error = false) => { $('poMasterStatus').textContent = text; $('poMasterStatus').classList.toggle('error', error); };
  const receiptSet = (text, error = false) => { $('poReceiptStatus').textContent = text; $('poReceiptStatus').classList.toggle('error', error); };
  const cell = (row, value) => { const td = document.createElement('td'); td.textContent = value; row.append(td); };
  const number = value => new Intl.NumberFormat('en-US', { maximumFractionDigits: 2 }).format(Number(value || 0));
  const remaining = line => Number(line.ordered_quantity) - Number(line.received_quantity) - Number(line.damaged_quantity || 0);
  function activeRows() {
    const term = $('poSearch').value.trim().toLowerCase(), status = $('poStatusFilter').value;
    return orders.filter(order => (!status || order.status === status) && (!term || [order.purchase_order_number, order.vendor_name, ...(order.purchase_order_lines || []).flatMap(line => [line.products?.sku, line.products?.name])].join(' ').toLowerCase().includes(term)));
  }
  function renderMaster() {
    const host = $('poMasterRows'); host.replaceChildren();
    activeRows().forEach(order => {
      const row = document.createElement('tr'), lines = order.purchase_order_lines || [], ordered = lines.reduce((sum, line) => sum + Number(line.ordered_quantity || 0), 0), received = lines.reduce((sum, line) => sum + Number(line.received_quantity || 0), 0);
      cell(row, order.purchase_order_number); cell(row, order.vendor_name || 'Unassigned'); cell(row, order.locations?.name || '—'); cell(row, number(received) + ' / ' + number(ordered)); cell(row, order.status.replaceAll('_', ' '));
      const action = document.createElement('td'), open = document.createElement('button'); open.className = 'button secondary'; open.type = 'button'; open.textContent = ['received', 'cancelled'].includes(order.status) ? 'View / print' : 'Scan receive'; open.onclick = () => selectOrder(order.id); action.append(open);
      if (order.status === 'draft' && canPurchase) { const send = document.createElement('button'); send.className = 'button'; send.type = 'button'; send.textContent = 'Mark sent'; send.onclick = async () => { try { await post({ action: 'mark-ordered', purchaseOrderId: order.id }); set(order.purchase_order_number + ' marked ordered.'); await load(); } catch (error) { set(error.message, true); } }; action.append(' ', send); }
      row.append(action); host.append(row);
    });
    if (!host.children.length) host.innerHTML = '<tr><td colspan="6" class="muted">No purchase orders match this view.</td></tr>';
  }
  function renderDetail() {
    if (!selected) return; $('poDetailCard').hidden = false; $('poDetailTitle').textContent = selected.purchase_order_number + ' · ' + (selected.vendor_name || 'Unassigned vendor'); $('poDetailMeta').textContent = 'Receive at ' + (selected.locations?.name || 'managed warehouse') + ' · ' + selected.status.replaceAll('_', ' ');
    const host = $('poDetailRows'); host.replaceChildren();
    (selected.purchase_order_lines || []).forEach(line => {
      const row = document.createElement('tr'), sku = line.products?.sku || 'No SKU', left = remaining(line); cell(row, sku); cell(row, line.products?.name || 'Unknown product'); cell(row, number(line.ordered_quantity)); cell(row, number(line.received_quantity)); cell(row, number(line.damaged_quantity)); cell(row, number(left));
      const good = document.createElement('input'); good.className = 'inventory-search'; good.type = 'number'; good.min = '0'; good.step = '1'; good.value = '0'; good.dataset.receiptGood = line.id; good.disabled = left <= 0 || ['received', 'cancelled'].includes(selected.status); const goodCell = document.createElement('td'); goodCell.append(good); row.append(goodCell);
      const damaged = document.createElement('input'); damaged.className = 'inventory-search'; damaged.type = 'number'; damaged.min = '0'; damaged.step = '1'; damaged.value = '0'; damaged.dataset.receiptDamage = line.id; damaged.disabled = good.disabled; const damageCell = document.createElement('td'); damageCell.append(damaged); row.append(damageCell); host.append(row);
    });
  }
  async function post(body) { const response = await fetch('/api/purchase-orders', { method: 'POST', credentials: 'same-origin', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) throw Error(data.error || 'Purchase order request failed'); return data; }
  async function load() { set('Loading purchase orders…'); const response = await fetch('/api/purchase-orders', { credentials: 'same-origin', cache: 'no-store' }); const data = await response.json(); if (!response.ok) throw Error(data.error || 'Unable to load purchase orders'); orders = data.orders || []; canPurchase = Boolean(data.canPurchase); if (selected) selected = orders.find(order => order.id === selected.id) || null; renderMaster(); if (selected) renderDetail(); set(orders.length + ' purchase orders loaded.'); }
  function selectOrder(id) { selected = orders.find(order => Number(order.id) === Number(id)); if (!selected) return; $('poScanInput').value = ''; $('poReceiptReference').value = ''; $('poReceiptNote').value = ''; receiptSet('Scan a SKU to add one good piece. Adjust quantities or damage below before posting.'); renderDetail(); $('poDetailCard').scrollIntoView({ behavior: 'smooth', block: 'start' }); }
  $('purchaseOrdersNav').addEventListener('click', () => { ['overviewView', 'inventoryView', 'snapshotView', 'transferView', 'receivingView', 'productionView', 'productSyncView', 'parLevelsView', 'bomManagementView', 'replenishmentView', 'forecastingView', 'skuFixView'].forEach(id => { const element = $(id); if (element) element.hidden = true; }); view.hidden = false; document.querySelectorAll('.nav-item').forEach(x => x.classList.toggle('active', x.id === 'purchaseOrdersNav')); load().catch(error => set(error.message, true)); });
  ['overviewNav', 'inventoryNav', 'productSyncNav', 'snapshotNav', 'transfersNav', 'receivingNav', 'productionNav', 'parLevelsNav', 'bomManagementNav', 'replenishmentNav', 'forecastNav', 'skuFixNav'].forEach(id => $(id)?.addEventListener('click', () => view.hidden = true));
  $('purchaseOrdersRefresh').addEventListener('click', () => load().catch(error => set(error.message, true))); $('poSearch').addEventListener('input', renderMaster); $('poStatusFilter').addEventListener('change', renderMaster);
  $('poScanInput').addEventListener('keydown', event => { if (event.key !== 'Enter') return; event.preventDefault(); const scan = event.target.value.trim().toLowerCase(); if (!scan || !selected) return; const line = (selected.purchase_order_lines || []).find(x => [x.products?.sku, x.products?.barcode].filter(Boolean).some(value => String(value).toLowerCase() === scan)); if (!line) return receiptSet('No open PO line matches "' + event.target.value.trim() + '".', true); const input = document.querySelector('[data-receipt-good="' + line.id + '"]'); if (!input || input.disabled) return receiptSet((line.products?.sku || 'That item') + ' has no remaining quantity.', true); input.value = String(Number(input.value || 0) + 1); event.target.value = ''; receiptSet((line.products?.sku || 'Item') + ' scanned into this receipt.'); });
  $('poPostReceipt').addEventListener('click', async () => { try { if (!selected) throw Error('Select a purchase order first.'); const lines = (selected.purchase_order_lines || []).map(line => ({ lineId: line.id, receivedQuantity: Number(document.querySelector('[data-receipt-good="' + line.id + '"]').value || 0), damagedQuantity: Number(document.querySelector('[data-receipt-damage="' + line.id + '"]').value || 0) })).filter(line => line.receivedQuantity > 0 || line.damagedQuantity > 0); if (!lines.length) throw Error('Scan or enter at least one received line.'); const data = await post({ action: 'receive-lines', purchaseOrderId: selected.id, lines, reference: $('poReceiptReference').value, notes: $('poReceiptNote').value, idempotencyKey: 'po-receipt-' + selected.id + '-' + Date.now() }); receiptSet(data.receipt.receiptNumber + ' posted. Inventory updated only for good pieces.'); await load(); } catch (error) { receiptSet(error.message, true); } });
  $('poPrint').addEventListener('click', () => { if (!selected) return; const lines = (selected.purchase_order_lines || []).map(line => '<tr><td>' + (line.products?.sku || '') + '</td><td>' + (line.products?.name || '') + '</td><td>' + number(line.ordered_quantity) + '</td><td>' + number(line.received_quantity) + '</td></tr>').join(''); const popup = window.open('about:blank', '_blank', 'width=900,height=700'); if (!popup) return receiptSet('Allow pop-ups to print this PO.', true); popup.document.write('<!doctype html><title>' + selected.purchase_order_number + '</title><style>body{font:14px Arial;padding:32px}table{width:100%;border-collapse:collapse}td,th{border:1px solid #bbb;padding:8px;text-align:left}</style><h1>' + selected.purchase_order_number + '</h1><p>Vendor: ' + (selected.vendor_name || 'Unassigned') + '<br>Receive at: ' + (selected.locations?.name || '') + '</p><table><thead><tr><th>SKU</th><th>Product</th><th>Ordered</th><th>Received</th></tr></thead><tbody>' + lines + '</tbody></table>'); popup.document.close(); popup.focus(); popup.print(); });
})();
