(() => {
  const $ = id => document.getElementById(id), view = $('replenishmentView');
  if (!view) return;
  let all = [], recommendations = [], purchaseQueue = [], purchaseOrders = [], showAllPurchaseQueue = false;
  const purchaseQueueLimit = 15, fmt = n => new Intl.NumberFormat('en-US', { maximumFractionDigits: 2 }).format(n);
  const set = (text, error = false) => { $('replenishmentStatus').textContent = text; $('replenishmentStatus').classList.toggle('error', error); };
  const poSet = (text, error = false) => { $('purchaseOrderStatus').textContent = text; $('purchaseOrderStatus').classList.toggle('error', error); };
  const cell = (row, value) => { const td = document.createElement('td'); td.textContent = value; row.append(td); };

  function renderBoard(board) {
    const host = $('lowStockBoard'); host.replaceChildren(); const byLoc = new Map();
    board.forEach(x => { if (!byLoc.has(x.location)) byLoc.set(x.location, []); byLoc.get(x.location).push(x); });
    [...byLoc.entries()].sort(([a], [b]) => a.localeCompare(b)).forEach(([location, groups]) => {
      const card = document.createElement('section'); card.className = 'low-stock-card' + (groups.some(x => x.below > 0) ? ' alert' : '');
      const head = document.createElement('div'); head.className = 'low-stock-card-head'; const title = document.createElement('div'); title.innerHTML = '<span>WAREHOUSE</span><strong></strong>'; title.querySelector('strong').textContent = location;
      const total = groups.reduce((n, x) => n + x.below, 0), badge = document.createElement('span'); badge.className = 'low-stock-badge'; badge.textContent = total ? total + ' below par' : 'Healthy'; head.append(title, badge); card.append(head);
      groups.forEach(x => { const row = document.createElement('div'); row.className = 'low-stock-row'; const name = document.createElement('span'), status = document.createElement('strong'); name.textContent = x.category; status.className = x.below ? 'needs' : 'healthy'; status.textContent = x.below ? x.below + ' below par' : 'Healthy'; row.append(name, status); card.append(row); }); host.append(card);
    });
  }
  function renderPurchaseOrders() {
    const host = $('purchaseOrderRows'); host.replaceChildren(); const open = purchaseOrders.filter(order => !['received', 'cancelled'].includes(order.status));
    open.forEach(order => {
      const row = document.createElement('tr'), lines = order.purchase_order_lines || []; cell(row, order.purchase_order_number); cell(row, order.vendor_name || 'Unassigned'); cell(row, String(lines.length)); cell(row, fmt(lines.reduce((sum, line) => sum + Number(line.ordered_quantity || 0), 0))); cell(row, order.status.replaceAll('_', ' '));
      const action = document.createElement('td'), receive = document.createElement('button'); receive.className = 'button'; receive.type = 'button'; receive.textContent = 'Receive at 730';
      receive.onclick = async () => { try { if (!confirm('Receive every outstanding line on ' + order.purchase_order_number + ' into 730?')) return; const response = await fetch('/api/purchase-orders', { method: 'POST', credentials: 'same-origin', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'receive', purchaseOrderId: order.id }) }), data = await response.json(); if (!response.ok) throw Error(data.error || 'Could not receive purchase order'); poSet(data.purchaseOrder.purchaseOrderNumber + ' received into 730. Create MT transfers when you are ready to distribute it.'); await load(); } catch (error) { poSet(error.message, true); } };
      action.append(receive); row.append(action); host.append(row);
    });
    if (!open.length) { const row = document.createElement('tr'), td = document.createElement('td'); td.colSpan = 6; td.className = 'muted'; td.textContent = 'No open purchase orders for 730.'; row.append(td); host.append(row); }
  }
  function buildPurchaseQueue() {
    const remaining = all.map(x => ({ ...x, remaining: Math.max(x.shortage - recommendations.filter(r => r.productId === x.productId && r.toLocationId === x.locationId).reduce((n, r) => n + r.quantity, 0), 0) })).filter(x => x.remaining > 0), grouped = new Map();
    remaining.forEach(x => { if (!grouped.has(x.productId)) grouped.set(x.productId, { productId: x.productId, sku: x.sku, product: x.product, category: x.category, quantity: 0, warehouses: [] }); const row = grouped.get(x.productId); row.quantity += x.remaining; row.warehouses.push(x.location); }); purchaseQueue = [...grouped.values()].sort((a, b) => b.quantity - a.quantity);
  }
  function render() {
    const term = $('replenishmentSearch').value.trim().toLowerCase(), locationId = $('replenishmentLocation').value, rows = all.filter(x => (!locationId || String(x.locationId) === locationId) && (!term || [x.sku, x.product, x.category, x.barcode, x.location].join(' ').toLowerCase().includes(term))), host = $('replenishmentRows'); host.replaceChildren();
    rows.forEach(x => { const row = document.createElement('tr'); [x.location, x.sku, x.product, x.category || '—', fmt(x.onHand), fmt(x.shortage), fmt(x.shortage)].forEach((value, index) => { const td = document.createElement('td'); td.textContent = value; if (index === 4) td.className = 'zero'; if (index > 4) td.style.color = '#ff8a8a'; row.append(td); }); host.append(row); });
    if (!rows.length) host.innerHTML = '<tr><td colspan="7" class="muted">No shortages match those filters.</td></tr>';
    $('replenishmentCount').textContent = rows.length + ' shortage SKUs'; $('replenishmentDeficit').textContent = fmt(rows.reduce((n, x) => n + x.shortage, 0)) + ' pieces to replenish';
    buildPurchaseQueue(); const buyHost = $('purchaseQueueRows'); buyHost.replaceChildren(); const visible = showAllPurchaseQueue ? purchaseQueue : purchaseQueue.slice(0, purchaseQueueLimit);
    visible.forEach(item => { const row = document.createElement('tr'), selected = document.createElement('input'); selected.type = 'checkbox'; selected.checked = true; selected.dataset.purchaseProductId = item.productId; const buy = document.createElement('td'); buy.append(selected); row.append(buy); cell(row, item.sku); cell(row, item.product); cell(row, item.category || '—'); cell(row, [...new Set(item.warehouses)].join(', ')); const amount = document.createElement('input'); amount.type = 'number'; amount.min = '0.01'; amount.step = '0.01'; amount.value = item.quantity; amount.className = 'inventory-search'; amount.dataset.purchaseQuantity = item.productId; const amountCell = document.createElement('td'); amountCell.append(amount); row.append(amountCell); buyHost.append(row); });
    if (!purchaseQueue.length) buyHost.innerHTML = '<tr><td colspan="6" class="muted">Internal transfer coverage resolves every current shortage.</td></tr>';
    $('purchaseQueueCount').textContent = purchaseQueue.length + ' SKUs to buy'; $('purchaseQueueQty').textContent = fmt(purchaseQueue.reduce((n, x) => n + x.quantity, 0)) + ' pieces remaining'; const toggle = $('purchaseQueueToggle'); toggle.hidden = purchaseQueue.length <= purchaseQueueLimit; toggle.textContent = showAllPurchaseQueue ? 'Show top ' + purchaseQueueLimit : 'Show all ' + purchaseQueue.length; $('purchaseQueueVisible').textContent = 'Selected lines create a draft PO received into 730.';
    const recHost = $('transferFirstRows'); recHost.replaceChildren(); const recs = recommendations.filter(x => !term || [x.sku, x.product, x.from, x.to].join(' ').toLowerCase().includes(term)); recs.forEach(x => { const row = document.createElement('tr'); [x.sku, x.product, x.from, x.to, fmt(x.quantity)].forEach(value => cell(row, value)); recHost.append(row); }); if (!recs.length) recHost.innerHTML = '<tr><td colspan="5" class="muted">No internal transfer opportunity found for the current shortage queue.</td></tr>'; $('transferFirstCount').textContent = recs.length + ' suggested moves';
  }
  async function loadOrders() { const response = await fetch('/api/purchase-orders', { credentials: 'same-origin', cache: 'no-store' }), data = await response.json(); if (!response.ok) throw Error(data.error || 'Unable to load purchase orders'); purchaseOrders = data.orders || []; poSet((data.hub?.name || '730') + ' is the procurement hub. Drafts are inventory-neutral.'); renderPurchaseOrders(); }
  async function load() {
    set('Loading V2 shortages…'); const response = await fetch('/api/replenishment', { credentials: 'same-origin', cache: 'no-store' }), data = await response.json(); if (!response.ok) throw Error(data.error || 'Unable to load replenishment'); all = data.items || []; recommendations = data.recommendations || []; renderBoard(data.board || []);
    const select = $('replenishmentLocation'); select.replaceChildren(); const option = document.createElement('option'); option.value = ''; option.textContent = 'All warehouses'; select.append(option); (data.locations || []).forEach(x => { const option = document.createElement('option'); option.value = x.id; option.textContent = x.name; select.append(option); }); render(); await loadOrders(); set(all.length + ' shortage SKUs · ' + fmt(all.reduce((n, x) => n + x.shortage, 0)) + ' total pieces required.');
  }
  $('createPurchaseOrder').addEventListener('click', async () => { try { const lines = [...document.querySelectorAll('[data-purchase-product-id]')].filter(input => input.checked).map(input => ({ productId: Number(input.dataset.purchaseProductId), quantity: Number(document.querySelector('[data-purchase-quantity="' + input.dataset.purchaseProductId + '"]').value) })); if (!lines.length) throw Error('Select at least one item to buy.'); const response = await fetch('/api/purchase-orders', { method: 'POST', credentials: 'same-origin', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'create', vendorName: $('purchaseVendor').value, notes: $('purchaseNotes').value, lines, idempotencyKey: 'po-' + Date.now() }) }), data = await response.json(); if (!response.ok) throw Error(data.error || 'Could not create purchase order'); poSet(data.purchaseOrder.purchaseOrderNumber + ' drafted for 730. It will not change inventory until received.'); $('purchaseNotes').value = ''; await load(); } catch (error) { poSet(error.message, true); } });
  $('replenishmentNav').addEventListener('click', () => { ['overviewView', 'inventoryView', 'snapshotView', 'transferView', 'receivingView', 'productionView', 'productSyncView', 'parLevelsView', 'bomManagementView'].forEach(id => { const element = $(id); if (element) element.hidden = true; }); view.hidden = false; document.querySelectorAll('.nav-item').forEach(x => x.classList.toggle('active', x.id === 'replenishmentNav')); load().catch(error => set(error.message, true)); });
  ['overviewNav', 'inventoryNav', 'productSyncNav', 'snapshotNav', 'transfersNav', 'receivingNav', 'productionNav', 'parLevelsNav', 'bomManagementNav'].forEach(id => $(id)?.addEventListener('click', () => view.hidden = true)); $('replenishmentRefresh').addEventListener('click', () => load().catch(error => set(error.message, true))); $('purchaseQueueToggle').addEventListener('click', () => { showAllPurchaseQueue = !showAllPurchaseQueue; render(); }); $('replenishmentSearch').addEventListener('input', render); $('replenishmentLocation').addEventListener('change', render);
})();
