(() => {
 const $=id=>document.getElementById(id); const view=$('replenishmentView'); if(!view)return;
 let all=[], recommendations=[], purchaseQueue=[];
 const fmt=n=>new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(n);
 function renderBoard(board){const host=$('lowStockBoard');host.replaceChildren();const byLoc=new Map();(board||[]).forEach(x=>{if(!byLoc.has(x.location))byLoc.set(x.location,[]);byLoc.get(x.location).push(x);});[...byLoc.entries()].sort((a,b)=>a[0].localeCompare(b[0])).forEach(([location,groups])=>{const card=document.createElement('section');card.className='low-stock-card'+(groups.some(x=>x.below>0)?' alert':'');const head=document.createElement('div');head.className='low-stock-card-head';const title=document.createElement('div');title.innerHTML='<span>WAREHOUSE</span><strong></strong>';title.querySelector('strong').textContent=location;const total=groups.reduce((n,x)=>n+x.below,0);const badge=document.createElement('span');badge.className='low-stock-badge';badge.textContent=total?total+' below par':'Healthy';head.append(title,badge);card.append(head);groups.forEach(x=>{const row=document.createElement('div');row.className='low-stock-row';const name=document.createElement('span');name.textContent=x.category;const status=document.createElement('strong');status.className=x.below?'needs':'healthy';status.textContent=x.below?x.below+' below par':'Healthy';row.append(name,status);card.append(row);});host.append(card);});}
 const set=(t,e=false)=>{$('replenishmentStatus').textContent=t;$('replenishmentStatus').classList.toggle('error',e);};
 function render(){
  const term=$('replenishmentSearch').value.trim().toLowerCase(),loc=$('replenishmentLocation').value;
  const rows=all.filter(x=>(!loc||String(x.locationId)===loc)&&(!term||[x.sku,x.product,x.category,x.barcode,x.location].join(' ').toLowerCase().includes(term)));
  const host=$('replenishmentRows');host.replaceChildren();
  rows.forEach(x=>{const tr=document.createElement('tr');[x.location,x.sku,x.product,x.category||'—',fmt(x.onHand),fmt(x.shortage),fmt(x.shortage)].forEach((v,i)=>{const td=document.createElement('td');td.textContent=v;if(i===4)td.className='zero';if(i===5||i===6)td.style.color='#ff8a8a';tr.append(td)});host.append(tr);});
  if(!rows.length){const tr=document.createElement('tr');const td=document.createElement('td');td.colSpan=7;td.className='muted';td.textContent='No shortages match those filters.';tr.append(td);host.append(tr);}
  const total=rows.reduce((n,x)=>n+x.shortage,0);$('replenishmentCount').textContent=rows.length+' shortage SKUs';$('replenishmentDeficit').textContent=fmt(total)+' pieces to replenish';
  const covered=new Map();recommendations.forEach(x=>covered.set(x.productId,(covered.get(x.productId)||0)+x.quantity));const remaining=all.map(x=>({...x,remaining:Math.max(x.shortage-(recommendations.filter(r=>r.productId===x.productId&&r.toLocationId===x.locationId).reduce((n,r)=>n+r.quantity,0)),0)})).filter(x=>x.remaining>0);const grouped=new Map();remaining.forEach(x=>{const k=x.productId;if(!grouped.has(k))grouped.set(k,{sku:x.sku,product:x.product,category:x.category,quantity:0,warehouses:[]});const y=grouped.get(k);y.quantity+=x.remaining;y.warehouses.push(x.location);});purchaseQueue=[...grouped.values()].sort((a,b)=>b.quantity-a.quantity);const buyHost=$('purchaseQueueRows');buyHost.replaceChildren();purchaseQueue.forEach(x=>{const tr=document.createElement('tr');[x.sku,x.product,x.category||'—',[...new Set(x.warehouses)].join(', '),fmt(x.quantity)].forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.append(td)});buyHost.append(tr);});if(!purchaseQueue.length){const tr=document.createElement('tr');const td=document.createElement('td');td.colSpan=5;td.className='muted';td.textContent='Internal transfer coverage resolves every current shortage.';tr.append(td);buyHost.append(tr);}$('purchaseQueueCount').textContent=purchaseQueue.length+' SKUs to buy';$('purchaseQueueQty').textContent=fmt(purchaseQueue.reduce((n,x)=>n+x.quantity,0))+' pieces remaining';
  const recHost=$('transferFirstRows');recHost.replaceChildren();const recs=recommendations.filter(x=>!term||[x.sku,x.product,x.from,x.to].join(' ').toLowerCase().includes(term));recs.forEach(x=>{const tr=document.createElement('tr');[x.sku,x.product,x.from,x.to,fmt(x.quantity)].forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.append(td)});recHost.append(tr);});if(!recs.length){const tr=document.createElement('tr');const td=document.createElement('td');td.colSpan=5;td.className='muted';td.textContent='No internal transfer opportunity found for the current shortage queue.';tr.append(td);recHost.append(tr);}$('transferFirstCount').textContent=recs.length+' suggested moves';
 }
 async function load(){
  set('Loading V2 shortages…');const r=await fetch('/api/replenishment',{credentials:'same-origin',cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to load replenishment');
  all=d.items||[];recommendations=d.recommendations||[];renderBoard(d.board||[]);const s=$('replenishmentLocation');s.replaceChildren();const o=document.createElement('option');o.value='';o.textContent='All warehouses';s.append(o);(d.locations||[]).forEach(x=>{const o=document.createElement('option');o.value=x.id;o.textContent=x.name;s.append(o);});
  const total=all.reduce((n,x)=>n+x.shortage,0);set(all.length+' shortage SKUs · '+fmt(total)+' total pieces required. These are V2 replenishment signals only.');render();
 }
 $('replenishmentNav').addEventListener('click',()=>{['overviewView','inventoryView','snapshotView','transferView','receivingView','productionView','productSyncView'].forEach(id=>{const el=$(id);if(el)el.hidden=true;});view.hidden=false;document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.id==='replenishmentNav'));load().catch(e=>set(e.message,true));});
 ['overviewNav','inventoryNav','productSyncNav','snapshotNav','transfersNav','receivingNav','productionNav'].forEach(id=>$(id)?.addEventListener('click',()=>view.hidden=true));
 $('replenishmentRefresh').addEventListener('click',()=>load().catch(e=>set(e.message,true)));
 $('replenishmentSearch').addEventListener('input',render);$('replenishmentLocation').addEventListener('change',render);
})();