(() => {
  const $=id=>document.getElementById(id);
  let vendors=[];
  const req=async (path='/api/vendors',options={})=>{const r=await fetch(path,{headers:{'Content-Type':'application/json'},...options});const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw Error(d.error||'Supplier request failed');return d;};
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function render(){const term=$('supplierSearch').value.trim().toLowerCase(), host=$('supplierRows');host.replaceChildren();const list=vendors.filter(v=>!term||[v.name,v.code,v.contact_person,v.email,v.phone].filter(Boolean).some(x=>String(x).toLowerCase().includes(term)));list.forEach(v=>{const tr=document.createElement('tr');tr.innerHTML='<td><strong>'+esc(v.name)+'</strong></td><td>'+esc(v.contact_person||'—')+'</td><td>'+esc(v.phone||'—')+'</td><td>'+esc(v.email||'—')+'</td><td>'+esc(v.payment_term_name||'—')+'</td><td>'+esc(v.active?'Active':'Inactive')+'</td>';host.append(tr)});$('supplierCount').textContent='Showing '+list.length+' of '+vendors.length+' suppliers';}
  async function load(){const data=await req();vendors=data.vendors||[];render();$('suppliersStatus').textContent=vendors.length+' suppliers loaded.';}
  function parseCsv(text){const rows=[];let row=[],cell='',quote=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c=='"'){if(quote&&n=='"'){cell+='"';i++;}else quote=!quote;}else if(c===','&&!quote){row.push(cell.trim());cell='';}else if((c==='\n'||c==='\r')&&!quote){if(c==='\r'&&n==='\n')i++;row.push(cell.trim());if(row.some(Boolean))rows.push(row);row=[];cell='';}else cell+=c;}row.push(cell.trim());if(row.some(Boolean))rows.push(row);const headers=rows.shift().map(h=>h.toLowerCase());return rows.map(values=>Object.fromEntries(headers.map((h,i)=>[h,values[i]||''])));}
  function mapCsv(row){const get=(...keys)=>keys.map(k=>row[k.toLowerCase()]).find(Boolean)||'';return {name:get('company name','name','supplier'),contact_person:get('contact person','contact'),phone:get('phone number','phone'),email:get('email'),vendor_type:get('wholesale or retail','type'),tax_number:get('tax number'),payment_term_name:get('payment term name','payment terms'),website:get('website'),shipping_address_line1:get('shipping address line1','address line1'),shipping_address_line2:get('shipping address line2','address line2'),shipping_address_city:get('shipping address city','city'),shipping_address_state:get('shipping address state','state'),shipping_address_zipcode:get('shipping address zipcode','zip','zipcode'),shipping_address_phone_number:get('shipping address phone number'),shipping_address_mobile_number:get('shipping address mobile number'),shipping_address_country:get('shipping address country','country')};}
  $('vendorDirectoryNav').onclick=()=>{document.querySelectorAll('main > section').forEach(s=>s.hidden=true);$('vendorDirectoryView').hidden=false;load().catch(e=>$('suppliersStatus').textContent=e.message);};
  $('supplierSearch').oninput=render;$('supplierRefresh').onclick=()=>load().catch(e=>$('suppliersStatus').textContent=e.message);
  $('supplierSave').onclick=async()=>{try{const vendor=Object.fromEntries(new FormData($('supplierForm')).entries());await req('/api/vendors',{method:'POST',body:JSON.stringify({action:'save',vendor})});$('supplierForm').reset();await load();$('suppliersStatus').textContent='Supplier saved.';}catch(e){$('suppliersStatus').textContent=e.message;}};
  $('supplierCsv').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;const rows=parseCsv(await file.text()).map(mapCsv).filter(v=>v.name);if(!rows.length)throw Error('No supplier rows found in that CSV.');await req('/api/vendors',{method:'POST',body:JSON.stringify({action:'import',vendors:rows})});await load();$('suppliersStatus').textContent=rows.length+' suppliers imported.';}catch(err){$('suppliersStatus').textContent=err.message;}finally{e.target.value='';}};
})();