create table if not exists public.production_work_orders (
 id bigint generated by default as identity primary key, work_order_number text not null unique, bom_id bigint not null references public.product_boms(id), production_location_id bigint not null references public.locations(id), destination_location_id bigint not null references public.locations(id), output_quantity numeric not null check (output_quantity > 0), reference text, idempotency_key text not null unique, status text not null check (status in ('allocated','completed','cancelled')), transfer_id bigint references public.transfers(id), created_by_user_id bigint, created_by_name text, started_at timestamptz not null default now(), completed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index if not exists production_work_orders_status_idx on public.production_work_orders(status, production_location_id);
create table if not exists public.production_work_order_lines (
 id bigint generated by default as identity primary key, work_order_id bigint not null references public.production_work_orders(id) on delete cascade, product_id bigint not null references public.products(id), allocated_quantity numeric not null check (allocated_quantity > 0), consumed_quantity numeric not null default 0 check (consumed_quantity >= 0), unique (work_order_id, product_id));
alter table public.production_work_orders enable row level security;
alter table public.production_work_order_lines enable row level security;

CREATE OR REPLACE FUNCTION public.start_v2_production_work_order(p_bom_id bigint, p_destination_location_id bigint, p_output_quantity numeric, p_reference text, p_idempotency_key text, p_user_id bigint, p_user_name text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'pg_catalog', 'public'
AS $function$
declare
  v_bom public.product_boms%rowtype;
  v_component record;
  v_location_id bigint;
  v_work_order_id bigint;
  v_number text;
  v_needed numeric;
  v_before numeric;
  v_allocated numeric;
begin
  if p_output_quantity is null or p_output_quantity <= 0 then raise exception 'output quantity must be greater than zero'; end if;
  if p_destination_location_id is null then raise exception 'final destination is required'; end if;
  if nullif(trim(coalesce(p_idempotency_key,'')),'') is null then raise exception 'idempotency key is required'; end if;
  select id into v_location_id from public.locations where active and code = '730' order by id limit 1;
  if v_location_id is null then raise exception '730 Windham production location is not configured'; end if;
  if p_destination_location_id = v_location_id then raise exception 'choose a destination other than 730 Windham Rd'; end if;
  select * into v_bom from public.product_boms where id = p_bom_id and active for update;
  if not found then raise exception 'active BOM not found'; end if;
  select id, work_order_number into v_work_order_id, v_number from public.production_work_orders where idempotency_key = p_idempotency_key;
  if found then return jsonb_build_object('alreadyStarted',true,'workOrderId',v_work_order_id,'workOrderNumber',v_number); end if;
  if not exists (select 1 from public.product_bom_components where bom_id = v_bom.id) then raise exception 'BOM needs at least one component'; end if;
  insert into public.production_work_orders(work_order_number,bom_id,production_location_id,destination_location_id,output_quantity,reference,idempotency_key,status,created_by_user_id,created_by_name)
  values ('WO-'||to_char(clock_timestamp(),'YYYYMMDD-HH24MISSMS'),v_bom.id,v_location_id,p_destination_location_id,p_output_quantity,nullif(trim(p_reference),''),p_idempotency_key,'allocated',p_user_id,p_user_name)
  returning id, work_order_number into v_work_order_id, v_number;
  for v_component in
    select c.component_product_id,c.quantity_per_yield,p.sku
    from public.product_bom_components c join public.products p on p.id=c.component_product_id
    where c.bom_id=v_bom.id and p.active
    order by c.component_product_id
  loop
    v_needed := p_output_quantity * v_component.quantity_per_yield / v_bom.yield_quantity;
    insert into public.inventory_balances(product_id,location_id,quantity,allocated_quantity)
      values(v_component.component_product_id,v_location_id,0,0)
      on conflict(product_id,location_id) do nothing;
    select quantity, allocated_quantity into v_before, v_allocated
      from public.inventory_balances
      where product_id=v_component.component_product_id and location_id=v_location_id
      for update;
    update public.inventory_balances
      set allocated_quantity=v_allocated+v_needed, updated_at=now()
      where product_id=v_component.component_product_id and location_id=v_location_id;
    insert into public.production_work_order_lines(work_order_id,product_id,allocated_quantity)
      values(v_work_order_id,v_component.component_product_id,v_needed);
    insert into public.inventory_movements(product_id,location_id,movement_type,quantity_delta,quantity_before,quantity_after,reference_type,reference_id,reason,idempotency_key,performed_by_user_id,performed_by_name,metadata)
      values(v_component.component_product_id,v_location_id,'production_allocate',0,v_before,v_before,'production_work_order',v_number,'Component reserved for production',p_idempotency_key||':allocate:'||v_component.component_product_id,p_user_id,p_user_name,jsonb_build_object('workOrderId',v_work_order_id,'destinationLocationId',p_destination_location_id));
  end loop;
  insert into public.activity_events(user_id,user_name,action_type,document_type,document_number,description,status,metadata)
    values(p_user_id,coalesce(nullif(trim(p_user_name),''),'Warehouse user'),'PRODUCTION_ALLOCATED','production',v_number,'Reserved 730 components for production','success',jsonb_build_object('workOrderId',v_work_order_id,'productionLocationId',v_location_id,'destinationLocationId',p_destination_location_id,'quantity',p_output_quantity));
  return jsonb_build_object('alreadyStarted',false,'workOrderId',v_work_order_id,'workOrderNumber',v_number,'productionLocationId',v_location_id);
end $function$


CREATE OR REPLACE FUNCTION public.complete_v2_production_work_order(p_work_order_id bigint, p_user_id bigint, p_user_name text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'pg_catalog', 'public'
AS $function$
declare
  v_work public.production_work_orders%rowtype;
  v_bom public.product_boms%rowtype;
  v_finished public.products%rowtype;
  v_line record;
  v_before numeric;
  v_allocated numeric;
  v_output_before numeric;
  v_transfer_id bigint;
  v_transfer_number text;
begin
  select * into v_work from public.production_work_orders where id=p_work_order_id for update;
  if not found then raise exception 'work order not found'; end if;
  if v_work.status='completed' then return jsonb_build_object('alreadyCompleted',true,'workOrderId',v_work.id,'transferId',v_work.transfer_id); end if;
  if v_work.status <> 'allocated' then raise exception 'work order is not ready to complete'; end if;
  select * into v_bom from public.product_boms where id=v_work.bom_id for update;
  select * into v_finished from public.products where id=v_bom.finished_product_id and active=true;
  if not found then raise exception 'finished product not found'; end if;
  for v_line in select * from public.production_work_order_lines where work_order_id=v_work.id order by product_id loop
    select quantity,allocated_quantity into v_before,v_allocated from public.inventory_balances where product_id=v_line.product_id and location_id=v_work.production_location_id for update;
    if v_allocated < v_line.allocated_quantity then raise exception 'component allocation changed; review work order'; end if;
    update public.inventory_balances
      set quantity=v_before-v_line.allocated_quantity,
          allocated_quantity=v_allocated-v_line.allocated_quantity,
          updated_at=now()
      where product_id=v_line.product_id and location_id=v_work.production_location_id;
    update public.production_work_order_lines set consumed_quantity=allocated_quantity where id=v_line.id;
    insert into public.inventory_movements(product_id,location_id,movement_type,quantity_delta,quantity_before,quantity_after,reference_type,reference_id,reason,idempotency_key,performed_by_user_id,performed_by_name,metadata)
      values(v_line.product_id,v_work.production_location_id,'production_consume',-v_line.allocated_quantity,v_before,v_before-v_line.allocated_quantity,'production_work_order',v_work.work_order_number,'Production component consumed',v_work.idempotency_key||':consume:'||v_line.product_id,p_user_id,p_user_name,jsonb_build_object('workOrderId',v_work.id));
  end loop;
  insert into public.inventory_balances(product_id,location_id,quantity,allocated_quantity)
    values(v_finished.id,v_work.production_location_id,0,0)
    on conflict(product_id,location_id) do nothing;
  select quantity into v_output_before from public.inventory_balances where product_id=v_finished.id and location_id=v_work.production_location_id for update;
  update public.inventory_balances set quantity=v_output_before+v_work.output_quantity,updated_at=now() where product_id=v_finished.id and location_id=v_work.production_location_id;
  insert into public.inventory_movements(product_id,location_id,movement_type,quantity_delta,quantity_before,quantity_after,reference_type,reference_id,reason,idempotency_key,performed_by_user_id,performed_by_name,metadata)
    values(v_finished.id,v_work.production_location_id,'production_complete',v_work.output_quantity,v_output_before,v_output_before+v_work.output_quantity,'production_work_order',v_work.work_order_number,'Finished goods completed at 730',v_work.idempotency_key||':complete',p_user_id,p_user_name,jsonb_build_object('workOrderId',v_work.id));
  insert into public.transfers(transfer_number,from_location_id,to_location_id,status,created_by_user_id,created_by_name)
    values('TR-'||to_char(clock_timestamp(),'YYYYMMDD-HH24MISSMS'),v_work.production_location_id,v_work.destination_location_id,'allocated',p_user_id,p_user_name)
    returning id,transfer_number into v_transfer_id,v_transfer_number;
  insert into public.transfer_lines(transfer_id,product_id,requested_quantity,allocated_quantity)
    values(v_transfer_id,v_finished.id,v_work.output_quantity,v_work.output_quantity);
  update public.inventory_balances
    set allocated_quantity=allocated_quantity+v_work.output_quantity,updated_at=now()
    where product_id=v_finished.id and location_id=v_work.production_location_id;
  update public.production_work_orders set status='completed',transfer_id=v_transfer_id,completed_at=now(),updated_at=now() where id=v_work.id;
  insert into public.activity_events(user_id,user_name,action_type,document_type,document_number,description,status,metadata)
    values(p_user_id,coalesce(nullif(trim(p_user_name),''),'Warehouse user'),'PRODUCTION_COMPLETED','production',v_work.work_order_number,'Completed production and allocated transfer '||v_transfer_number,'success',jsonb_build_object('workOrderId',v_work.id,'transferId',v_transfer_id,'transferNumber',v_transfer_number,'productionLocationId',v_work.production_location_id,'destinationLocationId',v_work.destination_location_id,'quantity',v_work.output_quantity));
  return jsonb_build_object('alreadyCompleted',false,'workOrderId',v_work.id,'workOrderNumber',v_work.work_order_number,'transferId',v_transfer_id,'transferNumber',v_transfer_number,'status','allocated');
end $function$


revoke all on function public.start_v2_production_work_order(bigint,bigint,numeric,text,text,bigint,text) from public, anon, authenticated;
revoke all on function public.complete_v2_production_work_order(bigint,bigint,text) from public, anon, authenticated;
grant execute on function public.start_v2_production_work_order(bigint,bigint,numeric,text,text,bigint,text) to service_role;
grant execute on function public.complete_v2_production_work_order(bigint,bigint,text) to service_role;