-- Durable Shopify-first purchase-order receipt attempts.
-- A retry reuses the same Shopify idempotency key and never applies a second inventory increment.

create table if not exists public.purchase_order_receipt_attempts (
  id bigint generated by default as identity primary key,
  purchase_order_id bigint not null references public.purchase_orders(id) on delete cascade,
  receiving_location_id bigint not null references public.locations(id),
  line_signature text not null,
  receipt_lines jsonb not null,
  idempotency_key text not null unique,
  status text not null default 'pending' check (status in ('pending','shopify_confirmed','applied')),
  shopify_adjustment_id text,
  created_by_user_id uuid,
  created_by_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  applied_at timestamptz
);

create unique index if not exists purchase_order_receipt_attempts_active_signature_idx
  on public.purchase_order_receipt_attempts (purchase_order_id, line_signature)
  where status in ('pending','shopify_confirmed');

create index if not exists purchase_order_receipt_attempts_order_idx
  on public.purchase_order_receipt_attempts (purchase_order_id, created_at desc);

create or replace function public.begin_v2_purchase_order_receipt(
  p_purchase_order_id bigint,
  p_receiving_location_id bigint,
  p_lines jsonb,
  p_user_id uuid default null,
  p_user_name text default null
) returns jsonb language plpgsql security definer set search_path = public as $$
declare
  v_signature text;
  v_attempt public.purchase_order_receipt_attempts%rowtype;
begin
  if jsonb_typeof(p_lines) <> 'array' or jsonb_array_length(p_lines) = 0 then
    raise exception 'Receipt lines are required.';
  end if;

  select string_agg(format('%s:%s', item->>'lineId', item->>'quantity'), ',' order by (item->>'lineId')::bigint)
    into v_signature
  from jsonb_array_elements(p_lines) item;

  select * into v_attempt
  from public.purchase_order_receipt_attempts
  where purchase_order_id = p_purchase_order_id
    and line_signature = v_signature
    and status in ('pending','shopify_confirmed')
  order by id desc
  limit 1
  for update;

  if found then
    return jsonb_build_object(
      'attemptId', v_attempt.id,
      'idempotencyKey', v_attempt.idempotency_key,
      'status', v_attempt.status,
      'shopifyAdjustmentId', v_attempt.shopify_adjustment_id,
      'reused', true
    );
  end if;

  insert into public.purchase_order_receipt_attempts (
    purchase_order_id, receiving_location_id, line_signature, receipt_lines,
    idempotency_key, created_by_user_id, created_by_name
  ) values (
    p_purchase_order_id, p_receiving_location_id, v_signature, p_lines,
    gen_random_uuid()::text, p_user_id, p_user_name
  ) returning * into v_attempt;

  return jsonb_build_object(
    'attemptId', v_attempt.id,
    'idempotencyKey', v_attempt.idempotency_key,
    'status', v_attempt.status,
    'shopifyAdjustmentId', null,
    'reused', false
  );
end;
$$;

create or replace function public.confirm_v2_purchase_order_receipt_shopify(
  p_attempt_id bigint,
  p_shopify_adjustment_id text
) returns void language plpgsql security definer set search_path = public as $$
begin
  update public.purchase_order_receipt_attempts
  set status = 'shopify_confirmed',
      shopify_adjustment_id = p_shopify_adjustment_id,
      updated_at = now()
  where id = p_attempt_id
    and status in ('pending','shopify_confirmed');

  if not found then raise exception 'Receipt attempt not found.'; end if;
end;
$$;

create or replace function public.complete_v2_purchase_order_receipt(
  p_attempt_id bigint
) returns void language plpgsql security definer set search_path = public as $$
begin
  update public.purchase_order_receipt_attempts
  set status = 'applied',
      applied_at = now(),
      updated_at = now()
  where id = p_attempt_id
    and status in ('pending','shopify_confirmed');

  if not found then raise exception 'Receipt attempt not found.'; end if;
end;
$$;

revoke all on function public.begin_v2_purchase_order_receipt(bigint,bigint,jsonb,uuid,text) from public;
revoke all on function public.confirm_v2_purchase_order_receipt_shopify(bigint,text) from public;
revoke all on function public.complete_v2_purchase_order_receipt(bigint) from public;
grant execute on function public.begin_v2_purchase_order_receipt(bigint,bigint,jsonb,uuid,text) to service_role;
grant execute on function public.confirm_v2_purchase_order_receipt_shopify(bigint,text) to service_role;
grant execute on function public.complete_v2_purchase_order_receipt(bigint) to service_role;
