-- 730 Windham Rd is the procurement hub. Purchases land there before MT transfers feed retail.
create table if not exists public.purchase_orders (
  id bigint generated by default as identity primary key,
  purchase_order_number text not null unique,
  vendor_name text,
  receiving_location_id bigint not null references public.locations(id) on delete restrict,
  status text not null default 'draft' check (status in ('draft', 'ordered', 'partially_received', 'received', 'cancelled')),
  notes text,
  created_by_user_id bigint references public.app_users(id) on delete set null,
  created_by_name text,
  ordered_at timestamptz,
  received_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.purchase_order_lines (
  id bigint generated by default as identity primary key,
  purchase_order_id bigint not null references public.purchase_orders(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete restrict,
  ordered_quantity numeric not null check (ordered_quantity > 0),
  received_quantity numeric not null default 0 check (received_quantity >= 0 and received_quantity <= ordered_quantity),
  notes text,
  unique (purchase_order_id, product_id)
);
create index if not exists purchase_orders_status_idx on public.purchase_orders(status, created_at desc);
create index if not exists purchase_order_lines_order_idx on public.purchase_order_lines(purchase_order_id);
alter table public.purchase_orders enable row level security;
alter table public.purchase_order_lines enable row level security;

create or replace function public.create_v2_purchase_order(
  p_vendor_name text, p_receiving_location_id bigint, p_lines jsonb, p_notes text,
  p_idempotency_key text, p_user_id bigint, p_user_name text
) returns jsonb language plpgsql set search_path to 'pg_catalog', 'public' as $$
declare v_order_id bigint; v_number text; v_line jsonb; v_product_id bigint; v_quantity numeric; v_count integer := 0;
begin
  if nullif(trim(coalesce(p_idempotency_key, '')), '') is null then raise exception 'purchase order idempotency key is required'; end if;
  if jsonb_typeof(p_lines) <> 'array' or jsonb_array_length(p_lines) = 0 then raise exception 'Select at least one item'; end if;
  select (metadata->>'purchaseOrderId')::bigint into v_order_id from public.activity_events where document_type = 'purchase_order' and metadata->>'idempotencyKey' = p_idempotency_key order by id desc limit 1;
  if v_order_id is not null then select purchase_order_number into v_number from public.purchase_orders where id = v_order_id; return jsonb_build_object('alreadyCreated', true, 'id', v_order_id, 'purchaseOrderNumber', v_number); end if;
  v_number := 'PO-' || to_char(clock_timestamp(), 'YYYYMMDD-HH24MISSMS');
  insert into public.purchase_orders(purchase_order_number, vendor_name, receiving_location_id, status, notes, created_by_user_id, created_by_name)
  values (v_number, nullif(trim(coalesce(p_vendor_name, '')), ''), p_receiving_location_id, 'draft', trim(coalesce(p_notes, '')) || case when trim(coalesce(p_notes, '')) <> '' then ' ' else '' end || '[' || p_idempotency_key || ']', p_user_id, p_user_name) returning id into v_order_id;
  for v_line in select value from jsonb_array_elements(p_lines) loop
    v_product_id := (v_line->>'productId')::bigint; v_quantity := (v_line->>'quantity')::numeric;
    if v_quantity is null or v_quantity <= 0 then raise exception 'Purchase quantities must be positive'; end if;
    perform 1 from public.products where id = v_product_id and active = true; if not found then raise exception 'Selected product is not active'; end if;
    insert into public.purchase_order_lines(purchase_order_id, product_id, ordered_quantity, notes) values (v_order_id, v_product_id, v_quantity, nullif(trim(coalesce(v_line->>'note', '')), ''));
    v_count := v_count + 1;
  end loop;
  insert into public.activity_events(user_id, user_name, action_type, document_type, document_number, description, status, metadata)
  values (p_user_id, p_user_name, 'PURCHASE_ORDER_CREATED', 'purchase_order', v_number, 'Created draft purchase order for 730 receiving', 'success', jsonb_build_object('purchaseOrderId', v_order_id, 'lineCount', v_count, 'receivingLocationId', p_receiving_location_id, 'idempotencyKey', p_idempotency_key));
  return jsonb_build_object('alreadyCreated', false, 'id', v_order_id, 'purchaseOrderNumber', v_number, 'status', 'draft');
end $$;

create or replace function public.receive_v2_purchase_order(p_purchase_order_id bigint, p_user_id bigint, p_user_name text)
returns jsonb language plpgsql set search_path to 'pg_catalog', 'public' as $$
declare v_order public.purchase_orders%rowtype; v_line record; v_before numeric; v_receive numeric; v_remaining integer;
begin
  select * into v_order from public.purchase_orders where id = p_purchase_order_id for update;
  if not found then raise exception 'purchase order not found'; end if;
  if v_order.status in ('received', 'cancelled') then return jsonb_build_object('alreadyReceived', v_order.status = 'received', 'purchaseOrderNumber', v_order.purchase_order_number); end if;
  for v_line in select * from public.purchase_order_lines where purchase_order_id = v_order.id order by id loop
    v_receive := v_line.ordered_quantity - v_line.received_quantity; if v_receive <= 0 then continue; end if;
    insert into public.inventory_balances(product_id, location_id, quantity, allocated_quantity) values (v_line.product_id, v_order.receiving_location_id, 0, 0) on conflict(product_id, location_id) do nothing;
    select quantity into v_before from public.inventory_balances where product_id = v_line.product_id and location_id = v_order.receiving_location_id for update;
    update public.inventory_balances set quantity = v_before + v_receive, updated_at = now() where product_id = v_line.product_id and location_id = v_order.receiving_location_id;
    update public.purchase_order_lines set received_quantity = received_quantity + v_receive where id = v_line.id;
    insert into public.inventory_movements(product_id, location_id, movement_type, quantity_delta, quantity_before, quantity_after, reference_type, reference_id, reason, idempotency_key, performed_by_user_id, performed_by_name, metadata)
    values (v_line.product_id, v_order.receiving_location_id, 'purchase_receipt', v_receive, v_before, v_before + v_receive, 'purchase_order', v_order.purchase_order_number, 'Purchase order receipt', 'po:' || v_order.id || ':receive:' || v_line.id, p_user_id, p_user_name, jsonb_build_object('purchaseOrderId', v_order.id));
  end loop;
  select count(*) into v_remaining from public.purchase_order_lines where purchase_order_id = v_order.id and received_quantity < ordered_quantity;
  update public.purchase_orders set status = case when v_remaining = 0 then 'received' else 'partially_received' end, received_at = case when v_remaining = 0 then now() else received_at end, updated_at = now() where id = v_order.id returning * into v_order;
  insert into public.activity_events(user_id, user_name, action_type, document_type, document_number, description, status, metadata)
  values (p_user_id, p_user_name, 'PURCHASE_ORDER_RECEIVED', 'purchase_order', v_order.purchase_order_number, 'Received purchase order into 730', 'success', jsonb_build_object('purchaseOrderId', v_order.id, 'receivingLocationId', v_order.receiving_location_id));
  return jsonb_build_object('alreadyReceived', false, 'purchaseOrderNumber', v_order.purchase_order_number, 'status', v_order.status);
end $$;

revoke all on function public.create_v2_purchase_order(text, bigint, jsonb, text, text, bigint, text) from public, anon, authenticated;
revoke all on function public.receive_v2_purchase_order(bigint, bigint, text) from public, anon, authenticated;
grant execute on function public.create_v2_purchase_order(text, bigint, jsonb, text, text, bigint, text) to service_role;
grant execute on function public.receive_v2_purchase_order(bigint, bigint, text) to service_role;
