-- Shopify paid-order webhook bridge for BM Warehouse V2.
-- A verified Shopify ORDERS_PAID event reduces only its mapped V2 warehouse balance.
-- Shopify and Qoblex are never written by this migration.

begin;

create table if not exists public.shopify_location_mappings (
  id bigint generated by default as identity primary key,
  store_key text not null check (store_key in ('store_1', 'store_2')),
  shopify_location_id text not null,
  shopify_location_name text not null,
  location_id bigint not null references public.locations(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (store_key, shopify_location_id)
);

create table if not exists public.shopify_webhook_events (
  id bigint generated by default as identity primary key,
  store_key text not null check (store_key in ('store_1', 'store_2')),
  topic text not null,
  webhook_id text not null,
  shopify_order_id text,
  shopify_order_number text,
  shopify_location_id text,
  status text not null default 'received'
    check (status in ('received', 'processed', 'needs_mapping', 'needs_review', 'ignored', 'failed')),
  processed_lines integer not null default 0,
  skipped_lines integer not null default 0,
  error text,
  summary jsonb not null default '{}'::jsonb,
  received_at timestamptz not null default now(),
  processed_at timestamptz,
  unique (store_key, webhook_id)
);

create index if not exists shopify_location_mappings_location_idx
  on public.shopify_location_mappings(location_id);
create index if not exists shopify_webhook_events_status_received_idx
  on public.shopify_webhook_events(status, received_at desc);
create index if not exists shopify_webhook_events_order_idx
  on public.shopify_webhook_events(store_key, shopify_order_id);

alter table public.shopify_location_mappings enable row level security;
alter table public.shopify_webhook_events enable row level security;
revoke all on public.shopify_location_mappings, public.shopify_webhook_events from anon, authenticated;
grant select, insert, update, delete on public.shopify_location_mappings, public.shopify_webhook_events to service_role;

create or replace function public.apply_v2_shopify_paid_order(
  p_store_key text,
  p_webhook_id text,
  p_order_id text,
  p_order_number text,
  p_shopify_location_id text,
  p_lines jsonb
)
returns jsonb
language plpgsql
security invoker
set search_path = pg_catalog, public
as $$
declare
  v_event_id bigint;
  v_location_id bigint;
  v_location_name text;
  v_line jsonb;
  v_line_index integer := 0;
  v_sku text;
  v_quantity numeric;
  v_product_id bigint;
  v_product_count integer;
  v_cost numeric;
  v_before numeric;
  v_after numeric;
  v_allocated numeric;
  v_idempotency_key text;
  v_processed integer := 0;
  v_skipped integer := 0;
  v_duplicate integer := 0;
  v_issues jsonb := '[]'::jsonb;
  v_status text;
begin
  if p_store_key not in ('store_1', 'store_2') then
    raise exception 'unknown Shopify store';
  end if;
  if nullif(btrim(coalesce(p_webhook_id, '')), '') is null then
    raise exception 'Shopify webhook id is required';
  end if;
  if nullif(btrim(coalesce(p_order_id, '')), '') is null then
    raise exception 'Shopify order id is required';
  end if;

  insert into public.shopify_webhook_events(
    store_key, topic, webhook_id, shopify_order_id, shopify_order_number, shopify_location_id
  ) values (
    p_store_key, 'orders/paid', p_webhook_id, p_order_id, nullif(btrim(coalesce(p_order_number, '')), ''),
    nullif(btrim(coalesce(p_shopify_location_id, '')), '')
  )
  on conflict (store_key, webhook_id) do nothing
  returning id into v_event_id;

  if v_event_id is null then
    return jsonb_build_object('duplicate', true, 'processedLines', 0, 'skippedLines', 0);
  end if;

  select m.location_id, l.name
    into v_location_id, v_location_name
  from public.shopify_location_mappings m
  join public.locations l on l.id = m.location_id and l.active = true
  where m.store_key = p_store_key
    and m.shopify_location_id = nullif(btrim(coalesce(p_shopify_location_id, '')), '')
  limit 1;

  if v_location_id is null then
    update public.shopify_webhook_events
    set status = 'needs_mapping',
        error = case
          when nullif(btrim(coalesce(p_shopify_location_id, '')), '') is null
            then 'Shopify order did not include a sale location.'
          else 'Shopify sale location is not mapped to a V2 warehouse.'
        end,
        processed_at = now()
    where id = v_event_id;

    insert into public.activity_events(
      user_name, action_type, document_type, document_number, description, status, metadata
    ) values (
      'Shopify webhook', 'SHOPIFY_SALE_NEEDS_MAPPING', 'sales_order', p_order_number,
      'Shopify sale was received but not deducted because its sale location is not mapped in V2.',
      'warning',
      jsonb_build_object('storeKey', p_store_key, 'orderId', p_order_id, 'shopifyLocationId', p_shopify_location_id)
    );

    return jsonb_build_object('duplicate', false, 'status', 'needs_mapping', 'processedLines', 0, 'skippedLines', 0);
  end if;

  for v_line in select value from jsonb_array_elements(coalesce(p_lines, '[]'::jsonb))
  loop
    v_line_index := v_line_index + 1;
    v_sku := nullif(btrim(coalesce(v_line->>'sku', '')), '');
    v_quantity := case when coalesce(v_line->>'quantity', '') ~ '^[0-9]+(\\.[0-9]+)?$'
      then (v_line->>'quantity')::numeric else 0 end;
    v_idempotency_key := 'shopify_sale:' || p_store_key || ':' || p_order_id || ':' ||
      coalesce(nullif(btrim(coalesce(v_line->>'id', '')), ''), v_line_index::text);

    if v_sku is null or v_quantity <= 0 then
      v_skipped := v_skipped + 1;
      v_issues := v_issues || jsonb_build_array(jsonb_build_object('line', v_line_index, 'reason', 'missing SKU or quantity', 'sku', v_sku));
      continue;
    end if;

    if exists (select 1 from public.inventory_movements where idempotency_key = v_idempotency_key) then
      v_duplicate := v_duplicate + 1;
      continue;
    end if;

    select count(*), min(id)
      into v_product_count, v_product_id
    from public.products
    where active = true and upper(btrim(sku)) = upper(v_sku);

    if v_product_count <> 1 then
      v_skipped := v_skipped + 1;
      v_issues := v_issues || jsonb_build_array(jsonb_build_object('line', v_line_index, 'reason', 'SKU is not uniquely matched in V2', 'sku', v_sku));
      continue;
    end if;

    select moving_average_cost into v_cost from public.products where id = v_product_id;
    insert into public.inventory_balances(product_id, location_id, quantity, allocated_quantity)
      values (v_product_id, v_location_id, 0, 0)
      on conflict (product_id, location_id) do nothing;

    select quantity, allocated_quantity into v_before, v_allocated
    from public.inventory_balances
    where product_id = v_product_id and location_id = v_location_id
    for update;

    v_after := v_before - v_quantity;
    if v_after < v_allocated then
      v_skipped := v_skipped + 1;
      v_issues := v_issues || jsonb_build_array(jsonb_build_object(
        'line', v_line_index, 'reason', 'sale would reduce on hand below allocated quantity',
        'sku', v_sku, 'onHand', v_before, 'allocated', v_allocated, 'saleQuantity', v_quantity
      ));
      continue;
    end if;

    update public.inventory_balances
    set quantity = v_after, updated_at = now()
    where product_id = v_product_id and location_id = v_location_id;

    insert into public.inventory_movements(
      product_id, location_id, movement_type, quantity_delta, quantity_before, quantity_after,
      unit_cost, reference_type, reference_id, reason, idempotency_key,
      performed_by_name, metadata
    ) values (
      v_product_id, v_location_id, 'shopify_sale', -v_quantity, v_before, v_after,
      v_cost, 'sales_order', p_order_id,
      'Shopify paid order ' || coalesce(nullif(btrim(coalesce(p_order_number, '')), ''), p_order_id),
      v_idempotency_key, 'Shopify webhook',
      jsonb_build_object(
        'storeKey', p_store_key, 'orderId', p_order_id, 'orderNumber', p_order_number,
        'shopifyLocationId', p_shopify_location_id, 'shopifyLineId', v_line->>'id', 'sku', v_sku
      )
    );
    v_processed := v_processed + 1;
  end loop;

  v_status := case when v_skipped > 0 then 'needs_review' else 'processed' end;
  update public.shopify_webhook_events
  set status = v_status,
      processed_lines = v_processed,
      skipped_lines = v_skipped,
      summary = jsonb_build_object('duplicates', v_duplicate, 'issues', v_issues, 'locationId', v_location_id),
      processed_at = now()
  where id = v_event_id;

  insert into public.activity_events(
    user_name, action_type, document_type, document_number, warehouse_id, description, status, metadata
  ) values (
    'Shopify webhook',
    case when v_status = 'processed' then 'SHOPIFY_SALE_DEDUCTED' else 'SHOPIFY_SALE_NEEDS_REVIEW' end,
    'sales_order', p_order_number, null,
    'Processed Shopify paid order ' || coalesce(nullif(btrim(coalesce(p_order_number, '')), ''), p_order_id) ||
      ': deducted ' || v_processed || ' line(s)' ||
      case when v_skipped > 0 then ', ' || v_skipped || ' line(s) need review' else '' end || '.',
    case when v_status = 'processed' then 'success' else 'warning' end,
    jsonb_build_object(
      'storeKey', p_store_key, 'orderId', p_order_id, 'locationId', v_location_id,
      'locationName', v_location_name, 'processedLines', v_processed, 'skippedLines', v_skipped,
      'duplicates', v_duplicate, 'issues', v_issues
    )
  );

  return jsonb_build_object(
    'duplicate', false, 'status', v_status, 'locationId', v_location_id,
    'processedLines', v_processed, 'skippedLines', v_skipped, 'duplicates', v_duplicate, 'issues', v_issues
  );
end;
$$;

revoke all on function public.apply_v2_shopify_paid_order(text, text, text, text, text, jsonb)
  from public, anon, authenticated;
grant execute on function public.apply_v2_shopify_paid_order(text, text, text, text, text, jsonb)
  to service_role;

commit;