-- Daily blind cycle counts. Counts do not alter inventory until a manager review
-- explicitly creates an inventory adjustment. Shopify and Qoblex are not changed.

create table if not exists public.cycle_count_runs (
  id bigint generated by default as identity primary key,
  location_id bigint not null references public.locations(id),
  business_date date not null,
  status text not null default 'open' check (status in ('open','ready_for_review','reviewed')),
  target_count integer not null default 5 check (target_count between 1 and 25),
  created_by_user_id bigint,
  created_by_name text,
  created_at timestamptz not null default now(),
  submitted_at timestamptz,
  reviewed_at timestamptz,
  reviewed_by_user_id bigint,
  reviewed_by_name text,
  unique (location_id, business_date)
);
create table if not exists public.cycle_count_lines (
  id bigint generated by default as identity primary key,
  run_id bigint not null references public.cycle_count_runs(id) on delete cascade,
  product_id bigint not null references public.products(id),
  expected_quantity numeric not null,
  counted_quantity numeric,
  status text not null default 'pending' check (status in ('pending','counted','variance')),
  counted_by_user_id bigint,
  counted_by_name text,
  counted_at timestamptz,
  note text,
  created_at timestamptz not null default now(),
  unique (run_id, product_id)
);
create index if not exists cycle_count_runs_location_date_idx on public.cycle_count_runs(location_id, business_date desc);
create index if not exists cycle_count_lines_run_idx on public.cycle_count_lines(run_id);
alter table public.cycle_count_runs enable row level security;
alter table public.cycle_count_lines enable row level security;
revoke all on public.cycle_count_runs, public.cycle_count_lines from anon, authenticated;
create or replace function public.open_v2_daily_cycle_count(p_location_id bigint,p_business_date date,p_target_count integer,p_user_id bigint,p_user_name text)
returns bigint language plpgsql security invoker set search_path = pg_catalog, public as $$
declare v_run_id bigint;
begin
  if p_location_id is null then raise exception 'warehouse is required'; end if;
  if p_business_date is null then raise exception 'business date is required'; end if;
  if p_target_count is null or p_target_count < 1 or p_target_count > 25 then raise exception 'target count must be between 1 and 25'; end if;
  insert into public.cycle_count_runs(location_id,business_date,target_count,created_by_user_id,created_by_name)
  values(p_location_id,p_business_date,p_target_count,p_user_id,nullif(trim(p_user_name),''))
  on conflict(location_id,business_date) do nothing returning id into v_run_id;
  if v_run_id is null then select id into v_run_id from public.cycle_count_runs where location_id=p_location_id and business_date=p_business_date; return v_run_id; end if;
  insert into public.cycle_count_lines(run_id,product_id,expected_quantity)
  select v_run_id, ranked.product_id, ranked.quantity from (
    select b.product_id,b.quantity,max(previous_run.business_date) as last_counted_date
    from public.inventory_balances b join public.products p on p.id=b.product_id and p.active=true
    left join public.cycle_count_lines previous_line on previous_line.product_id=b.product_id
    left join public.cycle_count_runs previous_run on previous_run.id=previous_line.run_id and previous_run.location_id=p_location_id and previous_run.status in ('ready_for_review','reviewed')
    where b.location_id=p_location_id and b.quantity<>0 group by b.product_id,b.quantity
    order by max(previous_run.business_date) asc nulls first,md5(b.product_id::text||p_business_date::text) limit p_target_count
  ) ranked;
  return v_run_id;
end; $$;
revoke all on function public.open_v2_daily_cycle_count(bigint,date,integer,bigint,text) from public,anon,authenticated;
grant execute on function public.open_v2_daily_cycle_count(bigint,date,integer,bigint,text) to service_role;