-- Warehouse-specific bin locations. A product may have a different bin at each warehouse.
create table if not exists public.inventory_bin_locations (
  id bigint generated by default as identity primary key,
  location_id bigint not null references public.locations(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  bin_code text not null check (length(btrim(bin_code)) > 0 and length(btrim(bin_code)) <= 80),
  note text,
  updated_at timestamptz not null default now(),
  updated_by_user_id uuid,
  updated_by_name text,
  unique (location_id, product_id)
);

create index if not exists inventory_bin_locations_location_bin_idx
  on public.inventory_bin_locations(location_id, bin_code);
create index if not exists inventory_bin_locations_product_idx
  on public.inventory_bin_locations(product_id);

create table if not exists public.inventory_bin_location_history (
  id bigint generated by default as identity primary key,
  location_id bigint not null references public.locations(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  previous_bin_code text,
  bin_code text not null,
  note text,
  changed_at timestamptz not null default now(),
  changed_by_user_id uuid,
  changed_by_name text
);

create index if not exists inventory_bin_location_history_location_product_changed_idx
  on public.inventory_bin_location_history(location_id, product_id, changed_at desc);

alter table public.inventory_bin_locations enable row level security;
alter table public.inventory_bin_location_history enable row level security;
revoke all on public.inventory_bin_locations from anon, authenticated;
revoke all on public.inventory_bin_location_history from anon, authenticated;
grant select, insert, update, delete on public.inventory_bin_locations to service_role;
grant select, insert on public.inventory_bin_location_history to service_role;

create or replace function public.set_v2_inventory_bin_location(
  p_location_id bigint,
  p_product_id bigint,
  p_bin_code text,
  p_note text default null,
  p_user_id uuid default null,
  p_user_name text default null
)
returns jsonb
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_previous text;
  v_bin text := upper(btrim(p_bin_code));
  v_note text := nullif(btrim(coalesce(p_note, '')), '');
begin
  if v_bin is null or v_bin = '' then
    raise exception 'Bin location is required';
  end if;

  select bin_code into v_previous
  from public.inventory_bin_locations
  where location_id = p_location_id and product_id = p_product_id
  for update;

  insert into public.inventory_bin_locations (
    location_id, product_id, bin_code, note, updated_at, updated_by_user_id, updated_by_name
  ) values (
    p_location_id, p_product_id, v_bin, v_note, now(), p_user_id, p_user_name
  )
  on conflict (location_id, product_id) do update set
    bin_code = excluded.bin_code,
    note = excluded.note,
    updated_at = excluded.updated_at,
    updated_by_user_id = excluded.updated_by_user_id,
    updated_by_name = excluded.updated_by_name;

  insert into public.inventory_bin_location_history (
    location_id, product_id, previous_bin_code, bin_code, note, changed_by_user_id, changed_by_name
  ) values (
    p_location_id, p_product_id, v_previous, v_bin, v_note, p_user_id, p_user_name
  );

  return jsonb_build_object(
    'location_id', p_location_id,
    'product_id', p_product_id,
    'previous_bin_code', v_previous,
    'bin_code', v_bin
  );
end;
$$;

revoke all on function public.set_v2_inventory_bin_location(bigint,bigint,text,text,uuid,text)
  from public, anon, authenticated;
grant execute on function public.set_v2_inventory_bin_location(bigint,bigint,text,text,uuid,text)
  to service_role;