-- V2 production and bill-of-materials ledger
create table if not exists public.product_boms (
 id bigint generated by default as identity primary key,
 finished_product_id bigint not null references public.products(id),
 yield_quantity numeric not null default 1 check (yield_quantity > 0),
 notes text, active boolean not null default true,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 unique(finished_product_id)
);
create table if not exists public.product_bom_components (
 id bigint generated by default as identity primary key,
 bom_id bigint not null references public.product_boms(id) on delete cascade,
 component_product_id bigint not null references public.products(id),
 quantity_per_yield numeric not null check (quantity_per_yield > 0),
 created_at timestamptz not null default now(), unique(bom_id, component_product_id)
);
alter table public.product_boms enable row level security;
alter table public.product_bom_components enable row level security;

create or replace function public.complete_v2_production(p_bom_id bigint, p_location_id bigint, p_output_quantity numeric, p_reference text, p_idempotency_key text, p_user_id bigint, p_user_name text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'pg_catalog', 'public'
security invoker as $function$
declare
  v_bom public.product_boms%rowtype; v_finished public.products%rowtype; v_component record;
  v_before numeric; v_after numeric; v_needed numeric; v_on_hand numeric; v_shortages jsonb := '[]'::jsonb;
begin
  if p_output_quantity is null or p_output_quantity <= 0 then raise exception 'output quantity must be greater than zero'; end if;
  if p_location_id is null then raise exception 'production location is required'; end if;
  if nullif(trim(coalesce(p_idempotency_key,'')),'') is null then raise exception 'idempotency key is required'; end if;
  if exists (select 1 from public.inventory_movements where idempotency_key = p_idempotency_key || ':complete') then
    return jsonb_build_object('alreadyCompleted',true);
  end if;
  select * into v_bom from public.product_boms where id=p_bom_id and active=true for update;
  if not found then raise exception 'active BOM not found'; end if;
  select * into v_finished from public.products where id=v_bom.finished_product_id and active=true;
  if not found then raise exception 'finished product not found'; end if;
  if not exists (select 1 from public.product_bom_components where bom_id=v_bom.id) then raise exception 'BOM needs at least one component'; end if;
  for v_component in
    select c.component_product_id,c.quantity_per_yield,p.sku,p.name
    from public.product_bom_components c join public.products p on p.id=c.component_product_id
    where c.bom_id=v_bom.id and p.active=true order by c.component_product_id
  loop
    v_needed := p_output_quantity * v_component.quantity_per_yield / v_bom.yield_quantity;
    insert into public.inventory_balances(product_id,location_id,quantity,allocated_quantity) values(v_component.component_product_id,p_location_id,0,0)
      on conflict(product_id,location_id) do nothing;
    select quantity,allocated_quantity into v_before,v_after from public.inventory_balances where product_id=v_component.component_product_id and location_id=p_location_id for update;
    if v_before-v_needed < 0 and v_after > 0 then raise exception 'cannot consume allocated component %', v_component.sku; end if;
    update public.inventory_balances set quantity=v_before-v_needed, updated_at=now() where product_id=v_component.component_product_id and location_id=p_location_id;
    insert into public.inventory_movements(product_id,location_id,movement_type,quantity_delta,quantity_before,quantity_after,reference_number,note,idempotency_key,created_by)
    values(v_component.component_product_id,p_location_id,'production_consume',-v_needed,v_before,v_before-v_needed,nullif(trim(p_reference),''),'Production consumption for '||v_finished.sku,p_idempotency_key||':consume:'||v_component.component_product_id,p_user_id);
    if v_before-v_needed < 0 then v_shortages := v_shortages || jsonb_build_array(jsonb_build_object('sku',v_component.sku,'shortage',abs(v_before-v_needed))); end if;
  end loop;
  insert into public.inventory_balances(product_id,location_id,quantity,allocated_quantity) values(v_finished.id,p_location_id,0,0) on conflict(product_id,location_id) do nothing;
  select quantity into v_before from public.inventory_balances where product_id=v_finished.id and location_id=p_location_id for update;
  v_on_hand := v_before+p_output_quantity;
  update public.inventory_balances set quantity=v_on_hand,updated_at=now() where product_id=v_finished.id and location_id=p_location_id;
  insert into public.inventory_movements(product_id,location_id,movement_type,quantity_delta,quantity_before,quantity_after,reference_number,note,idempotency_key,created_by)
  values(v_finished.id,p_location_id,'production_complete',p_output_quantity,v_before,v_on_hand,nullif(trim(p_reference),''),'Production complete',p_idempotency_key||':complete',p_user_id);
  insert into public.activity_events(user_id,user_name,action_type,document_type,document_number,description,status,metadata)
  values(p_user_id,coalesce(nullif(trim(p_user_name),''),'Warehouse user'),'PRODUCTION_COMPLETED','production',coalesce(nullif(trim(p_reference),''),'PROD-'||p_idempotency_key),'Completed '||p_output_quantity||' of '||v_finished.sku,'completed',jsonb_build_object('bomId',v_bom.id,'locationId',p_location_id,'quantity',p_output_quantity,'shortages',v_shortages));
  return jsonb_build_object('alreadyCompleted',false,'sku',v_finished.sku,'quantity',p_output_quantity,'onHand',v_on_hand,'shortages',v_shortages);
end $function$


create or replace function public.save_v2_product_bom(p_finished_product_id bigint, p_yield_quantity numeric, p_components jsonb, p_notes text, p_user_id bigint, p_user_name text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'pg_catalog', 'public'
security invoker as $function$
declare v_bom_id bigint; v_component jsonb; v_product public.products%rowtype; v_count integer;
begin
  if p_yield_quantity is null or p_yield_quantity <= 0 then raise exception 'Yield quantity must be greater than zero'; end if;
  if jsonb_typeof(p_components) <> 'array' or jsonb_array_length(p_components)=0 then raise exception 'Add at least one BOM component'; end if;
  select * into v_product from public.products where id=p_finished_product_id and active=true;
  if not found then raise exception 'Finished product not found'; end if;
  select count(*) into v_count from (select (value->>'productId')::bigint as product_id from jsonb_array_elements(p_components)) c;
  if v_count <> (select count(distinct (value->>'productId')::bigint) from jsonb_array_elements(p_components)) then raise exception 'Each BOM component may only be listed once'; end if;
  for v_component in select value from jsonb_array_elements(p_components) loop
    if (v_component->>'productId')::bigint = p_finished_product_id then raise exception 'A finished product cannot be its own component'; end if;
    if coalesce((v_component->>'quantity')::numeric,0)<=0 then raise exception 'Component quantities must be greater than zero'; end if;
    perform 1 from public.products where id=(v_component->>'productId')::bigint and active=true;
    if not found then raise exception 'A selected component is not an active V2 product'; end if;
  end loop;
  insert into public.product_boms(finished_product_id,yield_quantity,notes,active,updated_at)
    values(p_finished_product_id,p_yield_quantity,nullif(btrim(coalesce(p_notes,'')),''),true,now())
    on conflict(finished_product_id) do update set yield_quantity=excluded.yield_quantity,notes=excluded.notes,active=true,updated_at=now()
    returning id into v_bom_id;
  delete from public.product_bom_components where bom_id=v_bom_id;
  insert into public.product_bom_components(bom_id,component_product_id,quantity_per_yield)
    select v_bom_id,(value->>'productId')::bigint,(value->>'quantity')::numeric from jsonb_array_elements(p_components);
  insert into public.activity_events(user_id,user_name,action_type,document_type,document_number,description,status,metadata)
    values(p_user_id,p_user_name,'BOM_CONFIGURED','bom',v_product.sku,'Configured BOM for '||v_product.sku,'success',jsonb_build_object('bomId',v_bom_id,'finishedProductId',p_finished_product_id,'yieldQuantity',p_yield_quantity,'componentCount',jsonb_array_length(p_components)));
  return jsonb_build_object('bomId',v_bom_id,'finishedProductId',p_finished_product_id,'yieldQuantity',p_yield_quantity,'componentCount',jsonb_array_length(p_components));
end $function$

revoke all on function public.save_v2_product_bom(bigint,numeric,jsonb,text,bigint,text) from public,anon,authenticated;
grant execute on function public.save_v2_product_bom(bigint,numeric,jsonb,text,bigint,text) to service_role;
revoke all on function public.complete_v2_production(bigint,bigint,numeric,text,text,bigint,text) from public,anon,authenticated;
grant execute on function public.complete_v2_production(bigint,bigint,numeric,text,text,bigint,text) to service_role;
