begin;

create table if not exists public.shopify_inventory_sync_state (
  store_key text primary key check (store_key in ('store_1','store_2')),
  cursor text,
  cycle_started_at timestamptz,
  last_synced_at timestamptz,
  last_completed_at timestamptz,
  last_error text,
  updated_at timestamptz not null default now()
);
insert into public.shopify_inventory_sync_state(store_key)
values ('store_1'),('store_2')
on conflict (store_key) do nothing;

create table if not exists public.shopify_inventory_sync_runs (
  id bigint generated by default as identity primary key,
  store_key text not null check (store_key in ('store_1','store_2')),
  cycle_key text not null,
  cursor_before text,
  cursor_after text,
  scanned_items integer not null default 0,
  applied_levels integer not null default 0,
  changed_levels integer not null default 0,
  skipped_items integer not null default 0,
  completed_cycle boolean not null default false,
  error text,
  created_at timestamptz not null default now()
);
create index if not exists shopify_inventory_sync_runs_store_created_idx
  on public.shopify_inventory_sync_runs(store_key, created_at desc);

alter table public.shopify_inventory_sync_state enable row level security;
alter table public.shopify_inventory_sync_runs enable row level security;
revoke all on public.shopify_inventory_sync_state, public.shopify_inventory_sync_runs from public, anon, authenticated;
grant select, insert, update on public.shopify_inventory_sync_state to service_role;
grant select, insert on public.shopify_inventory_sync_runs to service_role;

create or replace function public.apply_v2_shopify_inventory_sync_page(
  p_store_key text,
  p_cycle_key text,
  p_items jsonb
) returns jsonb
language plpgsql
security invoker
set search_path = pg_catalog, public
as $$
declare
  v_item jsonb;
  v_level jsonb;
  v_sku text;
  v_item_id text;
  v_product_id bigint;
  v_product_count integer;
  v_location_id bigint;
  v_on_hand numeric;
  v_available numeric;
  v_committed numeric;
  v_before numeric;
  v_before_allocated numeric;
  v_applied integer := 0;
  v_changed integer := 0;
  v_skipped integer := 0;
begin
  if p_store_key not in ('store_1','store_2') then raise exception 'Unknown Shopify store.'; end if;
  if nullif(btrim(coalesce(p_cycle_key,'')),'') is null then raise exception 'Sync cycle key is required.'; end if;
  if jsonb_typeof(coalesce(p_items,'[]'::jsonb)) <> 'array' then raise exception 'Inventory page must be an array.'; end if;

  for v_item in select value from jsonb_array_elements(p_items) loop
    v_sku := nullif(btrim(coalesce(v_item->>'sku','')),'');
    v_item_id := nullif(btrim(coalesce(v_item->>'inventoryItemId','')),'');
    if v_sku is null or v_item_id is null then
      v_skipped := v_skipped + 1;
      continue;
    end if;

    select count(*), min(id) into v_product_count, v_product_id
    from public.products
    where active = true and upper(btrim(sku)) = upper(v_sku);
    if v_product_count <> 1 then
      v_skipped := v_skipped + 1;
      continue;
    end if;

    for v_level in select value from jsonb_array_elements(coalesce(v_item->'levels','[]'::jsonb)) loop
      select location_id into v_location_id
      from public.shopify_location_mappings
      where store_key = p_store_key and shopify_location_id = coalesce(v_level->>'locationId','')
      limit 1;
      if v_location_id is null then continue; end if;

      v_on_hand := coalesce(nullif(v_level->>'onHand','')::numeric,0);
      v_available := coalesce(nullif(v_level->>'available','')::numeric,0);
      v_committed := greatest(coalesce(nullif(v_level->>'committed','')::numeric,0), 0);

      insert into public.inventory_balances(product_id,location_id,quantity,allocated_quantity)
      values(v_product_id,v_location_id,0,0)
      on conflict(product_id,location_id) do nothing;

      select quantity,allocated_quantity into v_before,v_before_allocated
      from public.inventory_balances
      where product_id=v_product_id and location_id=v_location_id
      for update;

      update public.inventory_balances
      set quantity=v_on_hand, allocated_quantity=v_committed, updated_at=now()
      where product_id=v_product_id and location_id=v_location_id;

      v_applied := v_applied + 1;
      if v_before is distinct from v_on_hand or v_before_allocated is distinct from v_committed then
        insert into public.inventory_movements(
          product_id,location_id,movement_type,quantity_delta,quantity_before,quantity_after,
          unit_cost,reference_type,reference_id,reason,idempotency_key,performed_by_name,metadata
        ) values (
          v_product_id,v_location_id,'shopify_reconciliation',v_on_hand-v_before,v_before,v_on_hand,
          null,'shopify_inventory_sync',v_item_id,'Shopify phased inventory reconciliation',
          'shopify-sync:'||p_store_key||':'||p_cycle_key||':'||v_item_id||':'||coalesce(v_level->>'locationId',''),
          'Shopify sync',
          jsonb_build_object('storeKey',p_store_key,'shopifyInventoryItemId',v_item_id,
            'shopifyLocationId',v_level->>'locationId','shopifyOnHand',v_on_hand,
            'shopifyAvailable',v_available,'shopifyCommitted',v_committed)
        );
        v_changed := v_changed + 1;
      end if;
    end loop;
  end loop;
  return jsonb_build_object('appliedLevels',v_applied,'changedLevels',v_changed,'skippedItems',v_skipped);
end;
$$;

revoke all on function public.apply_v2_shopify_inventory_sync_page(text,text,jsonb) from public, anon, authenticated;
grant execute on function public.apply_v2_shopify_inventory_sync_page(text,text,jsonb) to service_role;

commit;
