begin;

create table if not exists public.intercompany_transfer_ledger_lines (
  id bigint generated by default as identity primary key,
  transfer_link_id uuid not null references public.shopify_transfer_links(id) on delete cascade,
  transfer_line_id bigint not null references public.shopify_transfer_link_lines(id) on delete restrict,
  bm_reference text not null,
  status text not null check (status in ('shipped','completed')),
  source_entity text not null,
  destination_entity text not null,
  source_location_id bigint not null references public.locations(id),
  destination_location_id bigint not null references public.locations(id),
  sku text not null,
  product_id bigint references public.products(id),
  quantity numeric not null check (quantity > 0),
  unit_cost numeric not null check (unit_cost >= 0),
  extended_value numeric generated always as (round(quantity * unit_cost, 4)) stored,
  currency text not null default 'USD' check (currency = 'USD'),
  source_shopify_adjustment_id text,
  destination_shopify_adjustment_id text,
  shipped_at timestamptz not null,
  received_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (transfer_line_id)
);

create index if not exists intercompany_transfer_ledger_lines_bookkeeping_idx
  on public.intercompany_transfer_ledger_lines (shipped_at desc, bm_reference);
create index if not exists intercompany_transfer_ledger_lines_entities_idx
  on public.intercompany_transfer_ledger_lines (source_entity, destination_entity, status);

alter table public.intercompany_transfer_ledger_lines enable row level security;
revoke all on table public.intercompany_transfer_ledger_lines from anon, authenticated;
grant select, insert, update, delete on table public.intercompany_transfer_ledger_lines to service_role;

insert into public.intercompany_transfer_ledger_lines (
  transfer_link_id, transfer_line_id, bm_reference, status, source_entity, destination_entity,
  source_location_id, destination_location_id, sku, product_id, quantity, unit_cost,
  source_shopify_adjustment_id, destination_shopify_adjustment_id, shipped_at, received_at
)
select
  l.id,
  ln.id,
  l.bm_reference,
  case when l.status = 'completed' then 'completed' else 'shipped' end,
  coalesce(l.metadata->>'source_entity', l.source_store_key),
  coalesce(l.metadata->>'destination_entity', l.destination_store_key),
  l.source_location_id,
  l.destination_location_id,
  ln.sku,
  p.id,
  ln.quantity,
  coalesce(p.moving_average_cost, p.purchase_price, 0),
  l.source_shopify_adjustment_reference,
  l.metadata->>'receive_adjustment_group_id',
  coalesce(l.shipped_at, l.created_at),
  l.received_at
from public.shopify_transfer_links l
join public.shopify_transfer_link_lines ln on ln.transfer_link_id = l.id
left join public.products p on upper(p.sku) = upper(ln.sku)
where l.route_type = 'cross_store'
  and l.status in ('shipped','partially_received','completed')
on conflict (transfer_line_id) do nothing;

comment on table public.intercompany_transfer_ledger_lines is
  'Bookkeeping snapshots of cross-company transfer value. Unit cost is frozen from the source product moving-average cost at shipment; it never writes to Shopify.';

commit;