-- BM-MFG-PILOT-001: one-door, fail-closed Manufacturing pilot.
-- Qoblex remains production. This gate is intentionally unusable until one SKU,
-- retail destination, and machine are explicitly approved.

create table if not exists public.manufacturing_pilot_gate (
  pilot_identifier text primary key,
  enabled boolean not null default false,
  approved_bom_id bigint references public.product_boms(id),
  approved_finished_product_id bigint references public.products(id),
  origin_location_id bigint not null references public.locations(id),
  destination_location_id bigint references public.locations(id),
  machine_code text check (machine_code in ('NIGHTHAWK','TERMINATOR')),
  approved_user_ids bigint[] not null,
  configured_by_user_id bigint references public.app_users(id),
  configured_at timestamptz,
  check (cardinality(approved_user_ids)=2)
);

create table if not exists public.manufacturing_pilot_orders (
  id bigint generated by default as identity primary key,
  pilot_identifier text not null references public.manufacturing_pilot_gate(pilot_identifier),
  work_order_number text not null unique,
  bom_id bigint not null references public.product_boms(id),
  finished_product_id bigint not null references public.products(id),
  origin_location_id bigint not null references public.locations(id),
  destination_location_id bigint not null references public.locations(id),
  machine_code text not null check (machine_code in ('NIGHTHAWK','TERMINATOR')),
  quantity integer not null check (quantity=1),
  status text not null check (status in ('draft','released','in_production','awaiting_shopify','shopify_confirmed','transfer_created','in_transit','received','closed','cancelled')),
  frozen_bom jsonb not null,
  frozen_bom_hash text not null,
  shopify_completion_reference text,
  shopify_transfer_link_id uuid references public.shopify_transfer_links(id),
  created_by_user_id bigint not null references public.app_users(id),
  released_at timestamptz,
  production_started_at timestamptz,
  completed_at timestamptz,
  closed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists manufacturing_pilot_one_active
  on public.manufacturing_pilot_orders ((1))
  where status not in ('closed','cancelled');

create table if not exists public.manufacturing_pilot_allocations (
  pilot_order_id bigint not null references public.manufacturing_pilot_orders(id) on delete cascade,
  component_product_id bigint not null references public.products(id),
  required_quantity numeric not null check (required_quantity>0),
  consumed_quantity numeric not null default 0 check (consumed_quantity>=0),
  primary key (pilot_order_id,component_product_id)
);

alter table public.manufacturing_pilot_gate enable row level security;
alter table public.manufacturing_pilot_orders enable row level security;
alter table public.manufacturing_pilot_allocations enable row level security;
revoke all on public.manufacturing_pilot_gate,public.manufacturing_pilot_orders,public.manufacturing_pilot_allocations from public,anon,authenticated;
grant all on public.manufacturing_pilot_gate,public.manufacturing_pilot_orders,public.manufacturing_pilot_allocations to service_role;

insert into public.manufacturing_pilot_gate(
  pilot_identifier,enabled,approved_bom_id,approved_finished_product_id,
  origin_location_id,destination_location_id,machine_code,approved_user_ids,
  configured_by_user_id,configured_at
)
select 'BM-MFG-PILOT-001',false,b.id,p.id,origin.id,destination.id,'NIGHTHAWK',
  array[greg.id,edwin.id]::bigint[],greg.id,now()
from public.products p
join public.product_boms b on b.finished_product_id=p.id and b.active
join public.locations origin on origin.code='730' and origin.name='730 Windham Rd' and origin.active
join public.locations destination on destination.name='Annex' and destination.active
join public.app_users greg on lower(greg.email)='greg@bargainmoulding.com' and greg.active
join public.app_users edwin on lower(edwin.email)='edwin@bargainmoulding.com' and edwin.active
where p.sku='CD2680PHLHSN80'
on conflict (pilot_identifier) do nothing;

do $$ begin
  if not exists (
    select 1 from public.manufacturing_pilot_gate
    where pilot_identifier='BM-MFG-PILOT-001' and enabled is false
      and cardinality(approved_user_ids)=2
  ) then
    raise exception 'BM-MFG-PILOT-001 configuration did not resolve exactly';
  end if;
end $$;

create or replace function public.create_manufacturing_pilot_draft(
  p_pilot_identifier text,p_user_id bigint
) returns jsonb language plpgsql security invoker set search_path='pg_catalog','public' as $$
declare g public.manufacturing_pilot_gate%rowtype; b public.product_boms%rowtype;
  v_id bigint; v_number text; v_frozen jsonb; v_hash text;
begin
  perform pg_advisory_xact_lock(hashtext(p_pilot_identifier));
  select * into g from public.manufacturing_pilot_gate where pilot_identifier=p_pilot_identifier for update;
  if not found or not g.enabled then raise exception 'Restricted Manufacturing pilot is not approved and enabled'; end if;
  if not (p_user_id=any(g.approved_user_ids)) then raise exception 'Only Greg or Edwin may operate this pilot'; end if;
  if g.approved_bom_id is null or g.approved_finished_product_id is null or g.destination_location_id is null or g.machine_code is null then raise exception 'Pilot SKU, destination, and machine must be approved'; end if;
  if exists(select 1 from public.manufacturing_pilot_orders where status not in ('closed','cancelled')) then raise exception 'A pilot work order is already active'; end if;
  select * into b from public.product_boms where id=g.approved_bom_id and finished_product_id=g.approved_finished_product_id and active for share;
  if not found then raise exception 'Approved BOM is missing or inactive'; end if;
  select jsonb_build_object('bomId',b.id,'finishedProductId',b.finished_product_id,'yieldQuantity',b.yield_quantity,
    'components',coalesce(jsonb_agg(jsonb_build_object('productId',c.component_product_id,'quantity',c.quantity_per_yield) order by c.component_product_id),'[]'::jsonb))
    into v_frozen from public.product_bom_components c where c.bom_id=b.id group by b.id,b.finished_product_id,b.yield_quantity;
  if v_frozen is null or jsonb_array_length(v_frozen->'components')=0 then raise exception 'Approved BOM has no components'; end if;
  v_hash:=md5(v_frozen::text); v_number:=p_pilot_identifier;
  insert into public.manufacturing_pilot_orders(pilot_identifier,work_order_number,bom_id,finished_product_id,origin_location_id,destination_location_id,machine_code,quantity,status,frozen_bom,frozen_bom_hash,created_by_user_id)
  values(g.pilot_identifier,v_number,g.approved_bom_id,g.approved_finished_product_id,g.origin_location_id,g.destination_location_id,g.machine_code,1,'draft',v_frozen,v_hash,p_user_id) returning id into v_id;
  return jsonb_build_object('id',v_id,'workOrderNumber',v_number,'status','draft','frozenBomHash',v_hash);
end $$;

create or replace function public.advance_manufacturing_pilot(
  p_pilot_order_id bigint,p_action text,p_user_id bigint,p_external_reference text default null
) returns jsonb language plpgsql security invoker set search_path='pg_catalog','public' as $$
declare o public.manufacturing_pilot_orders%rowtype; g public.manufacturing_pilot_gate%rowtype; c record; ib record; v_before numeric;
begin
  perform pg_advisory_xact_lock(hashtext('BM-MFG-PILOT-001'));
  select * into o from public.manufacturing_pilot_orders where id=p_pilot_order_id for update;
  if not found then raise exception 'Pilot work order not found'; end if;
  select * into g from public.manufacturing_pilot_gate where pilot_identifier=o.pilot_identifier for update;
  if not g.enabled or not (p_user_id=any(g.approved_user_ids)) then raise exception 'Pilot gate rejected this request'; end if;
  if o.quantity<>1 or o.origin_location_id<>g.origin_location_id or o.destination_location_id<>g.destination_location_id or o.machine_code<>g.machine_code or o.finished_product_id<>g.approved_finished_product_id or o.bom_id<>g.approved_bom_id then raise exception 'Pilot scope changed; request rejected'; end if;
  if md5(o.frozen_bom::text)<>o.frozen_bom_hash then raise exception 'Frozen BOM integrity check failed'; end if;
  if p_action='release' then
    if o.status<>'draft' then raise exception 'Only a draft pilot may be released'; end if;
    for c in select (x->>'productId')::bigint product_id,
      (x->>'quantity')::numeric / (o.frozen_bom->>'yieldQuantity')::numeric needed
      from jsonb_array_elements(o.frozen_bom->'components') x order by 1 loop
      insert into public.inventory_balances(product_id,location_id,quantity,allocated_quantity) values(c.product_id,o.origin_location_id,0,0) on conflict(product_id,location_id) do nothing;
      select * into ib from public.inventory_balances where product_id=c.product_id and location_id=o.origin_location_id for update;
      if ib.quantity-ib.allocated_quantity<c.needed then raise exception 'Component shortage for product %; pilot release rejected',c.product_id; end if;
      update public.inventory_balances set allocated_quantity=allocated_quantity+c.needed,updated_at=now() where product_id=c.product_id and location_id=o.origin_location_id;
      insert into public.manufacturing_pilot_allocations values(o.id,c.product_id,c.needed,0);
    end loop;
    update public.manufacturing_pilot_orders set status='released',released_at=now(),updated_at=now() where id=o.id;
  elsif p_action='start' then
    if o.status<>'released' then raise exception 'Pilot must be released before production starts'; end if;
    update public.manufacturing_pilot_orders set status='in_production',production_started_at=now(),updated_at=now() where id=o.id;
  elsif p_action='record_good_unit' then
    if o.status<>'in_production' then raise exception 'Pilot is not in production'; end if;
    for c in select * from public.manufacturing_pilot_allocations where pilot_order_id=o.id order by component_product_id for update loop
      select quantity into v_before from public.inventory_balances where product_id=c.component_product_id and location_id=o.origin_location_id for update;
      if v_before<c.required_quantity then raise exception 'Component shortage at completion; no inventory changed'; end if;
      update public.inventory_balances set quantity=v_before-c.required_quantity,allocated_quantity=allocated_quantity-c.required_quantity,updated_at=now() where product_id=c.component_product_id and location_id=o.origin_location_id;
      update public.manufacturing_pilot_allocations set consumed_quantity=required_quantity where pilot_order_id=o.id and component_product_id=c.component_product_id;
      insert into public.inventory_movements(product_id,location_id,movement_type,quantity_delta,quantity_before,quantity_after,reference_type,reference_id,reason,idempotency_key,performed_by_user_id)
      values(c.component_product_id,o.origin_location_id,'production_consume',-c.required_quantity,v_before,v_before-c.required_quantity,'manufacturing_pilot',o.work_order_number,'Restricted one-door pilot',o.pilot_identifier||':consume:'||c.component_product_id,p_user_id);
    end loop;
    insert into public.inventory_balances(product_id,location_id,quantity,allocated_quantity) values(o.finished_product_id,o.origin_location_id,0,0) on conflict(product_id,location_id) do nothing;
    select quantity into v_before from public.inventory_balances where product_id=o.finished_product_id and location_id=o.origin_location_id for update;
    update public.inventory_balances set quantity=v_before+1,updated_at=now() where product_id=o.finished_product_id and location_id=o.origin_location_id;
    insert into public.inventory_movements(product_id,location_id,movement_type,quantity_delta,quantity_before,quantity_after,reference_type,reference_id,reason,idempotency_key,performed_by_user_id)
    values(o.finished_product_id,o.origin_location_id,'production_complete',1,v_before,v_before+1,'manufacturing_pilot',o.work_order_number,'Restricted one-door pilot',o.pilot_identifier||':complete',p_user_id);
    update public.manufacturing_pilot_orders set status='awaiting_shopify',completed_at=now(),updated_at=now() where id=o.id;
  elsif p_action='confirm_shopify' then
    if o.status<>'awaiting_shopify' or nullif(btrim(coalesce(p_external_reference,'')),'') is null then raise exception 'A confirmed Shopify inventory reference is required'; end if;
    update public.manufacturing_pilot_orders set status='shopify_confirmed',shopify_completion_reference=p_external_reference,updated_at=now() where id=o.id;
  elsif p_action='close' then
    if o.status<>'received' then raise exception 'Pilot transfer must be received before the work order closes'; end if;
    update public.manufacturing_pilot_orders set status='closed',closed_at=now(),updated_at=now() where id=o.id;
  else raise exception 'Pilot action is not allowed'; end if;
  return jsonb_build_object('id',o.id,'action',p_action,'ok',true);
end $$;

revoke all on function public.create_manufacturing_pilot_draft(text,bigint) from public,anon,authenticated;
revoke all on function public.advance_manufacturing_pilot(bigint,text,bigint,text) from public,anon,authenticated;
grant execute on function public.create_manufacturing_pilot_draft(text,bigint) to service_role;
grant execute on function public.advance_manufacturing_pilot(bigint,text,bigint,text) to service_role;
