-- Durable, line-level PO receipts for scan-first warehouse receiving.
alter table public.purchase_order_lines
  add column if not exists damaged_quantity numeric not null default 0,
  add constraint purchase_order_lines_damaged_quantity_check check (damaged_quantity >= 0),
  add constraint purchase_order_lines_total_received_check check (received_quantity + damaged_quantity <= ordered_quantity);

create table if not exists public.purchase_order_receipts (
  id bigint generated by default as identity primary key,
  purchase_order_id bigint not null references public.purchase_orders(id) on delete cascade,
  receipt_number text not null unique,
  receiving_location_id bigint not null references public.locations(id) on delete restrict,
  received_by_user_id bigint references public.app_users(id) on delete set null,
  received_by_name text,
  reference text,
  notes text,
  idempotency_key text not null unique,
  received_at timestamptz not null default now()
);

create table if not exists public.purchase_order_receipt_lines (
  id bigint generated by default as identity primary key,
  purchase_order_receipt_id bigint not null references public.purchase_order_receipts(id) on delete cascade,
  purchase_order_line_id bigint not null references public.purchase_order_lines(id) on delete restrict,
  received_quantity numeric not null default 0 check (received_quantity >= 0),
  damaged_quantity numeric not null default 0 check (damaged_quantity >= 0),
  notes text,
  check (received_quantity + damaged_quantity > 0)
);

create index if not exists purchase_order_receipts_order_idx on public.purchase_order_receipts(purchase_order_id, received_at desc);
create index if not exists purchase_order_receipt_lines_receipt_idx on public.purchase_order_receipt_lines(purchase_order_receipt_id);
alter table public.purchase_order_receipts enable row level security;
alter table public.purchase_order_receipt_lines enable row level security;

create or replace function public.receive_v2_purchase_order_lines(
  p_purchase_order_id bigint,
  p_lines jsonb,
  p_reference text,
  p_notes text,
  p_idempotency_key text,
  p_user_id bigint,
  p_user_name text
) returns jsonb language plpgsql set search_path to 'pg_catalog', 'public' as $$
declare
  v_order public.purchase_orders%rowtype;
  v_line public.purchase_order_lines%rowtype;
  v_input jsonb;
  v_line_id bigint;
  v_good numeric;
  v_damaged numeric;
  v_remaining numeric;
  v_before numeric;
  v_receipt_id bigint;
  v_receipt_number text;
  v_open_lines integer;
begin
  if nullif(trim(coalesce(p_idempotency_key, '')), '') is null then raise exception 'Receipt idempotency key is required'; end if;
  if jsonb_typeof(p_lines) <> 'array' or jsonb_array_length(p_lines) = 0 then raise exception 'Scan or enter at least one received line'; end if;
  select * into v_order from public.purchase_orders where id = p_purchase_order_id for update;
  if not found then raise exception 'Purchase order not found'; end if;
  if v_order.status in ('received', 'cancelled') then raise exception 'This purchase order is closed'; end if;
  select id, receipt_number into v_receipt_id, v_receipt_number from public.purchase_order_receipts where idempotency_key = p_idempotency_key;
  if v_receipt_id is not null then return jsonb_build_object('alreadyReceived', true, 'receiptNumber', v_receipt_number, 'purchaseOrderNumber', v_order.purchase_order_number, 'status', v_order.status); end if;
  v_receipt_number := 'RCV-' || to_char(clock_timestamp(), 'YYYYMMDD-HH24MISSMS');
  insert into public.purchase_order_receipts(purchase_order_id, receipt_number, receiving_location_id, received_by_user_id, received_by_name, reference, notes, idempotency_key)
  values (v_order.id, v_receipt_number, v_order.receiving_location_id, p_user_id, p_user_name, nullif(trim(coalesce(p_reference, '')), ''), nullif(trim(coalesce(p_notes, '')), ''), p_idempotency_key)
  returning id into v_receipt_id;
  for v_input in select value from jsonb_array_elements(p_lines) loop
    v_line_id := nullif(v_input->>'lineId', '')::bigint;
    v_good := coalesce(nullif(v_input->>'receivedQuantity', '')::numeric, 0);
    v_damaged := coalesce(nullif(v_input->>'damagedQuantity', '')::numeric, 0);
    if v_line_id is null or v_good < 0 or v_damaged < 0 or v_good + v_damaged <= 0 then raise exception 'Receipt quantities must be positive'; end if;
    select * into v_line from public.purchase_order_lines where id = v_line_id and purchase_order_id = v_order.id for update;
    if not found then raise exception 'A scanned line does not belong to this purchase order'; end if;
    v_remaining := v_line.ordered_quantity - v_line.received_quantity - v_line.damaged_quantity;
    if v_good + v_damaged > v_remaining then raise exception 'Receipt exceeds remaining quantity for PO line %', v_line_id; end if;
    insert into public.purchase_order_receipt_lines(purchase_order_receipt_id, purchase_order_line_id, received_quantity, damaged_quantity, notes)
    values (v_receipt_id, v_line.id, v_good, v_damaged, nullif(trim(coalesce(v_input->>'note', '')), ''));
    update public.purchase_order_lines set received_quantity = received_quantity + v_good, damaged_quantity = damaged_quantity + v_damaged where id = v_line.id;
    if v_good > 0 then
      insert into public.inventory_balances(product_id, location_id, quantity, allocated_quantity) values (v_line.product_id, v_order.receiving_location_id, 0, 0) on conflict(product_id, location_id) do nothing;
      select quantity into v_before from public.inventory_balances where product_id = v_line.product_id and location_id = v_order.receiving_location_id for update;
      update public.inventory_balances set quantity = v_before + v_good, updated_at = now() where product_id = v_line.product_id and location_id = v_order.receiving_location_id;
      insert into public.inventory_movements(product_id, location_id, movement_type, quantity_delta, quantity_before, quantity_after, reference_type, reference_id, reason, idempotency_key, performed_by_user_id, performed_by_name, metadata)
      values (v_line.product_id, v_order.receiving_location_id, 'purchase_receipt', v_good, v_before, v_before + v_good, 'purchase_order', v_order.purchase_order_number, 'Scan-first PO receipt ' || v_receipt_number, 'po-receipt:' || v_receipt_id || ':line:' || v_line.id, p_user_id, p_user_name, jsonb_build_object('purchaseOrderId', v_order.id, 'receiptId', v_receipt_id, 'damagedQuantity', v_damaged));
    end if;
  end loop;
  select count(*) into v_open_lines from public.purchase_order_lines where purchase_order_id = v_order.id and received_quantity + damaged_quantity < ordered_quantity;
  update public.purchase_orders set status = case when v_open_lines = 0 then 'received' else 'partially_received' end, received_at = case when v_open_lines = 0 then now() else received_at end, updated_at = now() where id = v_order.id returning * into v_order;
  insert into public.activity_events(user_id, user_name, action_type, document_type, document_number, description, status, metadata)
  values (p_user_id, p_user_name, 'PURCHASE_ORDER_RECEIVED', 'purchase_order', v_order.purchase_order_number, 'Recorded scan-first receipt ' || v_receipt_number, 'success', jsonb_build_object('purchaseOrderId', v_order.id, 'receiptId', v_receipt_id, 'receivingLocationId', v_order.receiving_location_id));
  return jsonb_build_object('alreadyReceived', false, 'receiptNumber', v_receipt_number, 'purchaseOrderNumber', v_order.purchase_order_number, 'status', v_order.status);
end $$;

revoke all on function public.receive_v2_purchase_order_lines(bigint, jsonb, text, text, text, bigint, text) from public, anon, authenticated;
grant execute on function public.receive_v2_purchase_order_lines(bigint, jsonb, text, text, text, bigint, text) to service_role;
