-- Shopify paid-order manufacturing triggers.
-- This is operational metadata only: Shopify remains the inventory and fulfillment system of record.

create table if not exists public.manufacturing_shopify_triggers (
  id bigint generated by default as identity primary key,
  shopify_store_key text not null check (shopify_store_key in ('store_1','store_2')),
  shopify_product_id text not null,
  destination_location_id bigint not null references public.locations(id),
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (shopify_store_key, shopify_product_id)
);

create index if not exists manufacturing_shopify_triggers_destination_idx
  on public.manufacturing_shopify_triggers(destination_location_id);

create table if not exists public.manufacturing_shopify_work_order_events (
  id bigint generated by default as identity primary key,
  shopify_store_key text not null check (shopify_store_key in ('store_1','store_2')),
  shopify_order_id text not null,
  shopify_order_name text,
  shopify_line_item_id text not null,
  shopify_product_id text not null,
  shopify_variant_id text,
  sku text,
  quantity numeric not null check (quantity > 0),
  bom_id bigint references public.product_boms(id),
  production_work_order_id bigint references public.production_work_orders(id),
  status text not null default 'pending'
    check (status in ('pending','released','needs_bom','failed','ignored')),
  error text,
  payload jsonb not null default '{}'::jsonb,
  received_at timestamptz not null default now(),
  processed_at timestamptz,
  updated_at timestamptz not null default now(),
  unique (shopify_store_key, shopify_order_id, shopify_line_item_id)
);

create index if not exists manufacturing_shopify_work_order_events_status_idx
  on public.manufacturing_shopify_work_order_events(status, received_at desc);

alter table public.manufacturing_shopify_triggers enable row level security;
alter table public.manufacturing_shopify_work_order_events enable row level security;

revoke all on table public.manufacturing_shopify_triggers from anon, authenticated;
revoke all on table public.manufacturing_shopify_work_order_events from anon, authenticated;
grant select, insert, update, delete on table public.manufacturing_shopify_triggers to service_role;
grant select, insert, update, delete on table public.manufacturing_shopify_work_order_events to service_role;
grant usage, select on sequence public.manufacturing_shopify_triggers_id_seq to service_role;
grant usage, select on sequence public.manufacturing_shopify_work_order_events_id_seq to service_role;

insert into public.manufacturing_shopify_triggers
  (shopify_store_key, shopify_product_id, destination_location_id, enabled)
select 'store_1', '8975584854228', id, true
from public.locations
where name = 'Amityville Main' and active
on conflict (shopify_store_key, shopify_product_id) do nothing;
