alter table public.transfers
  add column if not exists receiving_started_at timestamptz,
  add column if not exists receiving_by_user_id uuid,
  add column if not exists receiving_by_name text,
  add column if not exists receiving_by_email text,
  add column if not exists problem_note text,
  add column if not exists qoblex_transfer_id bigint,
  add column if not exists qoblex_post_status text,
  add column if not exists qoblex_response jsonb,
  add column if not exists qoblex_submission_started_at timestamptz,
  add column if not exists resolved_at timestamptz,
  add column if not exists resolved_by_name text,
  add column if not exists resolved_by_email text;

create unique index if not exists transfers_qoblex_transfer_id_key
  on public.transfers (qoblex_transfer_id)
  where qoblex_transfer_id is not null;

alter table public.transfer_lines
  add column if not exists qoblex_variant_id bigint,
  add column if not exists qoblex_posted_qty numeric not null default 0,
  add column if not exists discrepancy_note text;

create table if not exists public.transfer_discrepancies (
  id bigint generated by default as identity primary key,
  transfer_id uuid not null references public.transfers(id) on delete cascade,
  transfer_line_id uuid references public.transfer_lines(id) on delete cascade,
  discrepancy_type text not null check (discrepancy_type in ('missing', 'damaged', 'wrong_item', 'overage', 'other')),
  sku text,
  barcode text,
  expected_qty numeric not null default 0,
  received_qty numeric not null default 0,
  discrepancy_qty numeric not null default 0,
  note text,
  reported_by_user_id uuid,
  reported_by_name text not null,
  reported_by_email text,
  created_at timestamptz not null default now(),
  resolved_at timestamptz,
  resolved_by_name text,
  resolution_note text
);

create index if not exists transfer_discrepancies_transfer_id_idx
  on public.transfer_discrepancies (transfer_id, created_at);

alter table public.transfer_discrepancies enable row level security;

revoke all on table public.transfer_discrepancies from anon, authenticated;
revoke all on sequence public.transfer_discrepancies_id_seq from anon, authenticated;

comment on table public.transfer_discrepancies is
  'Server-managed receiving exceptions for BM Warehouse transfers. Qoblex remains the inventory authority.';

comment on column public.transfers.qoblex_post_status is
  'not_submitted, submitting, posted, failed, or unknown; unknown must be reviewed before retrying.';
