begin;

create unique index if not exists shopify_location_mappings_location_id_key
  on public.shopify_location_mappings (location_id);

create table if not exists public.shopify_transfer_links (
  id uuid primary key default gen_random_uuid(),
  bm_reference text not null unique,
  route_type text not null check (route_type in ('same_store', 'cross_store')),
  status text not null default 'draft'
    check (status in ('draft', 'prepared', 'shipped', 'partially_received', 'completed', 'needs_review', 'failed', 'cancelled')),
  source_location_id bigint not null references public.locations(id) on delete restrict,
  destination_location_id bigint not null references public.locations(id) on delete restrict,
  source_store_key text not null check (source_store_key in ('store_1', 'store_2')),
  destination_store_key text not null check (destination_store_key in ('store_1', 'store_2')),
  source_shopify_location_id text not null,
  destination_shopify_location_id text not null,
  source_shopify_transfer_id text,
  source_shopify_adjustment_reference text,
  destination_shopify_purchase_order_id text,
  destination_shopify_transfer_id text,
  created_by_user_id uuid,
  created_by_name text,
  created_at timestamptz not null default now(),
  prepared_at timestamptz,
  shipped_at timestamptz,
  received_at timestamptz,
  error text,
  metadata jsonb not null default '{}'::jsonb,
  check (source_location_id <> destination_location_id)
);

create table if not exists public.shopify_transfer_link_lines (
  id bigint generated by default as identity primary key,
  transfer_link_id uuid not null references public.shopify_transfer_links(id) on delete cascade,
  sku text not null,
  product_id bigint references public.products(id) on delete set null,
  quantity numeric not null check (quantity > 0),
  source_shopify_variant_id text,
  destination_shopify_variant_id text,
  created_at timestamptz not null default now(),
  unique (transfer_link_id, sku)
);

create index if not exists shopify_transfer_links_status_idx
  on public.shopify_transfer_links (status, created_at desc);
create index if not exists shopify_transfer_links_route_idx
  on public.shopify_transfer_links (source_location_id, destination_location_id, created_at desc);
create index if not exists shopify_transfer_link_lines_sku_idx
  on public.shopify_transfer_link_lines (sku);

alter table public.shopify_transfer_links enable row level security;
alter table public.shopify_transfer_link_lines enable row level security;

revoke all on table public.shopify_transfer_links from anon, authenticated;
revoke all on table public.shopify_transfer_link_lines from anon, authenticated;
grant select, insert, update, delete on table public.shopify_transfer_links to service_role;
grant select, insert, update, delete on table public.shopify_transfer_link_lines to service_role;
grant usage, select on sequence public.shopify_transfer_link_lines_id_seq to service_role;

comment on table public.shopify_transfer_links is
  'Workflow and audit links for Shopify-backed transfers. This table never stores inventory balances.';
comment on table public.shopify_transfer_link_lines is
  'SKU lines linked to a Shopify-backed transfer. Inventory quantities remain authoritative in Shopify.';

commit;
