-- V2 transfer lifecycle foundation.
-- V2-only: no Qoblex or Shopify integration is introduced here.

begin;

alter table public.inventory_balances
  drop constraint if exists inventory_balances_quantity_check,
  drop constraint if exists inventory_balances_check;

alter table public.inventory_balances
  add constraint inventory_balances_allocation_check
  check (
    allocated_quantity >= 0
    and (quantity < 0 and allocated_quantity = 0 or quantity >= 0 and allocated_quantity <= quantity)
  );

alter table public.inventory_movements
  drop constraint if exists inventory_movements_quantity_before_check,
  drop constraint if exists inventory_movements_quantity_after_check;

create table if not exists public.transfers (
  id bigint generated by default as identity primary key,
  transfer_number text not null unique,
  from_location_id bigint not null references public.locations(id) on delete restrict,
  to_location_id bigint not null references public.locations(id) on delete restrict,
  status text not null default 'draft'
    check (status in ('draft','allocated','in_transit','partially_received','completed','problem','cancelled')),
  notes text,
  created_by_user_id bigint references public.app_users(id) on delete set null,
  created_by_name text,
  allocated_at timestamptz,
  shipped_at timestamptz,
  received_at timestamptz,
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (from_location_id <> to_location_id)
);

create table if not exists public.transfer_lines (
  id bigint generated by default as identity primary key,
  transfer_id bigint not null references public.transfers(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete restrict,
  requested_quantity numeric not null check (requested_quantity > 0),
  allocated_quantity numeric not null default 0 check (allocated_quantity >= 0),
  shipped_quantity numeric not null default 0 check (shipped_quantity >= 0),
  received_quantity numeric not null default 0 check (received_quantity >= 0),
  damaged_quantity numeric not null default 0 check (damaged_quantity >= 0),
  missing_quantity numeric not null default 0 check (missing_quantity >= 0),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (transfer_id, product_id),
  check (allocated_quantity <= requested_quantity),
  check (shipped_quantity <= allocated_quantity),
  check (received_quantity + damaged_quantity + missing_quantity <= shipped_quantity)
);

create table if not exists public.transfer_discrepancies (
  id bigint generated by default as identity primary key,
  transfer_id bigint not null references public.transfers(id) on delete cascade,
  transfer_line_id bigint references public.transfer_lines(id) on delete set null,
  discrepancy_type text not null check (discrepancy_type in ('missing','damaged','wrong_item','overage','other')),
  quantity numeric not null check (quantity > 0),
  note text,
  reported_by_user_id bigint references public.app_users(id) on delete set null,
  resolved_at timestamptz,
  resolution_note text,
  created_at timestamptz not null default now()
);

create index if not exists transfers_status_updated_idx on public.transfers(status, updated_at desc);
create index if not exists transfers_from_location_idx on public.transfers(from_location_id);
create index if not exists transfers_to_location_idx on public.transfers(to_location_id);
create index if not exists transfers_created_by_idx on public.transfers(created_by_user_id);
create index if not exists transfer_lines_transfer_idx on public.transfer_lines(transfer_id);
create index if not exists transfer_lines_product_idx on public.transfer_lines(product_id);
create index if not exists transfer_discrepancies_open_idx on public.transfer_discrepancies(transfer_id, resolved_at) where resolved_at is null;
create index if not exists transfer_discrepancies_line_idx on public.transfer_discrepancies(transfer_line_id);
create index if not exists transfer_discrepancies_reporter_idx on public.transfer_discrepancies(reported_by_user_id);

alter table public.transfers enable row level security;
alter table public.transfer_lines enable row level security;
alter table public.transfer_discrepancies enable row level security;
revoke all on public.transfers, public.transfer_lines, public.transfer_discrepancies from anon, authenticated;

commit;
