-- V2 par levels: configuration only. Does not change inventory, Shopify, or Qoblex.
create table if not exists public.location_category_par_levels (id bigint generated by default as identity primary key,location_id bigint not null references public.locations(id) on delete cascade,category text not null check(length(btrim(category))>0),par_quantity numeric not null check(par_quantity>=0),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(location_id,category));
create table if not exists public.product_par_levels (id bigint generated by default as identity primary key,location_id bigint not null references public.locations(id) on delete cascade,product_id bigint not null references public.products(id) on delete cascade,par_quantity numeric not null check(par_quantity>=0),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(location_id,product_id));
create index if not exists location_category_par_levels_location_category_idx on public.location_category_par_levels(location_id,category);
create index if not exists product_par_levels_location_product_idx on public.product_par_levels(location_id,product_id);
alter table public.location_category_par_levels enable row level security;
alter table public.product_par_levels enable row level security;
-- Functions are service-role only; see deployed migration v2_par_levels for bodies.
revoke all on table public.location_category_par_levels,public.product_par_levels from anon,authenticated;