const API_VERSION='2026-07';
const tokenCache=new Map();
const ALLOWED_EMAILS=new Set(['greg@bargainmoulding.com','edwin@bargainmoulding.com','justin@bargainmoulding.com','matt@bargainmoulding.com','evener.umanzor@bargainmoulding.com']);
const STORES=[
  {key:'store_1',label:'Bargain Moulding',domain:'SHOPIFY_STORE_1_DOMAIN',clientId:'SHOPIFY_STORE_1_CLIENT_ID',clientSecret:'SHOPIFY_STORE_1_CLIENT_SECRET'},
  {key:'store_2',label:'Bargain Moulding CT',domain:'SHOPIFY_STORE_2_DOMAIN',clientId:'SHOPIFY_STORE_2_CLIENT_ID',clientSecret:'SHOPIFY_STORE_2_CLIENT_SECRET'}
];
const LOCATION_NAMES={'Bayview Warehouse':'336 Bayview','Bohemia Warehouse':'Bargain Moulding (Bohemia)','Riverhead Warehouse':'1133 Old Country (Riverhead)','Annex (Retail) 730':'Annex Warehouse'};

function cleanDomain(value){return String(value||'').replace(/^https?:\/\//,'').replace(/\/+$/,'')}
function serviceBase(value){const base=String(value||'').trim().replace(/\/+$/,'');if(!base)return'';return /^https?:\/\//i.test(base)?base:`https://${base}`}
async function authorizedUser(req){const bearer=String(req.headers.authorization||'');if(!bearer.startsWith('Bearer '))return null;const base=serviceBase(process.env.BM_WAREHOUSE_SUPABASE_URL),key=process.env.BM_WAREHOUSE_SUPABASE_SERVICE_ROLE_KEY;if(!cleanDomain(base)||!key)throw new Error('Warehouse authentication is not configured');const response=await fetch(`${base}/auth/v1/user`,{headers:{apikey:key,Authorization:bearer}});if(!response.ok)return null;const user=await response.json(),email=String(user.email||'').trim().toLowerCase(),profiles=await warehouseData(`warehouse_app_users?select=id,role,location&or=(auth_user_id.eq.${user.id},email.ilike.${encodeURIComponent(email)})&active=eq.true&limit=1`);return profiles[0]?{...user,bmProfile:profiles[0]}:null}
async function warehouseData(path,options={}){const base=serviceBase(process.env.BM_WAREHOUSE_SUPABASE_URL),key=process.env.BM_WAREHOUSE_SUPABASE_SERVICE_ROLE_KEY;if(!base||!key)throw new Error('Warehouse database is not configured');const response=await fetch(`${base}/rest/v1/${path}`,{...options,headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json',Accept:'application/json',...(options.headers||{})}}),data=await response.json().catch(()=>null);if(!response.ok)throw new Error(data?.message||data?.error||`Warehouse database request failed (${response.status})`);return data}
async function routingOverrides(){return warehouseData('shopify_order_routing_overrides?select=source_store,shopify_order_id,bucket,reason,resolved_by_name,resolved_at&limit=1000')}
async function saveRoutingOverride(req,user){const body=typeof req.body==='string'?JSON.parse(req.body):req.body||{},sourceStore=String(body.sourceStore||''),shopifyOrderId=String(body.shopifyOrderId||''),orderNumber=String(body.orderNumber||'').slice(0,50),bucket=String(body.bucket||''),reason=String(body.reason||'').trim().slice(0,250);if(!STORES.some(store=>store.key===sourceStore))throw new Error('Invalid Shopify store.');if(!/^gid:\/\/shopify\/Order\/\d+$/.test(shopifyOrderId))throw new Error('Invalid Shopify order.');if(!['willcall','delivery','ignore'].includes(bucket))throw new Error('Invalid routing choice.');const email=String(user.email||'').trim().toLowerCase(),name=String(user.user_metadata?.full_name||user.user_metadata?.name||email);const row={source_store:sourceStore,shopify_order_id:shopifyOrderId,order_number:orderNumber,bucket,reason:reason||null,resolved_by_user_id:user.id||null,resolved_by_name:name,resolved_by_email:email,resolved_at:new Date().toISOString()};const saved=await warehouseData('shopify_order_routing_overrides?on_conflict=source_store,shopify_order_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify(row)});await warehouseData('activity_events',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({user_id:user.id||null,user_name:name,user_email:email,action_type:'SHOPIFY_ORDER_ROUTED',document_type:'shopify_order',document_number:orderNumber,description:`${orderNumber||'Shopify order'} routed to ${bucket}`,status:bucket,metadata:{sourceStore,shopifyOrderId,bucket,reason:reason||null}})});return saved?.[0]||row}
async function access(store){const cached=tokenCache.get(store.key);if(cached&&cached.expiresAt>Date.now()+60000)return cached;const shop=cleanDomain(process.env[store.domain]),clientId=process.env[store.clientId],clientSecret=process.env[store.clientSecret];if(!shop||!clientId||!clientSecret)throw new Error(`${store.label}: Shopify connection is not configured`);const response=await fetch(`https://${shop}/admin/oauth/access_token`,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded',Accept:'application/json'},body:new URLSearchParams({grant_type:'client_credentials',client_id:clientId,client_secret:clientSecret})}),data=await response.json().catch(()=>null);if(!response.ok||!data?.access_token)throw new Error(`${store.label}: Shopify token failed (${response.status})`);const value={shop,token:data.access_token,expiresAt:Date.now()+Math.max(300,Number(data.expires_in||3600))*1000};tokenCache.set(store.key,value);return value}
function classify(method){const value=String(method||'').trim();if(!value)return'review';return value.toLowerCase()==='in store'?'willcall':'delivery'}
function isCustomDoor(line){const handle=String(line.product?.handle||'').toLowerCase(),title=String(line.product?.title||line.name||'').toLowerCase(),sku=String(line.sku||'').toUpperCase();return handle==='custom-pre-hung-door-assembly'||title.includes('custom pre-hung door assembly')||sku==='CUSTOM-PREHUNG-DOOR'}
function mapOrder(store,order){
  const method=String(order.shippingLine?.title||order.shippingLine?.code||'').trim(),lines=[],specialLines=[];
  for(const line of order.lineItems?.nodes||[]){const sku=String(line.sku||'').trim(),remaining=Number(line.unfulfilledQuantity||0);if(remaining<=0)continue;if(isCustomDoor(line))specialLines.push({lineItemId:line.id,sku:sku||'CUSTOM DOOR',name:line.name||line.product?.title||'Custom Pre-Hung Door Assembly',quantity:remaining,properties:(line.customAttributes||[]).filter(x=>String(x.value||'').trim()).map(x=>({key:String(x.key||'').replace(/^_/,''),value:String(x.value||'')}))});if(!sku)continue;const existing=lines.find(item=>item.sku.toUpperCase()===sku.toUpperCase());if(existing)existing.expected+=remaining;else lines.push({sku,name:line.name||sku,barcode:line.variant?.barcode||sku,expected:remaining})}
  const retailName=order.retailLocation?.name||'',warehouse=LOCATION_NAMES[retailName]||retailName,bucket=classify(method);
  return{ref:String(order.name||'').toUpperCase(),shopifyOrderId:order.id,shopifyAdminUrl:`https://admin.shopify.com/store/${cleanDomain(store.shop).split('.')[0]}/orders/${order.legacyResourceId}`,sourceStore:store.key,sourceStoreLabel:store.label,customer:'Shopify Customer',job:order.note||'',warehouse,deliveryMethod:method,bucket,status:'Unfulfilled',createdAt:order.createdAt,financialStatus:order.displayFinancialStatus,lines,specialLines,reviewReason:!method?'Delivery method is blank':!warehouse?'Warehouse assignment is blank':''}
}
async function ordersForStore(store){
  const{shop,token}=await access(store),query=`query BMUnfulfilledOrders($after:String){orders(first:40,after:$after,reverse:true,query:"status:open fulfillment_status:unfulfilled"){pageInfo{hasNextPage endCursor}nodes{id legacyResourceId name createdAt displayFinancialStatus displayFulfillmentStatus note retailLocation{name} shippingLine{title code deliveryCategory} lineItems(first:50){nodes{id name sku unfulfilledQuantity customAttributes{key value} product{handle title} variant{barcode}}}}}}`;
  const orders=[];let after=null;
  for(let page=0;page<4;page++){
    const response=await fetch(`https://${shop}/admin/api/${API_VERSION}/graphql.json`,{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json','X-Shopify-Access-Token':token},body:JSON.stringify({query,variables:{after}})}),payload=await response.json().catch(()=>null);
    if(!response.ok||!payload)throw new Error(`${store.label}: order query failed (${response.status})`);
    if(payload.errors?.length)throw new Error(`${store.label}: ${[...new Set(payload.errors.map(error=>error.message))].join('; ')}`);
    const connection=payload.data?.orders;orders.push(...(connection?.nodes||[]));
    if(!connection?.pageInfo?.hasNextPage||!connection.pageInfo.endCursor)break;
    after=connection.pageInfo.endCursor;
  }
  return orders.filter(order=>order.displayFulfillmentStatus==='UNFULFILLED').map(order=>mapOrder({...store,shop},order))
}

module.exports=async function(req,res){res.setHeader('Cache-Control','private, max-age=20');try{const user=await authorizedUser(req);if(!user)return res.status(401).json({ok:false,error:'Sign in with your Bargain Moulding Google account.'});if(req.method==='POST')return res.status(200).json({ok:true,override:await saveRoutingOverride(req,user),shopifyWritten:false});if(req.method!=='GET')return res.status(405).json({ok:false,error:'Method not allowed.'});const settled=await Promise.allSettled(STORES.map(ordersForStore)),orders=settled.flatMap(result=>result.status==='fulfilled'?result.value:[]),warnings=settled.filter(result=>result.status==='rejected').map(result=>result.reason.message);if(!orders.length&&warnings.length===STORES.length)throw new Error(warnings.join('; '));let overrides=[];try{overrides=await routingOverrides()}catch(error){warnings.push(`Saved routing choices unavailable: ${error.message}`)}const overrideMap=new Map(overrides.map(item=>[`${item.source_store}|${item.shopify_order_id}`,item])),routed=orders.map(order=>{const override=overrideMap.get(`${order.sourceStore}|${order.shopifyOrderId}`);return override?{...order,bucket:override.bucket,routingOverride:override}:order}).filter(order=>order.bucket!=='ignore'),specialOrders=routed.flatMap(order=>(order.specialLines||[]).map(line=>({...line,orderNumber:order.ref,shopifyOrderId:order.shopifyOrderId,shopifyAdminUrl:order.shopifyAdminUrl,sourceStore:order.sourceStore,sourceStoreLabel:order.sourceStoreLabel,customer:order.customer,createdAt:order.createdAt,financialStatus:order.financialStatus,deliveryMethod:order.deliveryMethod,warehouse:order.warehouse})));return res.status(200).json({ok:true,mode:'SHOPIFY_READ_ONLY_ORDERS',writesEnabled:false,orders:routed,specialOrders,counts:{willcall:routed.filter(order=>order.bucket==='willcall').length,delivery:routed.filter(order=>order.bucket==='delivery').length,review:routed.filter(order=>order.bucket==='review').length,special:specialOrders.length},warnings})}catch(error){return res.status(500).json({ok:false,mode:'SHOPIFY_READ_ONLY_ORDERS',writesEnabled:false,error:error.message})}}
