const API_VERSION='2026-07';
const tokenCache=new Map();
const ALLOWED_EMAILS=new Set(['greg@bargainmoulding.com','edwin@bargainmoulding.com','justin@bargainmoulding.com','matt@bargainmoulding.com','evener.umanzor@bargainmoulding.com']);
const STORES=[
  {key:'store_1',label:'Bargain Moulding',domain:'SHOPIFY_STORE_1_DOMAIN',clientId:'SHOPIFY_STORE_1_CLIENT_ID',clientSecret:'SHOPIFY_STORE_1_CLIENT_SECRET'},
  {key:'store_2',label:'Bargain Moulding CT',domain:'SHOPIFY_STORE_2_DOMAIN',clientId:'SHOPIFY_STORE_2_CLIENT_ID',clientSecret:'SHOPIFY_STORE_2_CLIENT_SECRET'}
];
const LOCATION_NAMES={'Bayview Warehouse':'336 Bayview','Bohemia Warehouse':'Bargain Moulding (Bohemia)','Riverhead Warehouse':'1133 Old Country (Riverhead)','Annex (Retail) 730':'Annex Warehouse'};

function cleanDomain(value){return String(value||'').replace(/^https?:\/\//,'').replace(/\/+$/,'')}
async function authorizedUser(req){const bearer=String(req.headers.authorization||'');if(!bearer.startsWith('Bearer '))return null;const base=cleanDomain(process.env.BM_WAREHOUSE_SUPABASE_URL),key=process.env.BM_WAREHOUSE_SUPABASE_SERVICE_ROLE_KEY;if(!base||!key)throw new Error('Warehouse authentication is not configured');const response=await fetch(`${base}/auth/v1/user`,{headers:{apikey:key,Authorization:bearer}});if(!response.ok)return null;const user=await response.json(),email=String(user.email||'').trim().toLowerCase();return ALLOWED_EMAILS.has(email)?user:null}
async function access(store){const cached=tokenCache.get(store.key);if(cached&&cached.expiresAt>Date.now()+60000)return cached;const shop=cleanDomain(process.env[store.domain]),clientId=process.env[store.clientId],clientSecret=process.env[store.clientSecret];if(!shop||!clientId||!clientSecret)throw new Error(`${store.label}: Shopify connection is not configured`);const response=await fetch(`https://${shop}/admin/oauth/access_token`,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded',Accept:'application/json'},body:new URLSearchParams({grant_type:'client_credentials',client_id:clientId,client_secret:clientSecret})}),data=await response.json().catch(()=>null);if(!response.ok||!data?.access_token)throw new Error(`${store.label}: Shopify token failed (${response.status})`);const value={shop,token:data.access_token,expiresAt:Date.now()+Math.max(300,Number(data.expires_in||3600))*1000};tokenCache.set(store.key,value);return value}
function classify(methods){if(!methods.length||methods.some(method=>!method.methodType&&!String(method.presentedName||'').trim()))return'review';return methods.every(method=>method.methodType==='RETAIL'||String(method.presentedName||'').trim().toLowerCase()==='in store')?'willcall':'delivery'}
function methodLabel(methods){if(!methods.length)return'';return[...new Set(methods.map(method=>method.methodType==='RETAIL'?'In Store':method.presentedName||String(method.methodType||'').replaceAll('_',' ')).filter(Boolean))].join(' / ')}
function mapOrder(store,order){const fulfillmentOrders=order.fulfillmentOrders?.nodes||[],methods=fulfillmentOrders.map(row=>row.deliveryMethod||{}),assigned=[...new Set(fulfillmentOrders.map(row=>row.assignedLocation?.location?.name||row.assignedLocation?.name).filter(Boolean))],lines=[];for(const fulfillment of fulfillmentOrders){for(const node of fulfillment.lineItems?.nodes||[]){const line=node.lineItem||{},sku=String(line.sku||'').trim();if(!sku||Number(node.remainingQuantity||0)<=0)continue;const existing=lines.find(item=>item.sku.toUpperCase()===sku.toUpperCase());if(existing)existing.expected+=Number(node.remainingQuantity||0);else lines.push({sku,name:line.name||sku,barcode:line.variant?.barcode||sku,expected:Number(node.remainingQuantity||0)})}}const bucket=classify(methods),warehouse=assigned.length===1?(LOCATION_NAMES[assigned[0]]||assigned[0]):assigned.length>1?'Multiple Warehouses':'';return{ref:String(order.name||'').toUpperCase(),shopifyOrderId:order.id,sourceStore:store.key,sourceStoreLabel:store.label,customer:order.customer?.displayName||order.billingAddress?.name||'Customer',job:order.note||'',warehouse,deliveryMethod:methodLabel(methods),bucket,status:'Unfulfilled',createdAt:order.createdAt,financialStatus:order.displayFinancialStatus,lines,reviewReason:!methods.length?'Delivery method is blank':assigned.length>1?'Order is assigned to multiple warehouses':!warehouse?'Warehouse assignment is blank':''}}
async function ordersForStore(store){const{shop,token}=await access(store),query=`query BMUnfulfilledOrders{orders(first:100,reverse:true,query:"status:open fulfillment_status:unfulfilled"){nodes{id name createdAt displayFinancialStatus displayFulfillmentStatus note customer{displayName} billingAddress{name} fulfillmentOrders(first:20){nodes{id status assignedLocation{name location{id name}} deliveryMethod{methodType presentedName} lineItems(first:100){nodes{remainingQuantity lineItem{name sku variant{barcode}}}}}}}}}`;const response=await fetch(`https://${shop}/admin/api/${API_VERSION}/graphql.json`,{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json','X-Shopify-Access-Token':token},body:JSON.stringify({query})}),payload=await response.json().catch(()=>null);if(!response.ok||!payload)throw new Error(`${store.label}: order query failed (${response.status})`);if(payload.errors?.length)throw new Error(`${store.label}: ${payload.errors.map(error=>error.message).join('; ')}`);return(payload.data?.orders?.nodes||[]).filter(order=>order.displayFulfillmentStatus!=='FULFILLED').map(order=>mapOrder(store,order))}

module.exports=async function(req,res){res.setHeader('Cache-Control','private, max-age=20');try{const user=await authorizedUser(req);if(!user)return res.status(401).json({ok:false,error:'Sign in with your Bargain Moulding Google account.'});const settled=await Promise.allSettled(STORES.map(ordersForStore)),orders=settled.flatMap(result=>result.status==='fulfilled'?result.value:[]),warnings=settled.filter(result=>result.status==='rejected').map(result=>result.reason.message);if(!orders.length&&warnings.length===STORES.length)throw new Error(warnings.join('; '));return res.status(200).json({ok:true,mode:'SHOPIFY_READ_ONLY_ORDERS',writesEnabled:false,orders,counts:{willcall:orders.filter(order=>order.bucket==='willcall').length,delivery:orders.filter(order=>order.bucket==='delivery').length,review:orders.filter(order=>order.bucket==='review').length},warnings})}catch(error){return res.status(500).json({ok:false,mode:'SHOPIFY_READ_ONLY_ORDERS',writesEnabled:false,error:error.message})}}
